/**
 * Copy namespace: ASSIST ("Ask about this step" composer, suggestions, answer card, demo-mode label, guard notice) — owner: web
 * upload-review + assistant agent. Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass
 * `python3 tools/advice_lint.py`; no em dashes. The composer's aria-describedby sentence is information-only by construction.
 * `suggestions` mirrors api/app/assistant_templates.py SUGGESTIONS (keyed by engine rule code); the server's `suggested` list replaces
 * them after the first answer.
 */
export const ASSIST = {
  heading: "Ask about this cost",
  clauseHeading: "Ask about this rule",
  planHeading: "Ask about this plan",
  placeholder: "Ask what you pay…",
  clausePlaceholder: "Ask about this rule…",
  planPlaceholder: "Ask about this plan…",
  send: "Ask",
  scopeLabel: "What the question is about",
  scopeStep: "This step",
  scopeProcedure: "This care",
  scopePlan: "Whole plan",
  scopeClause: "This rule",
  describedBy: "Answers show what you pay and what insurance pays. Just numbers, no advice.",
  suggestionsLabel: "Questions you can tap",
  sending: "Reading your numbers…",
  sendingClause: "Reading the rule…",
  readIn: (n: number) => `${n} lookup${n === 1 ? "" : "s"}`,
  asked: (q: string) => `Asked: ${q}`,
  answerHeading: "What you pay and what insurance pays",
  demoRibbon: "Practice mode: ready-made answers from our math, not the computer helper.",
  fixedTemplate: "Ready-made answer from our math, not the computer helper.",
  liveFallback: "The model did not answer in time; a template answer is shown.",
  liveLabel: (model: string) => `Computer helper: ${model}. Every number comes from our math.`,
  demoEnvironment: "Practice mode: ready-made answers from our math.",
  guardRemoved: (n: number) => (n === 1 ? "1 sentence was taken out because it gave advice." : `${n} sentences were taken out because they gave advice.`),
  groundingRemoved: (n: number) => (n === 1 ? "1 sentence had a number we can't back up, so it is hidden." : `${n} sentences had numbers we can't back up, so they are hidden.`),
  nothingSurvived: "No answer passed our no-advice check. Here are the rule and the step.",
  rateLimited: "Lots of questions fast. The box opens again soon.",
  offline: "The helper needs the internet. The map and numbers still work.",
  failed: "The helper didn't answer. The map and numbers still work.",
  notFound: "We couldn't find these numbers, so the question wasn't sent.",
  adviceLabel: "Just numbers, no advice",
  outOfScopeLabel: "Not about cost",
  clarifyLabel: "Which care?",
  whatIfLabel: "Guesses",
  toolsUsed: "Looked up:",
  // demo-19: lookups in plain words (the ids resolve against the estimate the client holds; numbering is 1-based; no amounts)
  lookupBenefits: (code: string) => `Your benefit figures for ${code}`,
  lookupLine: (name: string) => `${name}: estimate line`,
  lookupStep: (name: string, step: string) => `${name}: ${step} step`,
  lookupStepUnnamed: (name: string, n: number) => `${name}: step ${n}`,
  lookupRules: (procedure: string) => `Plan rules for ${procedure}`,
  lookupClause: (id: string) => `Plan clause ${id}`,
  lookupProcedures: "Procedure names",
  lookupLineN: (n: number) => `Line ${n}`,
  stepRule: {
    fee: "dentist's fee", N: "allowed amount", AB: "alternate benefit", D: "deductible", CO: "plan share", M: "annual maximum",
    X: "exclusion", W: "waiting period", F: "frequency", total: "your share",
  } as Record<string, string>,
  toolName: {
    get_estimate_line: "ledger", explain_step: "step", get_plan_rules: "rules for", get_clause: "clause", get_benefits: "benefits of", resolve_procedure: "procedure names",
  } as Record<string, string>,
  refStep: (label: string) => `Step: ${label}`,
  refPatientTotal: "You pay on this line",
  refPlanTotal: "Insurance pays on this line",
  refClause: (stitch: string) => `Clause ${stitch}`,
  refField: {
    "plan.deductible_individual": "Part you pay first (plan papers)",
    "plan.annual_max": "Most insurance pays a year (plan papers)",
    "plan.benefit_year_start_month": "Benefit year start (plan document)",
    "plan.annual_max_unlimited": "Annual maximum: whether one applies",
    "benefits.remaining_deductible_cents": "Pay-first part left (your papers)",
    "benefits.remaining_max_cents": "Yearly limit left (your papers)",
    "benefits.deductible_met_cents": "Deductible met (your records)",
    "benefits.benefits_used_cents": "Benefits used (your records)",
    "rules.plan_pays_pct": "Insurance pays (plan table)",
    "rules.you_pay_pct": "You pay (plan table)",
    "rules.category": "Coverage class",
    "rules.deductible_applies": "Deductible applies",
    "rules.alternate_benefit": "Alternate benefit rule",
    "rules.frequency": "Frequency limit",
    "rules.waiting": "Waiting period",
    "rules.covered": "Covered",
    "treatment_item.dentist_fee_cents": "Dentist's price (your letter)",
    "treatment_item.allowed_cents": "Price your plan agreed to (your papers)",
    "estimate.inputs.hypotheticals": "Hypotheticals on this estimate",
    "estimate.missing_inputs": "Inputs the estimate is waiting for",
    "estimate.ledger.not_provided": "Inputs not provided",
    "estimate.ledger.patient_total_cents": "You pay for this care (we did the math)",
    "estimate.ledger.plan_total_cents": "Insurance pays for this care (we did the math)",
  } as Record<string, string>,
  refFlags: (i: number) => `Flags on line ${i + 1}`,
  refRemainingAfter: (i: number, which: string) => `${which === "deductible_cents" ? "Deductible" : "Annual maximum"} left after line ${i + 1}`,
  unlimited: "no yearly limit",
  notStated: "the papers don't say",
  notProvided: "missing",
  notLoaded: "figure not loaded",
  yes: "yes",
  no: "no",
  none: "none",
  loadingData: "Reading the estimate, the plan and your records…",
  footer: "Information from your documents and your inputs. Not advice. Not the plan's determination.",
  // mirrored from api/app/assistant_templates.py SUGGESTIONS (keyed by rule code)
  suggestions: {
    D: ["What deductible amount was applied to this line?", "Where does the remaining deductible figure come from?", "What does the plan document say about the deductible?"],
    CO: ["What share of this line does the plan pay?", "Where does the coinsurance percentage come from?", "What does the plan document say about this coverage class?"],
    M: ["Does this line stay within the remaining annual maximum?", "Where does the remaining maximum figure come from?", "What does the plan document say about the annual maximum?"],
    AB: ["Does an alternate benefit apply to this line?", "What does the plan document say about alternate benefits?", "Which clause is behind this step?"],
    N: ["Why do the fee and the allowed amount differ?", "Where does the allowed amount come from?", "What does the plan document say about network payment?"],
    fee: ["Where does the dentist's fee come from?", "Which steps on this line are cited to the plan document?", "What is waiting for information on this line?"],
    total: ["Which steps make up your share on this line?", "Which clauses are behind this line?", "Where does each figure on this line come from?"],
    X: ["Which clause excludes this procedure?", "What does the plan document say about this exclusion?", "Which steps on this line are cited?"],
    clause: ["What does this sentence change in my estimate?", "Which procedures does this sentence apply to?"],
    default: ["What does this step mean?", "Where does this figure come from?", "What does the plan document say here?"],
  } as Record<string, string[]>,

  // ---- the AskBox: "Ask in plain words" on every tab (desktop card; phone field above the dock + bottom sheet) ----
  boxTitle: "Ask in plain words",
  boxPlaceholder: "Ask anything about your plan, in your own words",
  boxDescribedBy: "Answers come from your plan document and your estimate, in everyday words. Information, not advice.",
  boxSending: "Reading your plan and your estimate…",
  boxSuggestionsLabel: "Questions people often ask",
  boxOpen: "Ask in plain words",
  boxClose: "Close",
  boxEarlier: (n: number) => (n === 1 ? "1 earlier answer" : `${n} earlier answers`),
  boxNothingSurvived: "No plain-words answer passed the information-only check. What the answer looked up is listed below.",
  liveUnavailable: "The live model is not answering right now. The map, the plan and the clauses do not depend on it.",
  // the answer card
  simpleLabel: "In simple terms",
  calcWords: "calculated from the clauses cited",
  simplerLabel: "Even simpler",
  sayItSimpler: "Say it more simply",
  sayingItSimpler: "Finding plainer words…",
  noSimpler: "No plainer version came back for this answer.",
  showDetails: "Show the details",
  hideDetails: "Hide the details",
  announce: (text: string) => `Answer: ${text}`,
  announceSimpler: (text: string) => `Even simpler: ${text}`,
  // tab-aware suggestion chips (everyday wording; the journey's comparison chip is built from the journey's own procedures)
  boxChips: {
    journey: ["What will I pay in total?", "What is a deductible?", "How much of my yearly maximum is left?"],
    plan: ["What is a deductible?", "What does plan share mean?", "What is an annual maximum?", "What is a waiting period?"],
    compare: ["What is the difference between these plans' deductibles?", "What does 'allowed amount' mean?", "What is an annual maximum?", "What does in-network mean?"],
    documents: ["What does this document cover?", "What is a frequency limit?", "What is an alternate benefit?", "What does 'not covered' mean?"],
  } as Record<string, string[]>,
  chipWhyMore: (higher: string, lower: string) => `Why does ${higher} cost more than ${lower}?`,
  chipWhatFor: (name: string) => `What do I pay for ${name}?`,
  chipFallback: "What does plan share mean?",
  /** Everyday names for the 16 procedure keys, used only to build the journey's comparison chip. */
  everydayName: {
    exam: "the checkup", cleaning: "the cleaning", bitewing_xrays: "the x-rays", fluoride_child: "the fluoride treatment", sealant: "the sealant",
    composite: "the filling", amalgam: "the filling", extraction_simple: "the extraction", extraction_surgical: "the surgical extraction",
    scaling_root_planing: "the deep cleaning", root_canal_molar: "the root canal", crown: "the crown", cast_crown: "the metal crown",
    denture_partial: "the partial denture", implant: "the implant", night_guard: "the night guard",
  } as Record<string, string>,
} as const satisfies Record<string, string | string[] | Record<string, string | string[]> | ((...a: never[]) => string)>;
