/**
 * Copy namespace: ASSIST ("Ask about this step" composer, suggestions, answer card, demo-mode label, guard notice) — owner: web
 * upload-review + assistant agent. Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass
 * `python3 tools/advice_lint.py`; no em dashes. The composer's aria-describedby sentence is information-only by construction.
 * `suggestions` mirrors api/app/assistant_templates.py SUGGESTIONS (keyed by engine rule code); the server's `suggested` list replaces
 * them after the first answer.
 */
export const ASSIST = {
  heading: "Ask about this step",
  clauseHeading: "Ask about this clause",
  planHeading: "Ask about this plan",
  placeholder: "Ask about this step…",
  clausePlaceholder: "Ask about this clause…",
  planPlaceholder: "Ask about this plan…",
  send: "Ask",
  scopeLabel: "Scope of the question",
  scopeStep: "This step",
  scopeProcedure: "This procedure",
  scopePlan: "Whole plan",
  scopeClause: "This clause",
  describedBy: "Answers quote your plan document and your estimate. This is information, not advice.",
  suggestionsLabel: "Suggested questions",
  sending: "Reading the selected step…",
  sendingClause: "Reading the selected clause…",
  readIn: (n: number) => `${n} lookup${n === 1 ? "" : "s"}`,
  asked: (q: string) => `Asked: ${q}`,
  answerHeading: "What the records and the document say",
  demoRibbon: "Fixed answer: put together from your plan's numbers. No AI is turned on.",
  fixedTemplate: "Fixed answer: put together from your plan's numbers, not written by AI.",
  liveFallback: "The model did not answer in time; a template answer is shown.",
  liveLabel: (model: string) => `Written by AI from your plan's numbers (${model}).`,
  demoEnvironment: "Demo environment: template answers until a model is configured.",
  guardRemoved: (n: number) => (n === 1 ? "1 sentence was removed by the information-only check." : `${n} sentences were removed by the information-only check.`),
  groundingRemoved: (n: number) => (n === 1 ? "1 sentence named a figure the records do not hold and was not shown." : `${n} sentences named a figure the records do not hold and were not shown.`),
  nothingSurvived: "No sentence about this step passed the information-only check; the clause and step are listed instead.",
  rateLimited: "Too many questions in a short time; the composer opens again in a moment.",
  offline: "The assistant needs the API. The map, the pipeline and the clauses do not.",
  failed: "The assistant did not answer. The map, the pipeline and the clauses do not depend on it.",
  notFound: "The selected estimate or plan is not in your space; the question was not sent.",
  adviceLabel: "Information, not a choice",
  outOfScopeLabel: "Outside this assistant's scope",
  clarifyLabel: "Which procedure?",
  whatIfLabel: "Hypotheticals",
  toolsUsed: "Looked up:",
  // demo-19: lookups in plain words (the ids resolve against the estimate the client holds; numbering is 1-based; no amounts)
  lookupBenefits: (code: string) => `Your benefit figures for ${code}`,
  lookupLine: (name: string) => `${name}: estimate line`,
  lookupStep: (name: string, step: string) => `${name}: ${step} step`,
  lookupStepUnnamed: (name: string, n: number) => `${name}: step ${n}`,
  lookupRules: (procedure: string) => `Plan rules for ${procedure}`,
  lookupClause: (id: string) => `Plan clause ${id}`,
  lookupProcedures: "Procedure names",
  lookupLineN: (n: number) => `Line ${n}`,
  stepRule: {
    fee: "dentist's fee", N: "allowed amount", AB: "alternate benefit", D: "deductible", CO: "plan share", M: "annual maximum",
    X: "exclusion", W: "waiting period", F: "frequency", total: "your share",
  } as Record<string, string>,
  toolName: {
    get_estimate_line: "ledger", explain_step: "step", get_plan_rules: "rules for", get_clause: "clause", get_benefits: "benefits of", resolve_procedure: "procedure names",
  } as Record<string, string>,
  refStep: (label: string) => `Step: ${label}`,
  refPatientTotal: "You pay on this line",
  refPlanTotal: "The plan pays on this line",
  refClause: (stitch: string) => `Clause ${stitch}`,
  refField: {
    "plan.deductible_individual": "Deductible (plan document)",
    "plan.annual_max": "Annual maximum (plan document)",
    "plan.benefit_year_start_month": "Benefit year start (plan document)",
    "plan.annual_max_unlimited": "Annual maximum: whether one applies",
    "benefits.remaining_deductible_cents": "Remaining deductible (your records)",
    "benefits.remaining_max_cents": "Remaining annual maximum (your records)",
    "benefits.deductible_met_cents": "Deductible met (your records)",
    "benefits.benefits_used_cents": "Benefits used (your records)",
    "rules.plan_pays_pct": "Plan share (coverage table)",
    "rules.you_pay_pct": "Your share (coverage table)",
    "rules.category": "Coverage class",
    "rules.deductible_applies": "Deductible applies",
    "rules.alternate_benefit": "Alternate benefit rule",
    "rules.frequency": "Frequency limit",
    "rules.waiting": "Waiting period",
    "rules.covered": "Covered",
    "treatment_item.dentist_fee_cents": "Dentist's fee (your estimate)",
    "treatment_item.allowed_cents": "Allowed amount (your records)",
    "estimate.inputs.hypotheticals": "Hypotheticals on this estimate",
    "estimate.missing_inputs": "Inputs the estimate is waiting for",
    "estimate.ledger.not_provided": "Inputs not provided",
    "estimate.ledger.patient_total_cents": "You pay for the planned work (calculated)",
    "estimate.ledger.plan_total_cents": "The plan pays for the planned work (calculated)",
  } as Record<string, string>,
  refFlags: (i: number) => `Flags on line ${i + 1}`,
  refRemainingAfter: (i: number, which: string) => `${which === "deductible_cents" ? "Deductible" : "Annual maximum"} left after line ${i + 1}`,
  unlimited: "no annual maximum stated",
  notStated: "not stated in this document",
  notProvided: "not provided",
  notLoaded: "figure not loaded",
  yes: "yes",
  no: "no",
  none: "none",
  loadingData: "Reading the estimate, the plan and your records…",
  footer: "Information from your documents and your inputs. Not advice. Not the plan's determination.",
  // mirrored from api/app/assistant_templates.py SUGGESTIONS (keyed by rule code)
  suggestions: {
    D: ["What deductible amount was applied to this line?", "Where does the remaining deductible figure come from?", "What does the plan document say about the deductible?"],
    CO: ["What share of this line does the plan pay?", "Where does the coinsurance percentage come from?", "What does the plan document say about this coverage class?"],
    M: ["Does this line stay within the remaining annual maximum?", "Where does the remaining maximum figure come from?", "What does the plan document say about the annual maximum?"],
    AB: ["Does an alternate benefit apply to this line?", "What does the plan document say about alternate benefits?", "Which clause is behind this step?"],
    N: ["Why do the fee and the allowed amount differ?", "Where does the allowed amount come from?", "What does the plan document say about network payment?"],
    fee: ["Where does the dentist's fee come from?", "Which steps on this line are cited to the plan document?", "What is waiting for information on this line?"],
    total: ["Which steps make up your share on this line?", "Which clauses are behind this line?", "Where does each figure on this line come from?"],
    X: ["Which clause excludes this procedure?", "What does the plan document say about this exclusion?", "Which steps on this line are cited?"],
    clause: ["What does this sentence change in my estimate?", "Which procedures does this sentence apply to?"],
    default: ["What does this step mean?", "Where does this figure come from?", "What does the plan document say here?"],
  } as Record<string, string[]>,

  // ---- the AskBox: "Ask in plain words" on every tab (desktop card; phone field above the dock + bottom sheet) ----
  boxTitle: "Ask what it costs",
  boxPlaceholder: "Ask what something costs, like a cleaning",
  boxDescribedBy: "We show two numbers: what you pay, and what insurance pays. Just numbers, no advice.",
  boxSending: "Doing the math…",
  boxSuggestionsLabel: "Try one of these",
  boxOpen: "Ask what it costs",
  boxClose: "Close",
  boxEarlier: (n: number) => (n === 1 ? "1 earlier answer" : `${n} earlier answers`),
  boxNothingSurvived: "No plain-words answer passed the information-only check. What the answer looked up is listed below.",
  liveUnavailable: "The live model is not answering right now. The map, the plan and the clauses do not depend on it.",
  // the answer card
  simpleLabel: "In simple terms",
  calcWords: "calculated from the clauses cited",
  simplerLabel: "Even simpler",
  sayItSimpler: "Say it more simply",
  sayingItSimpler: "Finding plainer words…",
  noSimpler: "No plainer version came back for this answer.",
  showDetails: "Show the details",
  hideDetails: "Hide the details",
  announce: (text: string) => `Answer: ${text}`,
  announceSimpler: (text: string) => `Even simpler: ${text}`,
  // tab-aware suggestion chips (everyday wording; the journey's comparison chip is built from the journey's own procedures)
  /** kid-simple cost questions (owner: only a cost breakdown; one plan per answer, no comparing) */
  boxChips: ["How much is a cleaning?", "How much is a filling?", "How much is a crown?", "What does deductible mean?"] as string[],
  // the plan dropdown and the hero numbers of a procedure_cost answer
  planSelectLabel: "Plan",
  heroYouPay: "You pay",
  heroPlanPays: "Insurance pays",
  heroPrice: "The dentist's price",
  heroPriceGuess: "Our guess of the price",
  heroMath: "We did the math from your plan",
  heroFor: (plan: string) => `With ${plan}`,
  chipWhyMore: (higher: string, lower: string) => `Why does ${higher} cost more than ${lower}?`,
  chipWhatFor: (name: string) => `What do I pay for ${name}?`,
  chipFallback: "What does plan share mean?",
  /** Everyday names for the 16 procedure keys, used only to build the journey's comparison chip. */
  everydayName: {
    exam: "the checkup", cleaning: "the cleaning", bitewing_xrays: "the x-rays", fluoride_child: "the fluoride treatment", sealant: "the sealant",
    composite: "the filling", amalgam: "the filling", extraction_simple: "the extraction", extraction_surgical: "the surgical extraction",
    scaling_root_planing: "the deep cleaning", root_canal_molar: "the root canal", crown: "the crown", cast_crown: "the metal crown",
    denture_partial: "the partial denture", implant: "the implant", night_guard: "the night guard",
  } as Record<string, string>,
} as const satisfies Record<string, string | string[] | Record<string, string | string[]> | ((...a: never[]) => string)>;
