/**
 * Copy namespace: ASSIST ("Ask about this step" composer, suggestions, answer card, demo-mode label, guard notice) — owner: web
 * upload-review + assistant agent. Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass
 * `python3 tools/advice_lint.py`; no em dashes. The composer's aria-describedby sentence is information-only by construction.
 * `suggestions` mirrors api/app/assistant_templates.py SUGGESTIONS (keyed by engine rule code); the server's `suggested` list replaces
 * them after the first answer.
 */
export const ASSIST = {
  heading: "Ask about this step",
  clauseHeading: "Ask about this clause",
  planHeading: "Ask about this plan",
  placeholder: "Ask about this step…",
  clausePlaceholder: "Ask about this clause…",
  planPlaceholder: "Ask about this plan…",
  send: "Ask",
  scopeLabel: "Scope of the question",
  scopeStep: "This step",
  scopeProcedure: "This procedure",
  scopePlan: "Whole plan",
  scopeClause: "This clause",
  describedBy: "Answers quote your plan document and your estimate. This is information, not advice.",
  suggestionsLabel: "Suggested questions",
  sending: "Reading the selected step…",
  sendingClause: "Reading the selected clause…",
  readIn: (n: number) => `${n} lookup${n === 1 ? "" : "s"} in`,
  asked: (q: string) => `Asked: ${q}`,
  answerHeading: "What the records and the document say",
  demoRibbon: "Demo mode: template answers assembled from the engine's fields, not a live model.",
  fixedTemplate: "Fixed template: assembled from the engine's fields, not a live model.",
  liveFallback: "The model did not answer in time; a template answer is shown.",
  liveLabel: (model: string) => `Live model: ${model}. Each sentence cites a figure from your records; sentences that state their own amounts are removed.`,
  demoEnvironment: "Demo environment: template answers until a model is configured.",
  guardRemoved: (n: number) => `${n} sentence${n === 1 ? "" : "s"} were removed by the information-only check.`,
  groundingRemoved: (n: number) => `${n} sentence${n === 1 ? "" : "s"} named a figure the records do not hold and were not shown.`,
  nothingSurvived: "No sentence about this step passed the information-only check; the clause and step are listed instead.",
  rateLimited: "Too many questions in a short time; the composer opens again in a moment.",
  offline: "The assistant needs the API. The map, the pipeline and the clauses do not.",
  failed: "The assistant did not answer. The map, the pipeline and the clauses do not depend on it.",
  notFound: "The selected estimate or plan is not in your space; the question was not sent.",
  adviceLabel: "Information, not a choice",
  outOfScopeLabel: "Outside this assistant's scope",
  clarifyLabel: "Which procedure?",
  whatIfLabel: "Hypotheticals",
  toolsUsed: "Looked up:",
  toolName: {
    get_estimate_line: "ledger", explain_step: "step", get_plan_rules: "rules for", get_clause: "clause", get_benefits: "benefits of", resolve_procedure: "procedure names",
  } as Record<string, string>,
  refStep: (label: string) => `Step: ${label}`,
  refPatientTotal: "You pay on this line",
  refPlanTotal: "The plan pays on this line",
  refClause: (stitch: string) => `Clause ${stitch}`,
  refField: {
    "plan.deductible_individual": "Deductible (plan document)",
    "plan.annual_max": "Annual maximum (plan document)",
    "plan.benefit_year_start_month": "Benefit year start (plan document)",
    "plan.annual_max_unlimited": "Annual maximum: whether one applies",
    "benefits.remaining_deductible_cents": "Remaining deductible (your records)",
    "benefits.remaining_max_cents": "Remaining annual maximum (your records)",
    "benefits.deductible_met_cents": "Deductible met (your records)",
    "benefits.benefits_used_cents": "Benefits used (your records)",
    "rules.plan_pays_pct": "Plan share (coverage table)",
    "rules.you_pay_pct": "Your share (coverage table)",
    "rules.category": "Coverage class",
    "rules.deductible_applies": "Deductible applies",
    "rules.alternate_benefit": "Alternate benefit rule",
    "rules.frequency": "Frequency limit",
    "rules.waiting": "Waiting period",
    "rules.covered": "Covered",
    "treatment_item.dentist_fee_cents": "Dentist's fee (your estimate)",
    "treatment_item.allowed_cents": "Allowed amount (your records)",
    "estimate.inputs.hypotheticals": "Hypotheticals on this estimate",
    "estimate.missing_inputs": "Inputs the estimate is waiting for",
    "estimate.ledger.not_provided": "Inputs not provided",
  } as Record<string, string>,
  refFlags: (i: number) => `Flags on line ${i + 1}`,
  refRemainingAfter: (i: number, which: string) => `${which === "deductible_cents" ? "Deductible" : "Annual maximum"} left after line ${i + 1}`,
  unlimited: "no annual maximum stated",
  notStated: "not stated in this document",
  notProvided: "not provided",
  notLoaded: "figure not loaded",
  yes: "yes",
  no: "no",
  none: "none",
  loadingData: "Reading the estimate, the plan and your records…",
  footer: "Information from your documents and your inputs. Not advice. Not the plan's determination.",
  // mirrored from api/app/assistant_templates.py SUGGESTIONS (keyed by rule code)
  suggestions: {
    D: ["What deductible amount was applied to this line?", "Where does the remaining deductible figure come from?", "What does the plan document say about the deductible?"],
    CO: ["What share of this line does the plan pay?", "Where does the coinsurance percentage come from?", "What does the plan document say about this coverage class?"],
    M: ["Does this line stay within the remaining annual maximum?", "Where does the remaining maximum figure come from?", "What does the plan document say about the annual maximum?"],
    AB: ["Does an alternate benefit apply to this line?", "What does the plan document say about alternate benefits?", "Which clause is behind this step?"],
    N: ["Why do the fee and the allowed amount differ?", "Where does the allowed amount come from?", "What does the plan document say about network payment?"],
    fee: ["Where does the dentist's fee come from?", "Which steps on this line are cited to the plan document?", "What is waiting for information on this line?"],
    total: ["Which steps make up your share on this line?", "Which clauses are behind this line?", "Where does each figure on this line come from?"],
    X: ["Which clause excludes this procedure?", "What does the plan document say about this exclusion?", "Which steps on this line are cited?"],
    clause: ["What does this sentence change in my estimate?", "Which procedures does this sentence apply to?"],
    default: ["What does this step mean?", "Where does this figure come from?", "What does the plan document say here?"],
  } as Record<string, string[]>,
} as const satisfies Record<string, string | string[] | Record<string, string | string[]> | ((...a: never[]) => string)>;
