/**
 * Copy namespace: DRAWER (procedure drawer, dollar pipeline, clause evidence, START and Harbor Light drawers).
 * Owner: web drawer + pipeline agent (spec §4.4, §4.5, §5.5). `lib/copy.ts` re-exports this file (the integrator swaps the
 * `DRAWER` export in copy/passage.ts for this one). Every string passes `python3 tools/advice_lint.py`: state what the documents say,
 * what the records say and what the arithmetic yields; never tell the user what to do; no em dashes; nothing recommends or ranks.
 */
export const DRAWER = {
  // shell
  region: "Procedure details",
  close: "Close details",
  crumbs: (order: number, n: number, place: string) => `Island ${order} of ${n} · ${place}`,
  crumbsStart: (place: string) => `Start · ${place}`,
  // the Harbor Light island's place is "Harbor Light" itself (lib/islands.ts LIGHT_PLACE): never print it twice (slop-18)
  crumbsLight: (place: string) => (place === "Harbor Light" ? "End of the route" : `Harbor Light · ${place}`),
  crumbsVisited: (place: string) => `Completed on your statement · ${place}`,
  crumbsMarginal: (place: string) => `Mentioned at the consultation · ${place}`,
  checkpointStrip: "Checkpoints on this island, in trail order",
  checkpointName: (term: string, amount: string) => `${term}: ${amount}`,
  youPayLede: "You pay",
  planPaysLede: "plan",
  planPaysRow: "Plan pays",
  beforeIsland: "Before this island",
  calculatedShort: "calculated",
  waitingInfo: "Waiting for information",
  noAmount: "no amount",
  estimateUpdated: "Estimate updated",
  pipelineHint: "The pipeline scrolls sideways; every node is also a row in the receipt below.",

  // section headings (spec §4.4; the checks look for these exact texts)
  sProcedure: "Procedure",
  sAllowance: "Allowance",
  sDeductible: "Deductible",
  sShare: "Coverage share",
  sAnnualMax: "Annual maximum",
  sFrequency: "Frequency",
  sWaiting: "Waiting period",
  sAlternate: "Alternate benefit (downgrade)",
  sExclusions: "Exclusions",
  sFinalCost: "Final cost",
  sCalculation: "How was this calculated?",
  calculated: "Calculated from the steps below",
  /** The same label away from a step list (map, overview, Answers log, stage panel): the figure is engine arithmetic over cited clauses. */
  calculatedCited: "Calculated from the clauses cited",
  calcFromRoute: "Calculated from your statement and the islands up to here",
  remainingBeforeLater: "The figure after the previous island on the route: your statement figure, then each earlier island in processing order.",
  harborTableNote: "Each figure is calculated from that island's steps; its stitch opens the clause behind it.",
  sEvidence: "Clause evidence",
  sPlan: "Plan",
  sRecords: "Records",
  sBenefitsForm: "Benefit statement figures",
  sTotals: "Totals for the route",
  sPerIsland: "Each island on the route",
  sAfterRoute: "After the route",
  sClaim: "Figures from your benefit statement",
  sRule: "Coverage rule",
  expand: "Open",
  collapse: "Close",

  // 1 Procedure
  identifier: "Identifier",
  asWritten: "as written on your estimate",
  noCode: "No code is printed in this document",
  dates: "Dates",
  dateAppointment: "appointment",
  datePrep: "preparation, planned",
  dateCompletion: "completion, planned",
  dentistFee: "Dentist's fee",
  quantity: (q: number) => `quantity ${q}`,
  planCategory: "Plan category",
  recordSource: "Record source",
  statusWord: (s: string) => s.replace(/_/g, " "),
  toothWord: (t: string) => `tooth ${t}`,

  // 2 Allowance
  allowedAmount: "Allowed amount",
  network: "Network",
  inNetwork: "in-network",
  outNetwork: "out-of-network",
  networkNotProvided: "Network status is not provided. In-network and out-of-network amounts differ; the estimate stays unresolved until it is entered.",
  allowedMissingTitle: "What this line is waiting for",
  allowedInputLabel: "Allowed amount, in dollars",
  allowedSourceLabel: "Where the allowed amount comes from (document and date)",
  allowedRecord: "Record the allowed amount",
  allowedRecorded: "Recorded. The estimate is recalculated from your records.",
  allowedFailed: "The allowed amount could not be recorded.",
  allowedSourceRequired: "A source is required with the figure.",
  allowedInvalid: "The allowed amount is a dollar figure above zero, such as 812.50.",

  // 3 Deductible
  planDeductible: "Plan deductible",
  appliesToCategory: "Applies to this category",
  applies: "applies",
  waivedFor: (cls: string) => `waived for ${cls}`,
  remainingBefore: "Remaining before this procedure",
  appliedToLine: "Applied to this line",
  remainingAfter: "Remaining after",

  // 4 Coverage share
  shareSentence: (category: string, pct: number) => `Your plan lists ${category} at ${pct}% of the allowed amount after the deductible.`,
  planShare: "Plan share",
  yourShare: "Your share",
  shareBar: (planPct: number, plan: string, you: string) => `Plan share ${planPct}% ${plan}; your share ${100 - planPct}% ${you}.`,

  // 5 Annual maximum
  planAnnualMax: "Plan annual maximum",
  unlimited: "Unlimited (no dollar maximum)",
  consumedByLine: "Consumed by this line",
  consumedNote: "The plan's payment for this line counts toward the maximum.",
  exemptNote: (cls: string) => `The document lists ${cls} as exempt from the annual maximum.`,
  beyondMax: "Beyond the maximum",
  withinMax: "within the remaining maximum",
  noMaxApplies: "no maximum applies",
  gaugeLabel: (before: string, after: string) => `Remaining annual maximum: ${before} before this procedure, ${after} after.`,
  gaugeBefore: "before",
  gaugeAfter: "after",

  // 6 Frequency
  frequencySentence: (n: number, clock: string) => `Your plan lists this service as covered ${n} per ${clock}.`,
  clockCalendar: "calendar year",
  clockInterval: (n: number) => `${n} months (one per interval)`,
  clockRolling: "rolling 12 months",
  clockPerTooth: (n: number) => `${n} months per tooth (shown as a rule; not enforced in the arithmetic)`,
  clockPerQuadrant: (n: number) => `${n} months per quadrant (shown as a rule; not enforced in the arithmetic)`,
  clockLifetime: "lifetime",
  serviceDates: "Service dates on your statement",
  noServiceDates: "None recorded on your statement.",

  // 7 Waiting period
  waitingUnknown: "The pages read do not state a waiting period for this service. The estimate is computed as if none applies; the flag below records this.",
  waitingNone: "This document states no waiting period for this service.",
  waitingMonths: (months: number, category: string) => `Your plan lists a ${months}-month waiting period for ${category}.`,
  coverageStart: "Coverage start",

  // 8 Alternate benefit
  alternateUnknown: "The pages read do not include an alternate-benefit clause for this service. Absence is not confirmed.",
  alternateSentence: (condition: string, basis: string) => `When ${condition}, the plan pays on the allowance for ${basis}.`,
  alternateNoConditions: "This document includes an alternate-benefit clause; the pages read do not say which services it names.",
  condMolar: "a crown is placed on a molar",
  condMandibularMolar: "a crown is placed on a lower molar",
  condPosterior: "a crown is placed on a back tooth",
  condAny: "this service is performed",
  condUpperSecondThird: "a crown is placed on an upper second or third molar, or a lower molar",
  condOther: (c: string) => `the condition "${c}" is met`,
  basisUnnamed: "the alternate service",
  notApplyTooth: (tooth: string) => `Does not apply to tooth ${tooth}.`,
  notApplyLine: "Does not apply to this line.",
  alternateBasis: "Basis change",
  alternateDifference: "Difference, your share",

  // 9 Exclusions
  excludedSentence: "This document lists this service under its exclusions.",
  notExcludedSentence: "The pages read list no exclusion naming this service. Absence is not confirmed.",
  relatedWording: "Related wording in the document (shown, not applied)",

  // 10 Final cost
  youPay: "You pay",
  estimatedPlanPayment: "Estimated plan payment",
  upperBoundWord: "(upper bound)",
  benefitYear: (y: number) => `benefit year ${y}`,
  notCoveredLine: "The plan pays nothing for this line; the full fee is your share.",
  pipelineLabel: (label: string, n: number, fee: string, youPay: string) => `Cost pipeline for ${label}: ${n} steps from dentist's fee ${fee} to you pay ${youPay}.`,
  pipelineUnresolved: (label: string) => `Cost pipeline for ${label}: the dentist's fee is known; the rest is waiting for information.`,
  ownerPatient: "your share",
  ownerPlan: "plan share",
  ownerNobody: "not owed by you",
  ownerBasis: "basis",
  ownerTotal: "total",
  fogNode: "Waiting for information",
  noChange: "no change",

  // 11 How was this calculated?
  equationsLabel: "Equation rows, one per step",
  calcFooter: "Every step above is a row the engine returned; nothing on this page is computed by the display.",
  fullTrail: "Every step in full",
  eqFee: "dentist's fee",
  eqAllowed: "allowed amount",
  eqBasis: "alternate basis",
  eqAfterDeductible: "after the deductible",
  eqPlanShare: "plan share",
  eqYourShare: "your share",
  eqPlanPays: "plan pays",
  eqYouPay: "you pay",
  eqFullFee: "the full fee is your share",
  reconcilesOnlyNote: "The reconciliation line is printed only when the display sum equals the engine's line totals.",

  // 12 Clause evidence
  clauseSection: (section: string) => `Where it sits: ${section}`,
  clauseOption: (option: string) => `The figure for this plan is read from the ${option} column.`,
  evidenceIntro: "Every clause behind this line, each with its document and page.",
  openInDocuments: "Open in Documents",
  noStoredPdf: "The document is not stored here; the official source is linked in Documents.",
  noClauses: "No clause of this document is attached to this line.",

  // visited / marginal
  visitedNote: (date: string) => `Figures as entered from the benefit statement dated ${date}. Nothing is recomputed; these figures enter no estimate.`,
  claimDate: "Date of service",
  planPaid: "Plan paid",
  youPaid: "You paid",
  deductibleApplied: "Deductible applied",
  marginalNotCovered: "Not covered · excluded by the plan",
  marginalSentence: "Mentioned at the consultation; not on the treatment plan. No estimate is calculated for it.",
  marginalCovered: "No fee or allowed amount is recorded, so no estimate is calculated.",
  deductibleApplies: "Deductible applies",
  planPaysPct: "Plan pays",

  // START
  planTitle: "Plan",
  planVersion: "Document version",
  fictionalRibbon: "Fictional demonstration plan",
  statementSource: "Benefit statement",
  remainingDeductible: "Remaining deductible",
  remainingMax: "Remaining annual maximum",
  networkStatus: "Network",
  drawnFrom: (n: number) => `${n} records feed this route; the START checkpoints list them on the Care timeline.`,
  benefitsFormPlaceholder: "Benefit statement form: provided by the plan view; it appears here once that module is present.",
  benefitsFormNote: "Remaining amounts are derived on the server: plan limit (document) minus what the statement reports (entered by you).",
  noBenefits: "No benefit statement figures are recorded for this plan.",

  // Harbor Light
  routeYouPay: "Estimated you pay for the route",
  routePlanPays: "Estimated plan payment for the route",
  island: "Island",
  status: "Status",
  statusEstimate: "estimate",
  statusNotCovered: "not covered",
  statusUnresolved: "waiting for information",
  statusPending: "no estimate yet",
  soundingsAfterRoute: "Soundings after the last island",
  deductibleLeft: "deductible left",
  maximumLeft: "maximum left",
  afterRouteStages: (n: number) => (n === 1 ? "1 care stage follows the route; its checkpoints are on the Care timeline." : `${n} care stages follow the route; their checkpoints are on the Care timeline.`),
  stageProgress: (title: string, done: number, total: number) => `${title} · ${done} of ${total} checkpoint${total === 1 ? "" : "s"} completed`,
  rangeOnly: (lo: string, hi: string) => `Between ${lo} and ${hi}.`,
  noAfterRoute: "No care stages follow the route.",
  orderNote: "Processing order",
  missingTitle: "This estimate is waiting for information",
} as const satisfies Record<string, string | ((...a: never[]) => string)>;
