/**
 * Copy namespace: DRAWER (procedure drawer, dollar pipeline, clause evidence, START and Harbor Light drawers).
 * Owner: web drawer + pipeline agent (spec §4.4, §4.5, §5.5). `lib/copy.ts` re-exports this file (the integrator swaps the
 * `DRAWER` export in copy/passage.ts for this one). Every string passes `python3 tools/advice_lint.py`: state what the documents say,
 * what the records say and what the arithmetic yields; never tell the user what to do; no em dashes; nothing recommends or ranks.
 */
export const DRAWER = {
  // shell
  region: "About this care",
  close: "Close",
  crumbs: (order: number, n: number, place: string) => `Island ${order} of ${n} · ${place}`,
  crumbsStart: (place: string) => `Start · ${place}`,
  // the Harbor Light island's place is "Harbor Light" itself (lib/islands.ts LIGHT_PLACE): never print it twice (slop-18)
  crumbsLight: (place: string) => (place === "Harbor Light" ? "End of the route" : `Harbor Light · ${place}`),
  crumbsVisited: (place: string) => `Done, says your insurance letter · ${place}`,
  crumbsMarginal: (place: string) => `Talked about at the visit · ${place}`,
  checkpointStrip: "Stops on this island, in order",
  checkpointName: (term: string, amount: string) => `${term}: ${amount}`,
  youPayLede: "You pay",
  planPaysLede: "insurance pays",
  planPaysRow: "Insurance pays",
  beforeIsland: "Before this island",
  calculatedShort: "calculated",
  waitingInfo: "We need more info",
  noAmount: "no amount",
  estimateUpdated: "Numbers updated",

  // section headings (spec §4.4; the checks look for these exact texts)
  sProcedure: "The care",
  sAllowance: "Price your plan agreed to",
  sDeductible: "Part you pay first",
  sShare: "Who pays what",
  sAnnualMax: "Most insurance pays a year",
  sFrequency: "How often insurance pays",
  sWaiting: "Wait before insurance helps",
  sAlternate: "Insurance pays for the cheaper fix",
  sExclusions: "Things insurance won't pay for",
  sFinalCost: "You pay and insurance pays",
  sCalculation: "How we did the math",
  calculated: "We did the math with the steps below",
  /** The same label away from a step list (map, overview, Answers log, stage panel): the figure is engine arithmetic over cited clauses. */
  calculatedCited: "We did the math with the plan rules",
  calcFromRoute: "We did the math with your letter and the islands so far",
  remainingBeforeLater: "What was left after the island before this one.",
  harborTableNote: "We did the math for each island. Tap a number to see the rule.",
  sEvidence: "The plan's words",
  sPlan: "Plan",
  sRecords: "Your papers",
  sBenefitsForm: "Numbers from your insurance letter",
  sTotals: "All the care added up",
  sPerIsland: "Each island",
  sAfterRoute: "After all this care",
  sClaim: "Numbers from your insurance letter",
  sRule: "Plan rule",
  expand: "Open",
  collapse: "Close",

  // 1 Procedure
  identifier: "Name",
  asWritten: "just as your letter wrote it",
  noCode: "The papers show no code",
  dates: "Dates",
  dateAppointment: "appointment",
  datePrep: "first visit, planned",
  dateCompletion: "last visit, planned",
  dentistFee: "Dentist's price",
  quantity: (q: number) => `how many: ${q}`,
  planCategory: "Kind of care",
  recordSource: "Where it's from",
  statusWord: (s: string) => s.replace(/_/g, " "),
  toothWord: (t: string) => `tooth ${t}`,

  // 2 Allowance
  allowedAmount: "Price your plan agreed to",
  network: "On your plan's list?",
  inNetwork: "dentist on your plan's list",
  outNetwork: "dentist outside your plan's list",
  networkNotProvided: "We don't know if this dentist is on your plan's list. The price changes with that, so the number stays open.",
  allowedMissingTitle: "What this number needs",
  allowedInputLabel: "Price your plan agreed to, in dollars",
  allowedSourceLabel: "Where this price comes from (which paper, which day)",
  allowedRecord: "Use this price",
  allowedRecorded: "Got it. We did the math again.",
  allowedFailed: "We couldn't keep this price.",
  allowedSourceRequired: "This price needs a paper it came from.",
  allowedInvalid: "The price is dollars more than zero, like 812.50.",

  // 3 Deductible
  planDeductible: "Part you pay first",
  appliesToCategory: "Counts for this kind of care",
  applies: "yes",
  waivedFor: (cls: string) => `not for ${cls}`,
  remainingBefore: "Left before this care",
  appliedToLine: "Used on this care",
  remainingAfter: "Left after",

  // 4 Coverage share
  shareSentence: (category: string, pct: number) => `For ${category}, insurance pays ${pct}%. You pay the rest.`,
  planShare: "Insurance pays",
  yourShare: "You pay",
  shareBar: (planPct: number, plan: string, you: string) => `Insurance pays ${planPct}% ${plan}; you pay ${100 - planPct}% ${you}.`,

  // 5 Annual maximum
  planAnnualMax: "Most insurance pays a year",
  unlimited: "No limit",
  consumedByLine: "Used by this care",
  consumedNote: "What insurance pays here counts toward the yearly limit.",
  exemptNote: (cls: string) => `The papers say ${cls} does not count toward the yearly limit.`,
  beyondMax: "Over the yearly limit",
  withinMax: "fits under the yearly limit",
  noMaxApplies: "no limit",
  gaugeLabel: (before: string, after: string) => `Yearly limit left: ${before} before this care, ${after} after.`,
  gaugeBefore: "before",
  gaugeAfter: "after",

  // 6 Frequency
  frequencySentence: (n: number, clock: string) => `Insurance pays for this ${n} time(s) per ${clock}.`,
  clockCalendar: "calendar year",
  clockInterval: (n: number) => `${n} months`,
  clockRolling: "12 months in a row",
  clockPerTooth: (n: number) => `${n} months per tooth (shown, not used in the math)`,
  clockPerQuadrant: (n: number) => `${n} months per part of the mouth (shown, not used in the math)`,
  clockLifetime: "whole life",
  serviceDates: "Visit dates on your insurance letter",
  noServiceDates: "Your letter shows none.",

  // 7 Waiting period
  waitingUnknown: "The papers don't say how long before insurance helps. We did the math as if there is no wait.",
  waitingNone: "The papers say there is no wait for this.",
  waitingMonths: (months: number, category: string) => `Insurance helps with ${category} after ${months} months.`,
  coverageStart: "Plan started",

  // 8 Alternate benefit
  alternateUnknown: "The papers we read don't say insurance pays for a cheaper fix here.",
  alternateSentence: (condition: string, basis: string) => `When ${condition}, insurance pays for ${basis} instead.`,
  alternateNoConditions: "The papers say insurance can pay for a cheaper fix. They don't say for what.",
  condMolar: "a crown is placed on a molar",
  condMandibularMolar: "a crown is placed on a lower molar",
  condPosterior: "a crown is placed on a back tooth",
  condAny: "this service is performed",
  condUpperSecondThird: "a crown is placed on an upper second or third molar, or a lower molar",
  condOther: (c: string) => `the condition "${c}" is met`,
  basisUnnamed: "the cheaper fix",
  notApplyTooth: (tooth: string) => `Not for tooth ${tooth}.`,
  notApplyLine: "Not for this care.",
  alternateBasis: "Cheaper fix price",
  alternateDifference: "The difference, you pay",

  // 9 Exclusions
  excludedSentence: "The papers say insurance won't pay for this.",
  notExcludedSentence: "The papers we read don't say insurance won't pay for this.",
  relatedWording: "Other words in the papers (shown, not used)",

  // 10 Final cost
  youPay: "You pay",
  estimatedPlanPayment: "Insurance pays",
  upperBoundWord: "(or less)",
  benefitYear: (y: number) => `plan year ${y}`,
  notCoveredLine: "Insurance pays nothing here. You pay the whole price.",
  pipelineLabel: (label: string, n: number, fee: string, youPay: string) => `Money steps for ${label}: ${n} steps from the dentist's price ${fee} to you pay ${youPay}.`,
  pipelineUnresolved: (label: string) => `Money steps for ${label}: we know the dentist's price. We need more info for the rest.`,
  ownerPatient: "you pay",
  ownerPlan: "insurance pays",
  ownerNobody: "you don't pay this",
  ownerBasis: "starting price",
  ownerTotal: "total",
  fogNode: "We need more info",
  noChange: "same",

  // 11 How was this calculated?
  equationsLabel: "Math, one line per step",
  calcFooter: "Every step comes from our math tool. The screen adds nothing.",
  fullTrail: "Every step",
  eqFee: "dentist's price",
  eqAllowed: "price your plan agreed to",
  eqBasis: "cheaper fix price",
  eqAfterDeductible: "after the part you pay first",
  eqPlanShare: "insurance part",
  eqYourShare: "your part",
  eqPlanPays: "insurance pays",
  eqYouPay: "you pay",
  eqFullFee: "you pay the whole price",
  reconcilesOnlyNote: "The 'it adds up' line shows only when the numbers match.",

  // 12 Clause evidence
  clauseSection: (section: string) => `Where it is: ${section}`,
  clauseOption: (option: string) => `This number comes from the ${option} column.`,
  evidenceIntro: "Every plan rule behind this number, with its page.",
  openInDocuments: "See it in your papers",
  noStoredPdf: "The papers aren't kept here. The real ones are linked in Documents.",
  noClauses: "No plan rule is tied to this number.",

  // visited / marginal
  visitedNote: (date: string) => `Numbers typed from your insurance letter from ${date}. We don't use them in new math.`,
  claimDate: "Visit date",
  planPaid: "Insurance paid",
  youPaid: "You paid",
  deductibleApplied: "Pay-first part used",
  marginalNotCovered: "Insurance won't pay for this",
  marginalSentence: "Talked about at the visit, but not in the dentist's plan. No numbers for it.",
  marginalCovered: "We have no price for this, so there are no numbers.",
  deductibleApplies: "Pay-first part counts",
  planPaysPct: "Insurance pays",

  // START
  planTitle: "Plan",
  planVersion: "Paper version",
  fictionalRibbon: "Pretend plan for showing how it works",
  statementSource: "Insurance letter",
  remainingDeductible: "Pay-first part left",
  remainingMax: "Yearly limit left",
  networkStatus: "On your plan's list?",
  drawnFrom: (n: number) => `${n} papers make this map. The START stops list them.`,
  benefitsFormPlaceholder: "The insurance letter form shows up here when it is ready.",
  benefitsFormNote: "Left = the plan's limit minus what your letter says was used.",
  noBenefits: "No numbers from an insurance letter yet.",

  // Harbor Light
  routeYouPay: "You pay, all care added up",
  routePlanPays: "Insurance pays, all care added up",
  island: "Island",
  status: "Status",
  statusEstimate: "estimate",
  statusNotCovered: "insurance won't pay",
  statusUnresolved: "need more info",
  statusPending: "no numbers yet",
  soundingsAfterRoute: "What is left after the last island",
  deductibleLeft: "pay-first part left",
  maximumLeft: "yearly limit left",
  afterRouteStages: (n: number) => (n === 1 ? "1 more care step comes after this." : `${n} more care steps come after this.`),
  stageProgress: (title: string, done: number, total: number) => `${title} · ${done} of ${total} stop${total === 1 ? "" : "s"} done`,
  rangeOnly: (lo: string, hi: string) => `Somewhere from ${lo} to ${hi}.`,
  noAfterRoute: "No more care steps after this.",
  orderNote: "Math order",
  missingTitle: "We need more info for this number",
} as const satisfies Record<string, string | ((...a: never[]) => string)>;
