/**
 * Copy namespace: PASSAGE, DRAWER, COMPASS — owner: web foundation + map agent (spec §13.1).
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`:
 * state what the documents say, what the records say and what the arithmetic yields; never tell the user what to do; no em dashes.
 */
export const PASSAGE = {
  // ---- vocabulary used inside accessible names and log rows ----
  inNetwork: "in-network",
  outOfNetwork: "out-of-network",
  networkNotProvided: "network not provided",
  tooth: "tooth",
  plan: "plan",
  you: "you",
  youPay: "you pay",
  planPaid: "plan paid",
  procedure: "procedure",
  step: "step",
  rule: "rule",
  cited: "cited",
  notStated: "not stated",
  fictional: "fictional",
  clause: "clause",
  page: "page",
  amountOut: "amount out",
  noChange: "no change",
  notOwedByYou: "not owed by you",
  notCoveredLower: "not covered",
  waitingLower: "waiting for information",
  noEstimateCalculated: "no estimate calculated",
  upperBoundParen: "(upper bound)",
  // ---- islands ----
  startTitle: "Start",
  lightTitle: "Harbor Light",
  startLabel: (code: string, network: string) => `Start · ${code} · ${network}`,
  lightLabel: (amount: string) => `Harbor Light · ${amount}`,
  visitedStamp: "visited",
  moreVisited: (k: number) => `+${k} more`,
  earlierVisits: (n: number) => `Earlier visits (${n})`,
  checkpointsCount: (k: number) => `${k} checkpoints`,
  notices: (n: number) => `${n} notice${n === 1 ? "" : "s"}`,
  lineMismatch: "Could not match this estimate line to a record; no amount is attributed to it.",
  feeExplanation: "What the dentist charges, as written on the estimate.",
  planPaidNotProvided: "amount paid by the plan not provided",
  notCoveredExcluded: "Not covered · excluded by the plan",
  marginalClosed: "Mentioned at the consultation; not on the treatment plan. No estimate is calculated for it.",
  marginalOpen: "No fee or allowed amount is recorded, so no estimate is calculated.",
  waiting: "Waiting for information",
  networkUnknown: "Network status is not provided. In-network and out-of-network amounts differ; the estimate stays unresolved until it is entered.",
  visitedNote: (date: string) => `Figures as entered from the benefit statement dated ${date}.`,
  // ---- answers log (§2.4) ----
  whereYouAre: "Where you are",
  onTheRoute: "On the route",
  estimatedYouPay: "Estimated you pay",
  rulesApplied: "Rules applied",
  from: "From",
  noStages: "No care stages recorded",
  noPlanned: "No planned procedures",
  completedOnStatement: "completed on your statement",
  recalculating: "Recalculating…",
  noEstimate: "No estimate yet",
  waitingInputs: (n: number) => `Waiting for information (${n} input${n === 1 ? "" : "s"})`,
  noPlan: "No plan is selected",
  // ---- map surface ----
  mapLabel: "Passage map",
  skipToRoute: "Skip to the route",
  islandsGroup: "Procedure islands",
  checkpointsOf: (title: string) => `Checkpoints on ${title}`,
  legendCheckpoint: "Checkpoint",
  legendPassed: "Pass-through, no change",
  legendClosed: "Not covered",
  legendVisited: "Completed on your statement",
  legendFog: "Waiting for information",
  legendMarginal: "Mentioned at the consultation",
  denseNote: "Dense route: checkpoint markers are drawn for the selected island only; every checkpoint stays listed in the Overview list.",
  collapsedNote: "Markers with no change are drawn as one hollow marker; each is still listed in the Overview list.",
  openWater: "open water",
  noPlannedBody: "No planned procedures are recorded. The route is drawn once a treatment item is added.",
  noPlanSelected: "No plan is selected. The route is drawn from a plan document and your records.",
  soundingsDeductible: "deductible left",
  soundingsMax: "maximum left",
  noMaximum: "no maximum applies",
  soundingsAria: (deductible: string, maximum: string) => `Soundings after this island: deductible left ${deductible}, maximum left ${maximum}`,
  soundingsBefore: "Before the route",
  careTimeline: "Care timeline",
  whatCompletionMeans: "What completion means",
  showOnChart: "Show on the chart",
  mapView: "Map view",
  jumpTo: "Jump to a procedure",
  estimateUpdated: "Estimate updated",
  youAreHere: "You are here",
  afterRoute: "After the route",
  passed: (names: string) => `Passed with no change: ${names}`,
  legOf: (from: string, to: string) => `Leg from ${from} to ${to}`,
  // ---- overview list (§9.3) ----
  routeTable: "Route from the dentist's fee to you pay",
  routeTableSummary: (n: number, plan: string, total: string) => `Route from the dentist's fee to you pay for ${n} procedure${n === 1 ? "" : "s"} under ${plan}; estimated you pay ${total}.`,
  visitedTable: "Completed on your statement",
  marginalTable: "Mentioned at the consultation",
  colProcedure: "Procedure",
  colTooth: "Tooth",
  colStatus: "Status",
  colFee: "Dentist's fee",
  colAllowed: "Allowed amount",
  colYouPay: "You pay",
  colPlanPays: "Plan pays",
  colCheckpoints: "Checkpoints",
  colFlags: "Notices",
  colSoundings: "Soundings after",
  colTerm: "Term",
  colAmountIn: "Amount in",
  colChange: "Change",
  colAmountOut: "Amount out",
  colOwner: "Owner",
  colClause: "Clause",
  colDate: "Date",
  colPlanPaid: "Plan paid",
  colPatientPaid: "Patient paid",
  colRule: "Coverage rule",
  stepsOf: (k: number) => `${k} step${k === 1 ? "" : "s"}`,
  showCheckpoints: "Checkpoints for this procedure",
  ownerPatient: "your share",
  ownerPlan: "plan share",
  ownerNobody: "not owed by you",
  ownerBasis: "basis",
  ownerInfo: "information",
  cancelledNote: (n: number) => `${n} cancelled item${n === 1 ? "" : "s"} not drawn.`,
} as const satisfies Record<string, string | ((...a: never[]) => string)>;
