/**
 * Copy namespace: PASSAGE, DRAWER, COMPASS — owner: web foundation + map agent (spec §13.1).
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`:
 * state what the documents say, what the records say and what the arithmetic yields; never tell the user what to do; no em dashes.
 */
export const PASSAGE = {
  // ---- vocabulary used inside accessible names and log rows ----
  inNetwork: "on your plan's list",
  outOfNetwork: "outside your plan's list",
  networkNotProvided: "plan's list not known",
  tooth: "tooth",
  plan: "insurance",
  you: "you",
  youPay: "you pay",
  insurancePays: "insurance pays",
  planPaid: "insurance paid",
  procedure: "care item",
  step: "step",
  rule: "rule",
  cited: "from the papers",
  notStated: "not in the papers",
  fictional: "pretend",
  clause: "rule",
  page: "page",
  amountOut: "after this step",
  noChange: "same",
  notOwedByYou: "you don't pay this",
  notCoveredLower: "insurance won't pay",
  waitingLower: "need more info",
  noEstimateCalculated: "no numbers yet",
  upperBoundParen: "(or less)",
  // ---- islands ----
  startTitle: "Start",
  lightTitle: "Harbor Light",
  startLabel: (code: string, network: string) => `Start · ${code} · ${network}`,
  lightLabel: (amount: string) => `Harbor Light · ${amount}`,
  visitedStamp: "done",
  moreVisited: (k: number) => `+${k} more`,
  earlierVisits: (n: number) => `Visits before (${n})`,
  moreMentioned: (k: number) => `+${k} more talked about`,
  mentionedCount: (n: number) => `Talked about at the visit (${n})`,
  stripPage: (from: number, to: number) => `Care ${from} to ${to}`,
  stripPages: "Pages of the care list",
  checkpointsCount: (k: number) => `${k} stops`,
  notices: (n: number) => `${n} note${n === 1 ? "" : "s"}`,
  lineMismatch: "We couldn't match this line to your papers. It has no number.",
  feeExplanation: "What the dentist charges, just as the letter says.",
  planPaidNotProvided: "what insurance paid is missing",
  notCoveredExcluded: "Insurance won't pay for this",
  marginalClosed: "Talked about at the visit, but not in the dentist's plan. No numbers for it.",
  marginalOpen: "We have no price for this, so there are no numbers.",
  waiting: "We need more info",
  networkUnknown: "We don't know if this dentist is on your plan's list. The price changes with that, so the number stays open.",
  visitedNote: (date: string) => `Numbers typed from your insurance letter from ${date}.`,
  // ---- answers log (§2.4) ----
  whereYouAre: "Where you are",
  onTheRoute: "Your care",
  estimatedYouPay: "You pay",
  rulesApplied: "Plan rules used",
  from: "From",
  noStages: "No care steps yet",
  noPlanned: "No care planned yet",
  completedOnStatement: "done, says your insurance letter",
  recalculating: "Doing the math…",
  noEstimate: "No numbers yet",
  waitingInputs: (n: number) => `We need more info (${n} thing${n === 1 ? "" : "s"})`,
  noPlan: "No plan picked",
  // ---- map surface ----
  mapLabel: "Care map",
  skipToRoute: "Go to your care",
  islandsGroup: "Care islands",
  checkpointsOf: (title: string) => `Stops on ${title}`,
  legendCheckpoint: "Stop",
  legendPassed: "Nothing changes here",
  legendClosed: "Insurance won't pay",
  legendVisited: "Done, says your insurance letter",
  legendFog: "We need more info",
  legendMarginal: "Talked about at the visit",
  denseNote: "Lots of stops: we draw them for one island at a time. The List shows them all.",
  collapsedNote: "Stops where nothing changes share one empty dot. The List shows each one.",
  openWater: "open water",
  noPlannedBody: "No care planned yet. The map shows up when care is added.",
  noPlanSelected: "No plan picked. The map comes from your plan papers.",
  soundingsDeductible: "pay-first part left",
  soundingsMax: "yearly limit left",
  noMaximum: "no limit",
  soundingsAria: (deductible: string, maximum: string) => `Left after this island: pay-first part ${deductible}, yearly limit ${maximum}`,
  soundingsBefore: "Before this care",
  careTimeline: "Care timeline",
  whatCompletionMeans: "What done means",
  showOnChart: "See it on the map",
  mapView: "Map",
  jumpTo: "Go to a care item",
  estimateUpdated: "Numbers updated",
  youAreHere: "You are here",
  afterRoute: "After this care",
  passed: (names: string) => `Nothing changed at: ${names}`,
  legOf: (from: string, to: string) => `From ${from} to ${to}`,
  // ---- overview list (§9.3) ----
  routeTable: "From the dentist's price to what you pay",
  routeTableSummary: (n: number, plan: string, total: string) => `From the dentist's price to what you pay, for ${n} care item${n === 1 ? "" : "s"} on ${plan}. You pay ${total}.`,
  visitedTable: "Done, says your insurance letter",
  marginalTable: "Talked about at the visit",
  colProcedure: "Care",
  colTooth: "Tooth",
  colStatus: "Status",
  colFee: "Dentist's price",
  colAllowed: "Price your plan agreed to",
  colYouPay: "You pay",
  colPlanPays: "Insurance pays",
  colCheckpoints: "Stops",
  colFlags: "Notes",
  colSoundings: "Left after",
  colTerm: "Step",
  colAmountIn: "Before",
  colChange: "Change",
  colAmountOut: "After",
  colOwner: "Who pays",
  colClause: "Rule",
  colDate: "Date",
  colPlanPaid: "Insurance paid",
  colPatientPaid: "You paid",
  colRule: "Plan rule",
  stepsOf: (k: number) => `${k} step${k === 1 ? "" : "s"}`,
  showCheckpoints: "Stops for this care",
  ownerPatient: "you pay",
  ownerPlan: "insurance pays",
  ownerNobody: "you don't pay this",
  ownerBasis: "starting price",
  ownerInfo: "just info",
  cancelledNote: (n: number) => `${n} cancelled item${n === 1 ? "" : "s"} not shown.`,
  uploadedPlan: "your plan papers",
  currentEstimate: "Your numbers now",
  whatIfTitle: "What if (a guess)",
  withHypothetical: "(with a guess you typed)",
  whatIfNetwork: "Is the dentist on your plan's list?",
  whatIfAsRecorded: (word: string) => `As your papers say (${word})`,
  whatIfIn: "On the list (a guess)",
  whatIfOut: "Not on the list (a guess)",
  whatIfActive: "These numbers use a guess you typed. Your papers stay the same.",
  toothLabel: "Tooth, as your dentist's plan says",
  toothSave: "Use this tooth",
  toothSaved: "Got it. We did the math again.",
  toothFailed: "We couldn't keep the tooth. Nothing changed.",
  journeysSummary: (n: number) => `Journeys (${n})`,
  calculatedAria: "we did the math with the plan rules",
  legendAmounts: "We did the math for You pay and Insurance pays. Each step shows where it came from.",
  visitedFigures: "What insurance paid, as you typed it from your letter.",
  tableScrolls: "Slide the table sideways to see more.",
  tableRegion: (name: string) => `${name} (table, slides sideways)`,
  // ---- the phone journey (mobile-only app): compact header over the painting, the rest below the map ----
  journeyDetails: "About this care",
  journeyTitleLabel: "Care",
  overviewHeading: "List",
  overviewNote: "The same care, shown as tables.",
} as const satisfies Record<string, string | ((...a: never[]) => string)>;
