/**
 * Copy namespace: PLAN (My plan view, plan selector, benefit statement form, treatment plan importer, Compare, Documents); owner: web foundation + map agent.
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`; no em dashes.
 * Voice: what the documents say, what your records say, what the arithmetic yields. Nothing here tells the reader what to do.
 */
export const PLAN = {
  // ---- plan selector (spec §7.2; addendum B1/B2: a single `label.plan-pick select` of plan codes stays as the fast path) ----
  sourceLabel: "Plan source",
  modePreset: "Preset plan",
  modeUpload: "Your uploaded document",
  carrier: "Carrier",
  planName: "Plan name",
  planYear: "Plan year",
  planCode: "Plan",
  publicGroup: "Public plan documents",
  fictionalGroup: "Fictional demonstration plans",
  uploadsGroup: "Your uploaded documents",
  uploadedPlan: "Published document",
  noUploads: "No uploaded plan document has been published yet. A document added here is read, redacted, reviewed by you and then published as its own plan version.",
  uploadsLoading: "Reading your published documents…",
  uploadVersion: (label: string, date: string) => `${label}, published ${date}`,
  uploadedRibbon: (label: string) => `Uploaded plan, version ${label}`,
  singleYear: (year: string) => `${year} (the only plan year in this document)`,
  noPlan: "No plan is selected. The route is drawn from a plan document and your records.",
  landmarkHint: "Each landmark opens one part of the plan. Familiar terms first; the place names are only the map's.",
  // ---- live region (one per surface) ----
  estimateUpdated: "Estimate updated",
  recalculating: "Recalculating…",
  benefitsUpdated: "Benefit statement figures recorded",
  // ---- states (spec §4.7) ----
  noProcedures: "No planned procedures are recorded. The cost breakdown is drawn once a treatment item is added.",
  waitingForInfo: "Waiting for information",
  unlimited: "Unlimited (no dollar maximum)",
  notProvided: "Not provided",
  // ---- benefit statement form (spec §4.5) ----
  bsTitle: "Benefit statement figures",
  bsNote: "Remaining amounts are derived on the server: plan limit (document) minus what the statement reports (entered by you).",
  bsEveryFigureUser: "Every figure entered here is labeled as entered by you, with the statement date.",
  bsDeductibleMet: "Deductible met so far this benefit year (dollars)",
  bsBenefitsUsed: "Paid by the plan so far this benefit year (dollars)",
  bsDeductibleMetOut: "Out-of-network deductible met so far (dollars)",
  bsBenefitsUsedOut: "Paid by the plan out-of-network so far (dollars)",
  bsCoverageStart: "Coverage start date",
  bsNetwork: "Your dentist's network status",
  bsNetworkIn: "In-network",
  bsNetworkOut: "Out-of-network",
  bsNetworkUnknown: "Not provided",
  bsSourceLabel: "Statement (label, required)",
  bsSourcePlaceholder: "MetLife benefit statement dated 2026-09-20",
  bsSourceDate: "Statement date (required)",
  bsSubmit: "Record these figures",
  bsSaved: "Figures recorded. The remaining amounts below are derived from them.",
  bsError: "The figures could not be recorded.",
  bsLabelRequired: "A statement label is required.",
  bsDateRequired: "A statement date is required.",
  bsDerivationTitle: "How the remaining amounts were derived",
  bsNoneEntered: "No benefit statement figures are entered for this plan.",
  bsOpen: "Enter benefit statement figures",
  bsSeparateOut: "This document states separate out-of-network limits; their figures are tracked separately.",
  // ---- add a procedure (spec §4.5) ----
  addTitle: "Add a procedure",
  addIntro: "A treatment item from your dentist's estimate. The procedure is matched to one of 16 fixed identifiers; the name as written stays on the island.",
  addProcedure: "Procedure (one of 16 fixed identifiers)",
  addProcedureName: "Name as written on the estimate (optional)",
  addTooth: "Tooth or area",
  addQuantity: "Quantity",
  addFee: "Dentist's fee (dollars)",
  addAllowed: "Allowed amount (dollars, optional)",
  addAllowedSource: "Where the allowed amount comes from",
  addAllowedSourceNote: "Required when an allowed amount is given, for example a pre-treatment estimate response with its date.",
  addNetwork: "Network",
  addPlannedPrep: "Planned preparation date",
  addPlannedCompletion: "Planned completion date",
  addAppointment: "Appointment date",
  addStatus: "Status",
  statusPlanned: "Planned",
  statusScheduled: "Scheduled",
  statusMentioned: "Mentioned at a consultation",
  addSource: "Source (required)",
  addSourcePlaceholder: "treatment plan 2026-09-24 (typed)",
  addCode: "Procedure code as written (optional)",
  addSubmit: "Add this procedure",
  addAdded: (name: string) => `${name} was added to your records. The estimate is recalculating.`,
  addError: "The procedure could not be added.",
  addFeeRequired: "A dentist's fee is required.",
  addSourceRequired: "A source is required.",
  addAllowedSourceRequired: "An allowed amount needs its source.",
  addCategoryHint: (hint: string) => `class hint: ${hint}`,
  amountOrEmpty: "An amount in dollars, or empty when not provided.",
  procedureRequired: "A procedure is required.",
  // ---- compare (CLAUDE.md rule 6) ----
  cmpTitle: "Side by side",
  cmpPicker: (i: number) => `Plan ${i}`,
  cmpNone: "none",
  cmpProcedures: (list: string) => `Procedures compared: ${list}.`,
  cmpNoneRecorded: "none recorded as planned",
  cmpUsageFor: (codes: string) => `Usage figures are entered for: ${codes}. Other columns show what is not provided.`,
  cmpNoPlanned: "No planned procedures to compare. A treatment item on My journey or My plan starts the comparison.",
  cmpLedgers: "Same estimate, each plan",
  cmpLedgerOf: (title: string) => `${title}: ledger`,
  cmpTopic: "Topic",
  cmpEligibility: "Eligibility",
  cmpOpenClause: (topic: string, plan: string) => `${topic} for ${plan}: open the clause behind this cell`,
  cmpNoClause: "No clause is cited for this cell; the value is what the document or your records provide.",
  cmpClauseFrom: (doc: string, page: string) => `${doc}, ${page}`,
  cmpPremium: "Premium (employee only, monthly)",
  cmpUpperBound: "(upper bound)",
  cmpUnresolvedFor: "Unresolved. Not provided for this plan:",
  cmpClose: "Close clause",
  // ---- documents ----
  docsPlan: "Plan documents",
  docsMine: "Your documents",
  docsNoPrivate: "No private documents are stored. Plan documents you add, typed estimates and benefit statements appear here with their extraction status.",
  docsUncertain: "Uncertain extractions are listed as needing confirmation; nothing uncertain enters a calculation until confirmed.",
  docsIgnoredTitle: "Text in the document that was not used as a rule",
  docsUnmatchedTitle: "Wording that matched none of the 16 procedure identifiers",
  docsUploadedPdf: "This PDF is stored in your own space and read only through an owner-checked request.",
  docsNotStoredPdf: "The PDF is not stored in this build (binary downloads from this host were blocked); clauses below show the exact quote with its page reference, and the link opens the official document.",
  docsAccessLimits: (n: number) => `Access limits recorded for this document (${n})`,
  docsReuse: "Reuse terms:",
  docsRetrieved: "retrieved",
  docsDated: "dated",
  docsPages: "pages",
  docsFilter: "Filter clauses",
  docsFilterPlaceholder: "deductible, crown, page…",
  docsPageReview: "page attribution needs review",
  docsExported: "A copy of your records was downloaded.",
  docsDeleted: (what: string) => `Deleted: ${what}.`,
  docsNothingStored: "nothing stored",
  docsNeedsConfirmation: "needs your confirmation:",
  docsRedactionRemoved: "Redaction preview removed:",
  docsNothing: "nothing",
  docsVersions: (labels: string) => `Published versions: ${labels}`,
} as const satisfies Record<string, string | ((...a: never[]) => string)>;
