/**
 * Copy namespace: PLAN (My plan view, plan selector, benefit statement form, treatment plan importer, Compare, Documents); owner: web foundation + map agent.
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`; no em dashes.
 * Voice: what the documents say, what your records say, what the arithmetic yields. Nothing here tells the reader what to do.
 */
export const PLAN = {
  viewTitle: "My plan",
  // engine totals: arithmetic over steps that each carry their own stitch or badge (CLAUDE.md rule 2; orchestrator note 1)
  calculatedFromSteps: "We did the math with the steps below. Each step shows where it came from.",
  calculatedShort: "calculated",
  // ---- plan selector (spec §7.2; addendum B1/B2: a single `label.plan-pick select` of plan codes stays as the fast path) ----
  sourceLabel: "Where the plan comes from",
  modePreset: "Ready-made plan",
  modeUpload: "Your plan papers",
  carrier: "Insurance company",
  planName: "Plan name",
  planYear: "Plan year",
  planCode: "Plan",
  publicGroup: "Real plans anyone can see",
  fictionalGroup: "Pretend plans",
  uploadsGroup: "Your plan papers",
  uploadedPlan: "Your plan papers",
  noUploads: "No plan papers added yet. Papers added here get read, cleaned of private info, and checked by you.",
  uploadsLoading: "Reading your plan papers…",
  uploadVersion: (label: string, date: string) => `${label}, added ${date}`,
  uploadedRibbon: (label: string) => `Your plan papers, version ${label}`,
  singleYear: (year: string) => `${year} (the only year in these papers)`,
  noPlan: "No plan picked. The map comes from your plan papers.",
  landmarkHint: "Each place on the map shows one part of your plan.",
  // ---- live region (one per surface) ----
  estimateUpdated: "Numbers updated",
  recalculating: "Doing the math…",
  benefitsUpdated: "Insurance letter numbers kept",
  // ---- states (spec §4.7) ----
  noProcedures: "No care planned yet. Your numbers show up when care is added.",
  waitingForInfo: "We need more info",
  unlimited: "No limit",
  unlimitedShort: "No limit",
  notProvided: "Missing",
  // ---- benefit statement form (spec §4.5) ----
  bsTitle: "Numbers from your insurance letter",
  bsNote: "Left = the plan's limit minus what your letter says was used.",
  bsEveryFigureUser: "Every number here is marked 'You typed this', with the letter's date.",
  bsDeductibleMet: "Part you pay first, paid so far this year (dollars)",
  bsBenefitsUsed: "Paid by insurance so far this year (dollars)",
  bsDeductibleMetOut: "Part you pay first, dentists outside the list, paid so far (dollars)",
  bsBenefitsUsedOut: "Paid by insurance for dentists outside the list so far (dollars)",
  bsCoverageStart: "Day your plan started",
  bsNetwork: "Is your dentist on your plan's list?",
  bsNetworkIn: "Yes, on the list",
  bsNetworkOut: "No, outside the list",
  bsNetworkUnknown: "Not known",
  bsSourceLabel: "Which letter (needed)",
  bsSourcePlaceholder: "MetLife benefit statement dated 2026-09-20",
  bsSourceDate: "Letter date (needed)",
  bsSubmit: "Use these numbers",
  bsSaved: "Got it. The numbers left below come from these.",
  bsError: "We couldn't keep these numbers.",
  bsLabelRequired: "The letter needs a name.",
  bsDateRequired: "The letter needs a date.",
  bsDerivationTitle: "How we did the math for what is left",
  bsNoneEntered: "No numbers from an insurance letter yet.",
  bsOpen: "Type numbers from your insurance letter",
  bsSeparateOut: "These papers have other limits for dentists outside the list. We keep those apart.",
  // ---- add a procedure (spec §4.5) ----
  addTitle: "Add care",
  addSummaryNote: "Type it, paste it, or use a photo",
  addIntro: "Care from your dentist's price letter. We match it to one of 16 kinds of care.",
  addProcedure: "Kind of care (one of 16)",
  addProcedureName: "Name on the letter (if you want)",
  addTooth: "Tooth or area",
  addQuantity: "How many",
  addFee: "Dentist's price (dollars)",
  addAllowed: "Price your plan agreed to (dollars, if you know it)",
  addAllowedSource: "Where that price comes from",
  addAllowedSourceNote: "Needed with that price, like an insurance letter and its date.",
  addNetwork: "On your plan's list?",
  addPlannedPrep: "First visit date",
  addPlannedCompletion: "Last visit date",
  addAppointment: "Visit date",
  addStatus: "Status",
  statusPlanned: "Planned",
  statusScheduled: "Scheduled",
  statusMentioned: "Talked about at a visit",
  addSource: "Where it's from (needed)",
  addSourcePlaceholder: "treatment plan 2026-09-24 (typed)",
  addCode: "Code on the letter (if you want)",
  addSubmit: "Add this care",
  addAdded: (name: string) => `${name} was added. We are doing the math.`,
  addError: "We couldn't add this care.",
  addFeeRequired: "The dentist's price is needed.",
  addSourceRequired: "Where it's from is needed.",
  addAllowedSourceRequired: "That price needs where it's from.",
  addCategoryHint: (hint: string) => `kind: ${hint}`,
  amountOrEmpty: "Dollars, or leave it empty.",
  procedureRequired: "A kind of care is needed.",
  // ---- read a treatment plan (addendum D.5a; api/app/treatment_reader.py) ----
  readTitle: "Read your dentist's price letter",
  readIntro: "Paste the text of your dentist's estimate, or add a photo or PDF of it. Personal details are removed on this device from pasted text and from a PDF's text layer before anything is sent; a photo or a scanned page cannot be redacted and reaches the model as it is. Each line is matched to one of the 16 procedure identifiers, and nothing is added until you confirm it.",
  readRemovedOnDevice: "Found and removed on this device before the text was sent.",
  readRemovedOnDevicePdf: "The PDF's text was read on this device; these were removed before the text was sent.",
  readModeDemo: "Demo mode: only the two stored fictional estimates are read",
  readModeLive: (model: string) => `Live mode: read by ${model}`,
  readPasteLabel: "Estimate text",
  readPastePlaceholder: "Tooth   Code    Procedure    Fee",
  readSamplesLabel: "Sample text",
  readSampleButton: (label: string) => label,
  readRun: "Read these lines",
  readTextRequired: "There is no text to read yet.",
  readOr: "or",
  readFileTitle: "Photo or PDF of the estimate",
  readFileHint: "Drop a photo or PDF here",
  readFileChoose: "Choose a file",
  readFileCancel: "Cancel",
  readFileLimits: (max: string) => `PNG, JPEG, WebP or PDF, up to ${max}`,
  readFileTooLarge: "The file is larger than 10 MB.",
  readFileWrongType: "Only PNG, JPEG or WebP images and PDF files are read.",
  readImageNote: "A photo cannot be redacted before reading. In live mode the image itself reaches the model; the server removes personal details from the model's answer.",
  readWorking: "Reading the estimate. Personal details are removed from the text before anything reaches a model.",
  readWorkingFile: "Reading the file. A photo or a scanned page cannot be redacted; the image itself reaches the model.",
  readWorkingDemo: "Reading the estimate in demo mode. Nothing is sent to a model.",
  readWorkingPdf: "Reading the PDF's text on this device and removing personal details before anything is sent.",
  // the send gate for files (orchestrator note 11): nothing leaves the browser in live mode until the user confirms
  readGateTitle: (name: string) => `Before ${name} is sent`,
  readGateImage: "This image is sent to the model as is; names, member IDs and dates on it are not removed. Pasting the text instead lets OralCompass remove them first.",
  readGatePdf: "A PDF with a text layer is redacted before reading. A scanned PDF has no text to redact: its pages are sent to the model as images, with any names, member IDs and dates on them. Pasting the text instead lets OralCompass remove them first.",
  readGateAck: "I understand the file may reach the model without redaction.",
  readGateSend: "Send this file to the model",
  readGatePaste: "Paste the text instead",
  readGateCancel: "Do not send",
  readGateCancelled: "The file was not sent.",
  readDemoImage: "Demo mode reads only the two stored fictional estimates, as text. The image was not sent.",
  readStagesTitle: "Stages that ran",
  readRemoved: (labels: string) => `Removed before reading: ${labels}.`,
  readNothingRemoved: "No personal details were found to remove.",
  readImageNotRedacted: "The image was not redacted before reading.",
  // security-3 (owner note 11): the notice the server returns with needs_image_consent (image_notice); this copy is the fallback
  readImageNotice: "This image is sent to the model as is; names, member IDs and dates on it are not removed. Pasting the text instead lets OralCompass remove them first.",
  readImageSend: "Send the image as is",
  readImagePaste: "Paste the text instead",
  readDropped: (n: number) => `${n} ${n === 1 ? "line" : "lines"} the model returned ${n === 1 ? "is" : "are"} not in the text and ${n === 1 ? "is" : "are"} not shown.`,
  readReviewTitle: "Each line",
  readReviewIntro: "Nothing is ticked in advance. A line is added only when it has a procedure identifier, a fee and your tick.",
  readColAsWritten: "Care as written",
  readColMapped: "Kind of care",
  readColTooth: "Tooth",
  readColFee: "Price",
  readColCode: "Code as written",
  readColAdd: "Add",
  readNotMatched: "No match",
  readNoChoice: "No kind picked",
  readNone: "None printed",
  readFeeInput: (name: string) => `Price for ${name} (dollars)`,
  readFeeNotWritten: "No fee with a currency sign was read; a fee typed here is labeled as entered by you.",
  readAsRead: "As read:",
  readUnverified: "Read from an image; not checked against a text layer.",
  readInclude: (name: string) => `Add ${name} to your records`,
  readNeedsKey: "A kind of care is needed first.",
  readNeedsFee: "A price is needed first.",
  readTicked: (n: number, total: number) => `${n} of ${total} ticked`,
  readConfirm: "Add the ticked lines",
  readConfirmed: (n: number) => `${n} ${n === 1 ? "treatment item was" : "treatment items were"} added from the treatment plan. The estimate is recalculating; new islands are drawn on My journey.`,
  readConfirmError: "We couldn't add the lines.",
  readError: "We couldn't read the letter.",
  readRateLimited: "Too many reads in a short time. The reader opens again in a few minutes.",
  readIgnoredTitle: (n: number) => `Text that was not used (${n})`,
  readIgnoredNote: "Totals, insurance estimates and sentences addressed to automated readers are listed here and not used.",
  readManualTitle: "Add one procedure by hand",
  // ---- compare (CLAUDE.md rule 6) ----
  cmpTitle: "Side by side",
  cmpViewTitle: "Compare plans",
  cmpEligibilitySeeDoc: "see the plan document",
  cmpPicker: (i: number) => `Plan ${i}`,
  cmpNone: "none",
  cmpProcedures: (list: string) => `Procedures compared: ${list}.`,
  cmpNoneRecorded: "none recorded as planned",
  cmpUsageFor: (codes: string) => `Usage figures are entered for: ${codes}. Other columns show what is not provided.`,
  cmpEnteredThisPlan: "Usage, network status and allowed amounts in this column: entered for this plan only.",
  cmpNothingEntered: "Nothing is entered for this plan; figures from other plans are never carried over.",
  cmpNoPlanned: "No planned procedures to compare. A treatment item on My journey or My plan starts the comparison.",
  cmpLedgers: "Same estimate, each plan",
  cmpLedgerOf: (title: string) => `${title}: ledger`,
  cmpTopic: "Topic",
  cmpEligibility: "Eligibility",
  cmpOpenClause: (topic: string, plan: string) => `${topic} for ${plan}: open the clause behind this cell`,
  cmpNoClause: "No clause is cited for this cell; the value is what the document or your records provide.",
  cmpClauseFrom: (doc: string, page: string) => `${doc}, ${page}`,
  cmpPremium: "Premium (employee only, monthly)",
  cmpUpperBound: "(upper bound)",
  cmpUnresolvedFor: "Unresolved. Not provided for this plan:",
  cmpClose: "Close clause",
  // phone Compare (mobile-only direction): one plan per card under a sticky plan switcher
  cmpChoose: "Choose plans",
  cmpChooseClose: "Close plan choice",
  cmpDone: "Done",
  cmpPickTwo: "Two or more plans are needed for a comparison.",
  cmpOrderNote: "Plans appear in the order you chose. Inputs are entered for each plan separately; nothing is copied between plans.",
  cmpSwitcher: "Plans in this comparison",
  cmpCardsRegion: "Plan cards. Swipe sideways to move between plans.",
  cmpCardPos: (i: number, n: number) => `Plan ${i} of ${n}`,
  cmpDiffers: "Differs between plans",
  cmpWhoCanEnroll: "Where offered and who can enroll",
  cmpCardEstimate: "Estimated you pay for the procedures compared",
  // ---- documents ----
  docsPlan: "Plan documents",
  docsMine: "Your documents",
  docsNoPrivate: "No private documents are stored. Plan documents you add, typed estimates and benefit statements appear here with their extraction status.",
  docsUncertain: "Uncertain extractions are listed as needing confirmation; nothing uncertain enters a calculation until confirmed.",
  docsIgnoredTitle: "Text in the document that was not used as a rule",
  docsUnmatchedTitle: "Wording that matched none of the 16 procedure identifiers",
  docsUploadedPdf: "This PDF is stored in your own space and read only through an owner-checked request.",
  docsNotStoredPdf: "The PDF is not stored in this build (binary downloads from this host were blocked); clauses below show the exact quote with its page reference, and the link opens the official document.",
  docsAccessLimits: (n: number) => `Access limits recorded for this document (${n})`,
  docsReuse: "Reuse terms:",
  docsRetrieved: "retrieved",
  docsDated: "dated",
  docsPages: "pages",
  docsFilter: "Filter clauses",
  docsFilterPlaceholder: "deductible, crown, page…",
  docsNoMatch: (q: string) => `No clause in this document contains “${q}”. Clear the search to see every clause.`,
  docsNoClauses: "No clauses are recorded for this plan yet.",
  docsRemindersSummary: (n: number, next: string | null) => (n === 0 ? "None listed for your records" : `${n} listed${next ? ` · next ${next}` : ""}`),
  docsRemindersClose: "Close reminders",
  docsPageReview: "page attribution needs review",
  docsExported: "A copy of your records was downloaded.",
  docsDeleted: (what: string) => `Deleted: ${what}.`,
  docsNothingStored: "nothing stored",
  docsNeedsConfirmation: "needs your confirmation:",
  /** Plain words for the stored-document type and extraction status slugs (no raw snake_case on screen); unknown slugs lose their underscores. */
  docsSlug: (slug: string): string => ({
    plan_document_public: "public plan document", plan_document_upload: "uploaded plan document", benefit_statement: "benefit statement",
    treatment_plan: "treatment plan", pretreatment_estimate_response: "pre-treatment estimate response", upload: "upload",
    typed_by_user: "typed by you", cited_facts_verified_in_text: "cited facts checked against the text", published: "published",
  } as Record<string, string>)[slug] ?? slug.replace(/_/g, " "),
  docsRedactionRemoved: "Redaction preview removed:",
  docsNothing: "nothing",
  docsVersions: (labels: string) => `Published versions: ${labels}`,
  docsPlanDocument: "Plan document",
  docsRendered: "Document rendered. The sentences used in your estimate are listed under Evidence below the pages.",
  docsPageGroup: (p: number, n: number) => `Page ${p} of ${n}`,
  docsPageAlt: (p: number, n: number, title: string) => `Page ${p} of ${n}${title ? ` of ${title}` : ""}, as an image. The sentences used in your estimate are listed as text under Evidence below the pages.`,
} as const satisfies Record<string, string | ((...a: never[]) => string)>;

/** Word lists for the treatment-plan reader (kept outside PLAN, whose values are strings or formatters). */
export const PLAN_READ = {
  removed: { name_line: "a name line", member_id: "a member number", ssn: "a social security number", dob: "a date of birth", phone: "a phone number",
             email: "an email address", address: "a street address", group_number: "a group number", claim_number: "a claim number",
             account_number: "an account number" } as Record<string, string>,
  confidence: { printed_code: "Matched by the printed code", wording: "Matched by the wording", ambiguous: "Several identifiers fit", not_matched: "Not matched" } as Record<string, string>,
} as const;

export const DOC_WORDS: { kind: Record<string, string>; status: Record<string, string> } = {
  /* Readable words for a stored document's kind and status (the API sends snake_case codes). */
  kind: { plan_document_public: "public plan document", plan_document_upload: "uploaded plan document", treatment_plan: "treatment plan",
    pretreatment_estimate_response: "pre-treatment estimate", benefit_statement: "benefit statement", upload: "upload" },
  status: { cited_facts_verified_in_text: "figures checked against the document text", typed_by_user: "figures typed by you",
    cached: "read earlier", uploaded: "uploaded, not read yet" },
};

/** My plan as a painted passage (owner direction 05:58 / 06:00: the plan map in the journey's concept, full-bleed, phone only). */
export const PLAN_MAP = {
  mapLabel: "Plan map: five landmarks on one route",
  documentSection: "Plan document",
  youPay: "you pay",
  plan: "plan",
  planPays: "plan pays",
  calculated: "calculated",
  upperBound: "(upper bound)",
  noPlanned: "no planned procedures",
  waiting: "Waiting for information",
} as const;
