/**
 * Copy namespace: PLAN (My plan view, plan selector, benefit statement form, treatment plan importer, Compare, Documents); owner: web foundation + map agent.
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`; no em dashes.
 * Voice: what the documents say, what your records say, what the arithmetic yields. Nothing here tells the reader what to do.
 */
export const PLAN = {
  viewTitle: "My plan",
  // engine totals: arithmetic over steps that each carry their own stitch or badge (CLAUDE.md rule 2; orchestrator note 1)
  calculatedFromSteps: "Calculated from the steps below; each step shows its clause or source.",
  calculatedShort: "calculated",
  // ---- plan selector (spec §7.2; addendum B1/B2: a single `label.plan-pick select` of plan codes stays as the fast path) ----
  sourceLabel: "Plan source",
  modePreset: "Preset plan",
  modeUpload: "Your uploaded document",
  carrier: "Carrier",
  planName: "Plan name",
  planYear: "Plan year",
  planCode: "Plan",
  publicGroup: "Public plan documents",
  fictionalGroup: "Fictional demonstration plans",
  uploadsGroup: "Your uploaded documents",
  uploadedPlan: "Published document",
  noUploads: "No uploaded plan document has been published yet. A document added here is read, redacted, reviewed by you and then published as its own plan version.",
  uploadsLoading: "Reading your published documents…",
  uploadVersion: (label: string, date: string) => `${label}, published ${date}`,
  uploadedRibbon: (label: string) => `Uploaded plan, version ${label}`,
  singleYear: (year: string) => `${year} (the only plan year in this document)`,
  noPlan: "No plan is selected. The route is drawn from a plan document and your records.",
  landmarkHint: "Each landmark opens one part of the plan. Familiar terms first; the place names are only the map's.",
  // ---- live region (one per surface) ----
  estimateUpdated: "Estimate updated",
  recalculating: "Recalculating…",
  benefitsUpdated: "Benefit statement figures recorded",
  // ---- states (spec §4.7) ----
  noProcedures: "No planned procedures are recorded. The cost breakdown is drawn once a treatment item is added.",
  waitingForInfo: "Waiting for information",
  unlimited: "Unlimited (no dollar maximum)",
  unlimitedShort: "No dollar maximum",
  notProvided: "Not provided",
  // ---- benefit statement form (spec §4.5) ----
  bsTitle: "Benefit statement figures",
  bsNote: "Remaining amounts are derived on the server: plan limit (document) minus what the statement reports (entered by you).",
  bsEveryFigureUser: "Every figure entered here is labeled as entered by you, with the statement date.",
  bsDeductibleMet: "Deductible met so far this benefit year (dollars)",
  bsBenefitsUsed: "Paid by the plan so far this benefit year (dollars)",
  bsDeductibleMetOut: "Out-of-network deductible met so far (dollars)",
  bsBenefitsUsedOut: "Paid by the plan out-of-network so far (dollars)",
  bsCoverageStart: "Coverage start date",
  bsNetwork: "Your dentist's network status",
  bsNetworkIn: "In-network",
  bsNetworkOut: "Out-of-network",
  bsNetworkUnknown: "Not provided",
  bsSourceLabel: "Statement (label, required)",
  bsSourcePlaceholder: "MetLife benefit statement dated 2026-09-20",
  bsSourceDate: "Statement date (required)",
  bsSubmit: "Record these figures",
  bsSaved: "Figures recorded. The remaining amounts below are derived from them.",
  bsError: "The figures could not be recorded.",
  bsLabelRequired: "A statement label is required.",
  bsDateRequired: "A statement date is required.",
  bsDerivationTitle: "How the remaining amounts were derived",
  bsNoneEntered: "No benefit statement figures are entered for this plan.",
  bsOpen: "Enter benefit statement figures",
  bsSeparateOut: "This document states separate out-of-network limits; their figures are tracked separately.",
  // ---- add a procedure (spec §4.5) ----
  addTitle: "Add a procedure",
  addSummaryNote: "Type it, paste the estimate's text or read a photo of it",
  addIntro: "A treatment item from your dentist's estimate. The procedure is matched to one of 16 fixed identifiers; the name as written stays on the island.",
  addProcedure: "Procedure (one of 16 fixed identifiers)",
  addProcedureName: "Name as written on the estimate (optional)",
  addTooth: "Tooth or area",
  addQuantity: "Quantity",
  addFee: "Dentist's fee (dollars)",
  addAllowed: "Allowed amount (dollars, optional)",
  addAllowedSource: "Where the allowed amount comes from",
  addAllowedSourceNote: "Required when an allowed amount is given, for example a pre-treatment estimate response with its date.",
  addNetwork: "Network",
  addPlannedPrep: "Planned preparation date",
  addPlannedCompletion: "Planned completion date",
  addAppointment: "Appointment date",
  addStatus: "Status",
  statusPlanned: "Planned",
  statusScheduled: "Scheduled",
  statusMentioned: "Mentioned at a consultation",
  addSource: "Source (required)",
  addSourcePlaceholder: "treatment plan 2026-09-24 (typed)",
  addCode: "Procedure code as written (optional)",
  addSubmit: "Add this procedure",
  addAdded: (name: string) => `${name} was added to your records. The estimate is recalculating.`,
  addError: "The procedure could not be added.",
  addFeeRequired: "A dentist's fee is required.",
  addSourceRequired: "A source is required.",
  addAllowedSourceRequired: "An allowed amount needs its source.",
  addCategoryHint: (hint: string) => `class hint: ${hint}`,
  amountOrEmpty: "An amount in dollars, or empty when not provided.",
  procedureRequired: "A procedure is required.",
  // ---- read a treatment plan (addendum D.5a; api/app/treatment_reader.py) ----
  readTitle: "Read a treatment plan",
  readIntro: "Paste the text of your dentist's estimate, or add a photo or PDF of it. Personal details are removed from pasted text first; a photo reaches the model as it is. Each line is matched to one of the 16 procedure identifiers, and nothing is added until you confirm it.",
  readModeDemo: "Demo mode: only the two stored fictional estimates are read",
  readModeLive: (model: string) => `Live mode: read by ${model}`,
  readPasteLabel: "Estimate text",
  readPastePlaceholder: "Tooth   Code    Procedure    Fee",
  readSamplesLabel: "Sample text",
  readSampleButton: (label: string) => label,
  readRun: "Read these lines",
  readTextRequired: "There is no text to read yet.",
  readOr: "or",
  readFileTitle: "Photo or PDF of the estimate",
  readFileHint: "Drop a photo or PDF here",
  readFileChoose: "Choose a file",
  readFileCancel: "Cancel",
  readFileLimits: (max: string) => `PNG, JPEG, WebP or PDF, up to ${max}`,
  readFileTooLarge: "The file is larger than 10 MB.",
  readFileWrongType: "Only PNG, JPEG or WebP images and PDF files are read.",
  readImageNote: "A photo cannot be redacted before reading. In live mode the image itself reaches the model; the server removes personal details from the model's answer.",
  readWorking: "Reading the estimate. Personal details are removed from the text before anything reaches a model.",
  readWorkingFile: "Reading the file. A photo or a scanned page cannot be redacted; the image itself reaches the model.",
  readWorkingDemo: "Reading the estimate in demo mode. Nothing is sent to a model.",
  // the send gate for files (orchestrator note 11): nothing leaves the browser in live mode until the user confirms
  readGateTitle: (name: string) => `Before ${name} is sent`,
  readGateImage: "This image is sent to the model as is; names, member IDs and dates on it are not removed. Pasting the text instead lets OralCompass remove them first.",
  readGatePdf: "A PDF with a text layer is redacted before reading. A scanned PDF has no text to redact: its pages are sent to the model as images, with any names, member IDs and dates on them. Pasting the text instead lets OralCompass remove them first.",
  readGateAck: "I understand the file may reach the model without redaction.",
  readGateSend: "Send this file to the model",
  readGatePaste: "Paste the text instead",
  readGateCancel: "Do not send",
  readGateCancelled: "The file was not sent.",
  readDemoImage: "Demo mode reads only the two stored fictional estimates, as text. The image was not sent.",
  readStagesTitle: "Stages that ran",
  readRemoved: (labels: string) => `Removed before reading: ${labels}.`,
  readNothingRemoved: "No personal details were found to remove.",
  readImageNotRedacted: "The image was not redacted before reading.",
  // security-3 (owner note 11): the notice the server returns with needs_image_consent (image_notice); this copy is the fallback
  readImageNotice: "This image is sent to the model as is; names, member IDs and dates on it are not removed. Pasting the text instead lets OralCompass remove them first.",
  readImageSend: "Send the image as is",
  readImagePaste: "Paste the text instead",
  readDropped: (n: number) => `${n} ${n === 1 ? "line" : "lines"} the model returned ${n === 1 ? "is" : "are"} not in the text and ${n === 1 ? "is" : "are"} not shown.`,
  readReviewTitle: "Review each line",
  readReviewIntro: "Nothing is ticked in advance. A line is added only when it has a procedure identifier, a fee and your tick.",
  readColAsWritten: "Procedure as written",
  readColMapped: "Mapped procedure",
  readColTooth: "Tooth",
  readColFee: "Fee",
  readColCode: "Code as written",
  readColAdd: "Add",
  readNotMatched: "Not matched",
  readNoChoice: "No identifier chosen",
  readNone: "None printed",
  readFeeInput: (name: string) => `Fee for ${name} (dollars)`,
  readFeeNotWritten: "No fee with a currency sign was read; a fee typed here is labeled as entered by you.",
  readAsRead: "As read:",
  readUnverified: "Read from an image; not checked against a text layer.",
  readInclude: (name: string) => `Add ${name} to your records`,
  readNeedsKey: "A procedure identifier is needed first.",
  readNeedsFee: "A fee is needed first.",
  readTicked: (n: number, total: number) => `${n} of ${total} ticked`,
  readConfirm: "Add the ticked lines",
  readConfirmed: (n: number) => `${n} ${n === 1 ? "treatment item was" : "treatment items were"} added from the treatment plan. The estimate is recalculating; new islands are drawn on My journey.`,
  readConfirmError: "The lines could not be added.",
  readError: "The estimate could not be read.",
  readRateLimited: "Too many reads in a short time. The reader opens again in a few minutes.",
  readIgnoredTitle: (n: number) => `Text that was not used (${n})`,
  readIgnoredNote: "Totals, insurance estimates and sentences addressed to automated readers are listed here and not used.",
  readManualTitle: "Add one procedure by hand",
  // ---- compare (CLAUDE.md rule 6) ----
  cmpTitle: "Side by side",
  cmpViewTitle: "Compare plans",
  cmpEligibilitySeeDoc: "see the plan document",
  cmpPicker: (i: number) => `Plan ${i}`,
  cmpNone: "none",
  cmpProcedures: (list: string) => `Procedures compared: ${list}.`,
  cmpNoneRecorded: "none recorded as planned",
  cmpUsageFor: (codes: string) => `Usage figures are entered for: ${codes}. Other columns show what is not provided.`,
  cmpEnteredThisPlan: "Usage, network status and allowed amounts in this column: entered for this plan only.",
  cmpNothingEntered: "Nothing is entered for this plan; figures from other plans are never carried over.",
  cmpNoPlanned: "No planned procedures to compare. A treatment item on My journey or My plan starts the comparison.",
  cmpLedgers: "Same estimate, each plan",
  cmpLedgerOf: (title: string) => `${title}: ledger`,
  cmpTopic: "Topic",
  cmpEligibility: "Eligibility",
  cmpOpenClause: (topic: string, plan: string) => `${topic} for ${plan}: open the clause behind this cell`,
  cmpNoClause: "No clause is cited for this cell; the value is what the document or your records provide.",
  cmpClauseFrom: (doc: string, page: string) => `${doc}, ${page}`,
  cmpPremium: "Premium (employee only, monthly)",
  cmpUpperBound: "(upper bound)",
  cmpUnresolvedFor: "Unresolved. Not provided for this plan:",
  cmpClose: "Close clause",
  // phone Compare (mobile-only direction): one plan per card under a sticky plan switcher
  cmpChoose: "Choose plans",
  cmpChooseClose: "Close plan choice",
  cmpDone: "Done",
  cmpPickTwo: "Two or more plans are needed for a comparison.",
  cmpOrderNote: "Plans appear in the order you chose. Inputs are entered for each plan separately; nothing is copied between plans.",
  cmpSwitcher: "Plans in this comparison",
  cmpCardsRegion: "Plan cards. Swipe sideways to move between plans.",
  cmpCardPos: (i: number, n: number) => `Plan ${i} of ${n}`,
  cmpDiffers: "Differs between plans",
  cmpWhoCanEnroll: "Where offered and who can enroll",
  cmpCardEstimate: "Estimated you pay for the procedures compared",
  // ---- documents ----
  docsPlan: "Plan documents",
  docsMine: "Your documents",
  docsNoPrivate: "No private documents are stored. Plan documents you add, typed estimates and benefit statements appear here with their extraction status.",
  docsUncertain: "Uncertain extractions are listed as needing confirmation; nothing uncertain enters a calculation until confirmed.",
  docsIgnoredTitle: "Text in the document that was not used as a rule",
  docsUnmatchedTitle: "Wording that matched none of the 16 procedure identifiers",
  docsUploadedPdf: "This PDF is stored in your own space and read only through an owner-checked request.",
  docsNotStoredPdf: "The PDF is not stored in this build (binary downloads from this host were blocked); clauses below show the exact quote with its page reference, and the link opens the official document.",
  docsAccessLimits: (n: number) => `Access limits recorded for this document (${n})`,
  docsReuse: "Reuse terms:",
  docsRetrieved: "retrieved",
  docsDated: "dated",
  docsPages: "pages",
  docsFilter: "Filter clauses",
  docsFilterPlaceholder: "deductible, crown, page…",
  docsNoMatch: (q: string) => `No clause in this document contains “${q}”. Clear the search to see every clause.`,
  docsNoClauses: "No clauses are recorded for this plan yet.",
  docsRemindersSummary: (n: number, next: string | null) => (n === 0 ? "None listed for your records" : `${n} listed${next ? ` · next ${next}` : ""}`),
  docsRemindersClose: "Close reminders",
  docsPageReview: "page attribution needs review",
  docsExported: "A copy of your records was downloaded.",
  docsDeleted: (what: string) => `Deleted: ${what}.`,
  docsNothingStored: "nothing stored",
  docsNeedsConfirmation: "needs your confirmation:",
  /** Plain words for the stored-document type and extraction status slugs (no raw snake_case on screen); unknown slugs lose their underscores. */
  docsSlug: (slug: string): string => ({
    plan_document_public: "public plan document", plan_document_upload: "uploaded plan document", benefit_statement: "benefit statement",
    treatment_plan: "treatment plan", pretreatment_estimate_response: "pre-treatment estimate response", upload: "upload",
    typed_by_user: "typed by you", cited_facts_verified_in_text: "cited facts checked against the text", published: "published",
  } as Record<string, string>)[slug] ?? slug.replace(/_/g, " "),
  docsRedactionRemoved: "Redaction preview removed:",
  docsNothing: "nothing",
  docsVersions: (labels: string) => `Published versions: ${labels}`,
  docsPlanDocument: "Plan document",
  docsRendered: "Document rendered. The sentences used in your estimate are listed under Evidence below the pages.",
  docsPageGroup: (p: number, n: number) => `Page ${p} of ${n}`,
  docsPageAlt: (p: number, n: number, title: string) => `Page ${p} of ${n}${title ? ` of ${title}` : ""}, as an image. The sentences used in your estimate are listed as text under Evidence below the pages.`,
} as const satisfies Record<string, string | ((...a: never[]) => string)>;

/** Word lists for the treatment-plan reader (kept outside PLAN, whose values are strings or formatters). */
export const PLAN_READ = {
  removed: { name_line: "a name line", member_id: "a member number", ssn: "a social security number", dob: "a date of birth", phone: "a phone number",
             email: "an email address", address: "a street address" } as Record<string, string>,
  confidence: { printed_code: "Matched by the printed code", wording: "Matched by the wording", ambiguous: "Several identifiers fit", not_matched: "Not matched" } as Record<string, string>,
} as const;

export const DOC_WORDS: { kind: Record<string, string>; status: Record<string, string> } = {
  /* Readable words for a stored document's kind and status (the API sends snake_case codes). */
  kind: { plan_document_public: "public plan document", plan_document_upload: "uploaded plan document", treatment_plan: "treatment plan",
    pretreatment_estimate_response: "pre-treatment estimate", benefit_statement: "benefit statement", upload: "upload" },
  status: { cited_facts_verified_in_text: "figures checked against the document text", typed_by_user: "figures typed by you",
    cached: "read earlier", uploaded: "uploaded, not read yet" },
};

/** My plan as a painted passage (owner direction 05:58 / 06:00: the plan map in the journey's concept, full-bleed, phone only). */
export const PLAN_MAP = {
  mapLabel: "Plan map: five landmarks on one route",
  documentSection: "Plan document",
  youPay: "you pay",
  plan: "plan",
  planPays: "plan pays",
  calculated: "calculated",
  upperBound: "(upper bound)",
  noPlanned: "no planned procedures",
  waiting: "Waiting for information",
} as const;
