/**
 * Copy namespace: UPLOAD (upload wizard, redaction preview, extraction stages, review table, publish) — owner: web upload-review + assistant agent.
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`; no em dashes.
 * The stage copy table lives in spec §7.3 step 3; the review footer and publish note in step 4. Server texts that the API already returns
 * (ribbon, notes_for_review, stage labels) are shown as returned; the strings below are the client's own.
 * REMINDERS (components/notifications/RemindersPanel.tsx) lives here too: it is the same owner's namespace file.
 */
/** Category words for the chips ("3 names") and the list rows ("Member ID"); keys are the detector's IdentifierCategory values. */
const IDENTIFIER_WORDS: Record<string, [string, string]> = {
  name: ["name", "names"], address: ["address", "addresses"], member_id: ["member ID", "member IDs"], group_number: ["group number", "group numbers"],
  claim_number: ["claim number", "claim numbers"], account_number: ["account number", "account numbers"], ssn: ["SSN", "SSNs"],
  dob: ["date of birth", "dates of birth"], phone: ["phone number", "phone numbers"], email: ["email address", "email addresses"],
};
const IDENTIFIER_NAMES: Record<string, string> = {
  name: "Name", address: "Address", member_id: "Member ID", group_number: "Group number", claim_number: "Claim number", account_number: "Account number",
  ssn: "SSN", dob: "Date of birth", phone: "Phone number", email: "Email address",
};

export const UPLOAD = {
  // entry + dialog
  trigger: "Add a plan document",
  title: "Add a plan document",
  description: "Personal details are found and removed on this device first. The PDF is then stored in your private space, extracted, verified against its own pages and reviewed by you before any rule enters an estimate.",
  close: "Close",
  loadingWizard: "Opening the document tools…",
  stepName: (n: number) => ["Choose a file", "Personal details", "Extraction", "Review and publish"][n - 1] ?? `Step ${n}`,
  stepLabel: (n: number, name: string) => `Step ${n}: ${name}`,
  demoRibbon: "Demo mode: fields come from a stored fixture that matches this document's checksum.",
  demoEnvironment: "Demo environment: no extraction model is configured. A document whose checksum matches a stored fixture extracts from that fixture; any other PDF opens the hand-entry path.",
  liveLabel: (model: string) => `Live mode: ${model} proposes fields; the server verifies every quote against the page text.`,
  // step 1: file
  fileTitle: "Plan document (PDF)",
  fileHint: "Drop a PDF here, or pick one from this device",
  choose: "Choose a PDF",
  cancel: "Cancel",
  limits: (max: string) => `PDF up to ${max}, at most 100 pages`,
  notPdf: "This file is not a PDF.",
  tooLarge: "This file is larger than 32 MB.",
  tooManyPages: "This document has more than 100 pages.",
  unreadable: "This PDF could not be read; it has no readable pages.",
  phaseChecksum: "Computing the document checksum…",
  phaseReading: (done: number, total: number) => `Reading the text layer (${done} of ${total} pages)…`,
  phaseDetecting: "Removing personal details on this device…",
  phaseUploading: "Sending the document to your private space…",
  sampleButton: "Try a fictional sample statement",
  sampleNote: "A made-up member benefits statement for a fictional plan. Every name, number and address on it is invented.",
  sampleLoading: "Opening the sample statement…",
  sampleFailed: "The sample statement could not be loaded from this server.",
  uploadFailed: "The document could not be stored. The API runs on :8000 with ORALCOMPASS_DEV_AUTH=1.",
  serverNotPdf: "The server did not read this file as a PDF.",
  serverTooLarge: "The server limits uploads to 32 MB.",
  serverTooManyPages: "The server limits documents to 100 pages.",
  shaMismatch: "The checksum computed here differs from the server's; the file changed during upload.",
  invalidClientRedaction: "The server did not accept the list of personal details, so nothing was stored. The file can be chosen again.",
  uploadQuota: "Your private space holds the maximum number of uploaded documents.",
  fileSummary: (name: string, pages: number, sha: string) => `${name}: ${pages} pages, checksum ${sha.slice(0, 12)}…`,
  // step 2: personal details, reviewed on this device before anything is uploaded (client redaction, design point 2)
  identifiersRemoved: (n: number) => (n === 1 ? "1 personal identifier removed before AI analysis" : `${n} personal identifiers removed before AI analysis`),
  identifiersRemovedWords: (n: number) => (n === 1 ? "personal identifier removed before AI analysis" : "personal identifiers removed before AI analysis"),
  noneFoundTitle: "No personal identifiers found.",
  noneFoundBody: "The AI receives the plan text as is.",
  noTextTitle: "No text could be read on this device.",
  noTextBody: "This PDF has no text layer, so nothing could be checked or removed here before upload.",
  summaryCaption: "Found and removed on this device. The AI receives only the plan text it needs: coverage clauses, deductible, annual maximum, procedure codes, percentages, exclusions, waiting periods and limits.",
  categoriesLabel: "Removed, by kind",
  categoryCount: (c: string, n: number) => {
    const w = IDENTIFIER_WORDS[c] ?? [c, c];
    return `${n} ${n === 1 ? w[0] : w[1]}`;
  },
  categoryName: (c: string) => IDENTIFIER_NAMES[c] ?? c,
  keptCount: (n: number) => (n === 1 ? "1 identifier stays in the text, as you chose." : `${n} identifiers stay in the text, as you chose.`),
  listSummary: (n: number) => `Each identifier found (${n})`,
  listIntro: "Values stay masked unless shown. A switch keeps a value in the text when it is not personal, and the count changes with it.",
  maskedSr: (visible: string) => (visible ? `masked, visible characters ${visible}` : "masked"),
  show: "Show",
  hide: "Hide",
  showValue: (c: string) => `Show this ${(IDENTIFIER_WORDS[c] ?? [c])[0]}`,
  hideValue: (c: string) => `Hide this ${(IDENTIFIER_WORDS[c] ?? [c])[0]}`,
  removedIn: (n: number) => (n === 1 ? "removed in 1 place" : `removed in ${n} places`),
  keptIn: (n: number) => (n === 1 ? "stays in the text, 1 place" : `stays in the text, ${n} places`),
  onPages: (ranges: string, many: boolean) => `${many ? "pages" : "page"} ${ranges}`,
  keepInText: "Keep in text",
  termsTitle: "Your own terms",
  termRemove: (t: string) => `Stop removing ${t}`,
  termNotFound: "not in the text",
  termIn: (n: number) => (n === 1 ? "1 place" : `${n} places`),
  termTooShort: "A term needs at least 2 characters.",
  termLimit: "Up to 20 terms can be added.",
  termDuplicate: "This term is already on the list.",
  previewTitle: "Redacted text",
  previewNote: (shown: number, total: number) => (shown < total ? `As read on this device. The first ${shown.toLocaleString("en-US")} of ${total.toLocaleString("en-US")} characters are shown.` : "As read on this device."),
  previewPage: (n: number) => `Page ${n}`,
  previewEmpty: "This PDF has no text layer to read on this device. The server reads it and applies its own check before any AI call.",
  continueUpload: "Continue",
  chooseAnother: "Choose another file",
  continueNote: "Continue stores the PDF in your private space and starts the extraction. The server removes these details again, and runs its own check, before any AI call.",
  storedNote: "The document is stored with these removals.",
  liveCount: (n: number) => (n === 1 ? "1 personal identifier removed before AI analysis" : `${n} personal identifiers removed before AI analysis`),
  stageRemovedCount: (label: string, n: number) => `${label} \u00b7 ${n} removed`,
  serverCheckExtra: (n: number) => (n === 1 ? "1 more was found by the server's own check." : `${n} more were found by the server's own check.`),
  serverCounted: "Counted by the server on the text it read for extraction.",
  // step 2: redaction
  redactionTitle: "Redaction preview",
  removed: (list: string) => `Removed before any model call: ${list || "nothing matched"}`,
  previewIntro: "The first 1,200 characters of the redacted text:",
  addTerm: "Add a word or number to remove",
  addTermHint: "Up to 20 terms, each 2 to 64 characters. They are removed on this device as soon as they are added.",
  addTermButton: "Remove this term",
  extraTerms: (list: string) => `Also removed: ${list}`,
  termTooLong: "A term is longer than 64 characters.",
  continueRedaction: "Continue with these redactions",
  dataNote: "The document text is treated as data. Nothing in it is followed as an instruction.",
  startingExtraction: "Starting extraction…",
  startFailed: "Extraction did not start. The document is stored in your space; Continue tries again.",
  startLimited: "Too many extractions in a short time. Continue works again in a few minutes.",
  // step 3: extraction (spec §7.3 step 3 table; stage names come from the server's stages[])
  extractionTitle: "Extraction",
  stageQueued: "Waiting to start…",
  stageReading: (done: number, total: number) => `Reading the document text (${done} of ${total} pages)…`,
  stageRedacting: "Removing personal details…",
  stageIdentifying: "Identifying benefit fields…",
  stageMatching: "Matching the 16 procedure identifiers to the document's wording…",
  stageVerifying: (done: number, total: number) => `Verifying each quote against the page text (${done} of ${total})…`,
  stageReady: (c: number, l: number, n: number, nf: number) => `Extraction complete. ${c} confirmed · ${l} likely · ${n} need review · ${nf} not found.`,
  stageFailed: (reason: string) => `The document could not be read automatically (${reason}). Fields can be entered by hand below.`,
  stageDemoNoModel: "No extraction model is configured in this environment. Fields from a known fixture document are shown; others can be entered by hand.",
  stageOf: (i: number, n: number, name: string) => `Stage ${i} of ${n}: ${name}`,
  modelLine: (model: string) => `Model: ${model}`,
  reviewFields: "Review the fields",
  extractionNotStarted: "Extraction has not started for this document.",
  pollingFailed: "The extraction status could not be read. The pipeline keeps running on the server.",
  // step 4: review
  reviewTitle: "Review the extracted fields",
  reviewIntro: "One row per field the extractor looked for. Nothing enters the plan version until you decide on it.",
  landmark: { harbor: "Your plan", bridge: "Deductible", cove: "Coverage", lookout: "Annual maximum", rules: "Rules" } as Record<string, string>,
  colField: "Field",
  colProposed: "Proposed value",
  colConfidence: "Confidence",
  colQuote: "Quote",
  colDecision: "Your decision",
  confidence: { confirmed: "Confirmed", likely: "Likely", needs_review: "Needs review", not_found: "Not found" } as Record<string, string>,
  confidenceGlyph: { confirmed: "✓", likely: "◐", needs_review: "?", not_found: "∅" } as Record<string, string>,
  quoteVerified: "quote verified on the cited page",
  quoteNearby: "page attribution needs review",
  userConfirmed: "confirmed by you",
  noQuote: "No quote was found for this field.",
  page: (p: number) => `p.${p}`,
  pageNote: (n: string) => `Page note: ${n}`,
  openPage: "Open page",
  closePage: "Close page",
  pageTitle: (p: number) => `Page ${p} of the uploaded document`,
  pageLoading: "Rendering the page…",
  looksRight: "Looks right",
  edit: "Edit",
  notInDocument: "Not in document",
  decided: { confirmed: "Confirmed by you", edited: "Entered by you", not_in_document: "Marked not in document", candidate: "Candidate chosen" } as Record<string, string>,
  decidedAt: (d: string) => `decided ${d}`,
  undo: "Change decision",
  candidates: "Candidates found in the document; each keeps AMBIGUOUS unless its quote verifies on the page:",
  candidateName: (field: string) => `Candidates for ${field}`,
  candidateOption: (value: string, page: number) => `${value}, page ${page}`,
  newValue: "New value",
  valueDollars: "Dollars",
  valuePercent: "Percent the plan pays",
  valueMonths: "Months",
  valueMonth: "Month",
  valueText: "Value as written in your source",
  valueBool: { yes: "Yes", no: "No" },
  valueClass: "Coverage class",
  valueList: "Value (JSON, as the extractor would write it)",
  sourceLabel: "Source",
  sourceHint: "Where this value comes from (another document, a statement, a call), kept with the value.",
  sourceRequired: "A source is required for an entered value.",
  invalidValue: "This value does not fit the field's unit.",
  unknownClass: "The class must be one of the document's classes.",
  enterValue: "Enter this value",
  cancelEdit: "Cancel",
  required: "required",
  requiredGroup: "at least one coverage class row",
  /** Plain-language names for extraction field paths, matching the review table's row labels (api/app/extraction.py). Never show a raw path. */
  fieldPath: {
    benefit_year_start_month: "Benefit year start month",
    deductible_individual: "Deductible (per person)",
    deductible_family: "Deductible (family)",
    annual_max: "Annual maximum",
    alternate_benefit: "Alternate benefit clause",
    waiting_months: "Waiting periods",
    oon_rule: "Out-of-network payment basis",
    dos_rule: "Date of service rule",
    class_of: "Coverage class for at least one procedure",
  } as Record<string, string>,
  fieldShareIn: (n: number) => `Plan share in-network (coverage class ${n})`,
  fieldShareOut: (n: number) => `Plan share out-of-network (coverage class ${n})`,
  fieldClassOf: (proc: string) => `Coverage class: ${proc}`,
  fieldAllowed: (proc: string) => `Allowed amount: ${proc}`,
  fieldExcluded: (proc: string) => `Exclusion: ${proc}`,
  fieldFrequency: (n: number) => `Frequency limit (rule ${n})`,
  fieldPremium: (cat: string) => `Monthly premium: ${cat}`,
  fieldOther: "A plan detail",
  confirmAllVerified: "Confirm all verified quotes",
  confirmAllNote: (n: number) => `${n} row${n === 1 ? "" : "s"} with a quote verified on the cited page and no decision yet.`,
  waitingCount: (n: number) => (n === 1 ? "1 required field is waiting for a decision." : `${n} required fields are waiting for a decision.`),
  allDecided: "Every required field has a decision.",
  undecidedList: (list: string) => `Waiting: ${list}`,
  publish: "Publish this plan version",
  publishHold: "Hold to publish, or use Confirm publish below.",
  publishConfirmPrompt: "Publish this plan version now? Only decided rows enter it.",
  publishConfirm: "Confirm publish",
  publishConfirmCancel: "Not yet",
  publishing: "Publishing…",
  published: (label: string) => `Published as ${label}`,
  publishedBody: (label: string) => `${label} is now a plan version in your space. The plan picker lists it; estimates calculated with it carry the ${label} label.`,
  publishedKept: "The journey keeps the plan it had; the plan picker switches whenever you choose.",
  showJourneyOn: (label: string) => `Show this journey on ${label}`,      // a plain switch, never a suggestion (advice_lint: no "use" opener)
  publishUndecided: (list: string) => `The server lists required rows without a decision: ${list}.`,
  publishInvalid: (type: string) => `The engine rejected the built plan (${type}). Decisions can be changed and the version published again.`,
  publishFailed: "The plan version could not be published.",
  publishNote: "Only decided rows enter the plan version. Rows marked \"Needs review\" stay AMBIGUOUS and are flagged on every estimate; rows marked \"Not in document\" stay UNKNOWN.",
  reviewFailed: "The decision could not be recorded.",
  ignoredWordingTitle: "Text in the document that was not used as a rule",
  unmatchedWordingTitle: "Wording that matched none of the 16 procedure identifiers",
  wordingPage: (p: number) => `page ${p}`,
  notesTitle: "Notes from extraction",
  notesDropped: (n: number) => `${n} note${n === 1 ? "" : "s"} removed by the information-only check.`,
  valueUnlimited: "no annual maximum",
  valueNone: "nothing proposed",
  monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  months: (n: number) => `${n} month${n === 1 ? "" : "s"}`,
  percent: (bp: number) => `${(bp / 100).toLocaleString("en-US", { maximumFractionDigits: 2 })}%`,
  frequencyValue: (n: number, clock: string) => `${n} per ${clock.replace(/_/g, " ")}`,
  // demo-mode / fictional ribbons
  fictional: "Fictional demonstration plan",
  demoFixtureMatch: "This document's checksum matches a stored fixture.",
} as const satisfies Record<string, string | string[] | Record<string, string> | ((...a: never[]) => string)>;

/** Reminders panel + push subscription client (components/notifications/RemindersPanel.tsx). Information only; nothing urges. */
export const REMINDERS = {
  title: "Reminders",
  intro: "Dates and figures from your plan document and your records, each with its source.",
  loading: "Reading your reminders…",
  empty: "No reminders are listed for your records.",
  asOf: (d: string) => `As of ${d}`,
  cite: (doc: string, page: number) => `${doc} p.${page}`,
  source: (s: string) => `Source: ${s}`,
  kind: { benefit_year_end: "Benefit year", frequency_next_eligible: "Frequency interval", frequency_count_reset: "Frequency count", document_awaiting_decision: "Document" } as Record<string, string>,
  noDate: "no date",
  failed: "Reminders could not be loaded.",
  pushTitle: "Push reminders on this device",
  pushBody: "A push message carries no figures and no names. It is a fixed sentence saying that a date you chose to follow is approaching.",
  subscribe: "Turn on push reminders",
  unsubscribe: "Turn off push reminders",
  subscribed: "Push reminders are on for this browser.",
  notSubscribed: "Push reminders are off for this browser.",
  working: "Updating the subscription…",
  unsupported: "This browser does not support push messages.",
  noKey: "Push is not configured on this server (no VAPID public key).",
  denied: "Notification permission was declined in this browser.",
  insecure: "Push needs a secure page (https or localhost).",
  subscribeFailed: "The subscription could not be stored.",
  testPush: "Send a test push",
  testSent: (sent: number, failed: number) => `Test push: ${sent} sent, ${failed} failed.`,
  testUnavailable: "Push is not configured on this server (no VAPID private key).",
  devOnly: "Dev auth is on for this server; the test push is a development control.",
} as const satisfies Record<string, string | Record<string, string> | ((...a: never[]) => string)>;
