/**
 * Copy namespace: UPLOAD (upload wizard, redaction preview, extraction stages, review table, publish) — owner: web upload-review + assistant agent.
 * Append strings here only; `lib/copy.ts` re-exports this file. Every string must pass `python3 tools/advice_lint.py`; no em dashes.
 * The stage copy table lives in spec §7.3 step 3; the review footer and publish note in step 4. Server texts that the API already returns
 * (ribbon, notes_for_review, stage labels) are shown as returned; the strings below are the client's own.
 * REMINDERS (components/notifications/RemindersPanel.tsx) lives here too: it is the same owner's namespace file.
 */
export const UPLOAD = {
  // entry + dialog
  trigger: "Add a plan document",
  title: "Add a plan document",
  description: "A PDF is read in your private space: redacted, extracted, verified against its own pages, then reviewed by you before any rule enters an estimate.",
  close: "Close",
  stepName: (n: number) => ["Choose a file", "Redaction preview", "Extraction", "Review and publish"][n - 1] ?? `Step ${n}`,
  stepLabel: (n: number, name: string) => `Step ${n}: ${name}`,
  demoRibbon: "Demo mode: fields come from a stored fixture that matches this document's checksum.",
  liveLabel: (model: string) => `Live mode: ${model} proposes fields; the server verifies every quote against the page text.`,
  // step 1: file
  fileTitle: "Plan document (PDF)",
  fileHint: "Drop a PDF here, or pick one from this device",
  choose: "Choose a PDF",
  cancel: "Cancel",
  limits: (max: string) => `PDF up to ${max}, at most 100 pages`,
  notPdf: "This file is not a PDF.",
  tooLarge: "This file is larger than 32 MB.",
  tooManyPages: "This document has more than 100 pages.",
  unreadable: "This PDF could not be read; it has no readable pages.",
  phaseChecksum: "Computing the document checksum…",
  phaseReading: (done: number, total: number) => `Reading the text layer (${done} of ${total} pages)…`,
  phaseUploading: "Sending the document to your private space…",
  uploadFailed: "The document could not be stored. The API runs on :8000 with ORALCOMPASS_DEV_AUTH=1.",
  serverNotPdf: "The server did not read this file as a PDF.",
  serverTooLarge: "The server limits uploads to 32 MB.",
  serverTooManyPages: "The server limits documents to 100 pages.",
  shaMismatch: "The checksum computed here differs from the server's; the file changed during upload.",
  fileSummary: (name: string, pages: number, sha: string) => `${name}: ${pages} pages, checksum ${sha.slice(0, 12)}…`,
  // step 2: redaction
  redactionTitle: "Redaction preview",
  removed: (list: string) => `Removed before any model call: ${list || "nothing matched"}`,
  previewIntro: "The first 1,200 characters of the redacted text:",
  addTerm: "Add a word or number to remove",
  addTermHint: "Up to 20 terms, each up to 64 characters. The preview re-runs on the server.",
  addTermButton: "Remove this term",
  extraTerms: (list: string) => `Also removed: ${list}`,
  termTooLong: "A term is longer than 64 characters.",
  continueRedaction: "Continue with these redactions",
  dataNote: "The document text is treated as data. Nothing in it is followed as an instruction.",
  startingExtraction: "Starting extraction…",
  // step 3: extraction (spec §7.3 step 3 table; stage names come from the server's stages[])
  extractionTitle: "Extraction",
  stageQueued: "Waiting to start…",
  stageReading: (done: number, total: number) => `Reading the document text (${done} of ${total} pages)…`,
  stageRedacting: "Removing personal details…",
  stageIdentifying: "Identifying benefit fields…",
  stageMatching: "Matching the 16 procedure identifiers to the document's wording…",
  stageVerifying: (done: number, total: number) => `Verifying each quote against the page text (${done} of ${total})…`,
  stageReady: (c: number, l: number, n: number, nf: number) => `Extraction complete. ${c} confirmed · ${l} likely · ${n} need review · ${nf} not found.`,
  stageFailed: (reason: string) => `The document could not be read automatically (${reason}). Fields can be entered by hand below.`,
  stageDemoNoModel: "No extraction model is configured in this environment. Fields from a known fixture document are shown; others can be entered by hand.",
  stageOf: (i: number, n: number, name: string) => `Stage ${i} of ${n}: ${name}`,
  modelLine: (model: string) => `Model: ${model}`,
  reviewFields: "Review the fields",
  extractionNotStarted: "Extraction has not started for this document.",
  pollingFailed: "The extraction status could not be read. The pipeline keeps running on the server.",
  // step 4: review
  reviewTitle: "Review the extracted fields",
  reviewIntro: "One row per field the extractor looked for. Nothing enters the plan version until you decide on it.",
  landmark: { harbor: "Your plan", bridge: "Deductible", cove: "Coverage", lookout: "Annual maximum", rules: "Rules" } as Record<string, string>,
  colField: "Field",
  colProposed: "Proposed value",
  colConfidence: "Confidence",
  colQuote: "Quote",
  colDecision: "Your decision",
  confidence: { confirmed: "Confirmed", likely: "Likely", needs_review: "Needs review", not_found: "Not found" } as Record<string, string>,
  confidenceGlyph: { confirmed: "✓", likely: "◐", needs_review: "?", not_found: "∅" } as Record<string, string>,
  quoteVerified: "quote verified on the cited page",
  quoteNearby: "page attribution needs review",
  userConfirmed: "confirmed by you",
  noQuote: "No quote was found for this field.",
  page: (p: number) => `p.${p}`,
  pageNote: (n: string) => `Page note: ${n}`,
  openPage: "Open page",
  closePage: "Close page",
  pageTitle: (p: number) => `Page ${p} of the uploaded document`,
  pageLoading: "Rendering the page…",
  looksRight: "Looks right",
  edit: "Edit",
  notInDocument: "Not in document",
  decided: { confirmed: "Confirmed by you", edited: "Entered by you", not_in_document: "Marked not in document", candidate: "Candidate chosen" } as Record<string, string>,
  decidedAt: (d: string) => `decided ${d}`,
  undo: "Change decision",
  candidates: "Candidates found in the document; each keeps AMBIGUOUS unless its quote verifies on the page:",
  candidateName: (field: string) => `Candidates for ${field}`,
  candidateOption: (value: string, page: number) => `${value}, page ${page}`,
  newValue: "New value",
  valueDollars: "Dollars",
  valuePercent: "Percent the plan pays",
  valueMonths: "Months",
  valueMonth: "Month",
  valueText: "Value as written in your source",
  valueBool: { yes: "Yes", no: "No" },
  valueClass: "Coverage class",
  valueList: "Value (JSON, as the extractor would write it)",
  sourceLabel: "Source",
  sourceHint: "Where this value comes from (another document, a statement, a call), kept with the value.",
  sourceRequired: "A source is required for an entered value.",
  invalidValue: "This value does not fit the field's unit.",
  unknownClass: "The class must be one of the document's classes.",
  enterValue: "Enter this value",
  cancelEdit: "Cancel",
  required: "required",
  requiredGroup: "at least one coverage class row",
  confirmAllVerified: "Confirm all verified quotes",
  confirmAllNote: (n: number) => `${n} row${n === 1 ? "" : "s"} with a quote verified on the cited page and no decision yet.`,
  waitingCount: (n: number) => (n === 1 ? "1 required field is waiting for a decision." : `${n} required fields are waiting for a decision.`),
  allDecided: "Every required field has a decision.",
  undecidedList: (list: string) => `Waiting: ${list}`,
  publish: "Publish this plan version",
  publishHold: "Hold to publish",
  publishing: "Publishing…",
  published: (label: string) => `Published as ${label}`,
  publishedBody: (label: string) => `${label} is now a plan version in your space. The plan picker lists it; estimates calculated with it carry the ${label} label.`,
  publishUndecided: (list: string) => `The server lists required rows without a decision: ${list}.`,
  publishInvalid: (type: string) => `The engine rejected the built plan (${type}). Decisions can be changed and the version published again.`,
  publishFailed: "The plan version could not be published.",
  reviewFailed: "The decision could not be recorded.",
  ignoredWordingTitle: "Text in the document that was not used as a rule",
  unmatchedWordingTitle: "Wording that matched none of the 16 procedure identifiers",
  wordingPage: (p: number) => `page ${p}`,
  notesTitle: "Notes from extraction",
  notesDropped: (n: number) => `${n} note${n === 1 ? "" : "s"} removed by the information-only check.`,
  valueUnlimited: "no annual maximum",
  valueNone: "nothing proposed",
  monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  months: (n: number) => `${n} month${n === 1 ? "" : "s"}`,
  percent: (bp: number) => `${(bp / 100).toLocaleString("en-US", { maximumFractionDigits: 2 })}%`,
  frequencyValue: (n: number, clock: string) => `${n} per ${clock.replace(/_/g, " ")}`,
  // demo-mode / fictional ribbons
  fictional: "Fictional demonstration plan",
  demoFixtureMatch: "This document's checksum matches a stored fixture.",
} as const satisfies Record<string, string | string[] | Record<string, string> | ((...a: never[]) => string)>;

/** Reminders panel + push subscription client (components/notifications/RemindersPanel.tsx). Information only; nothing urges. */
export const REMINDERS = {
  title: "Reminders",
  intro: "Dates and figures from your plan document and your records, each with its source.",
  loading: "Reading your reminders…",
  empty: "No reminders are listed for your records.",
  asOf: (d: string) => `As of ${d}`,
  cite: (doc: string, page: number) => `${doc} p.${page}`,
  source: (s: string) => `Source: ${s}`,
  kind: { benefit_year_end: "Benefit year", frequency_next_eligible: "Frequency interval", frequency_count_reset: "Frequency count", document_awaiting_decision: "Document" } as Record<string, string>,
  noDate: "no date",
  failed: "Reminders could not be loaded.",
  pushTitle: "Push reminders on this device",
  pushBody: "A push message carries no figures and no names. It is a fixed sentence saying that a date you chose to follow is approaching.",
  subscribe: "Turn on push reminders",
  unsubscribe: "Turn off push reminders",
  subscribed: "Push reminders are on for this browser.",
  notSubscribed: "Push reminders are off for this browser.",
  working: "Updating the subscription…",
  unsupported: "This browser does not support push messages.",
  noKey: "Push is not configured on this server (no VAPID public key).",
  denied: "Notification permission was declined in this browser.",
  insecure: "Push needs a secure page (https or localhost).",
  subscribeFailed: "The subscription could not be stored.",
  testPush: "Send a test push",
  testSent: (sent: number, failed: number) => `Test push: ${sent} sent, ${failed} failed.`,
  testUnavailable: "Push is not configured on this server (no VAPID private key).",
  devOnly: "Dev auth is on for this server; the test push is a development control.",
} as const satisfies Record<string, string | Record<string, string> | ((...a: never[]) => string)>;
