#!/usr/bin/env python3
"""Repeatable ingestion: sources/extracted/*.json  →  fixtures/sources.json (source inventory),
fixtures/evidence/<source_id>.json (normalized facts), fixtures/procedure_codes.json (explicit external-code mappings for the
16 fixed internal procedure keys), fixtures/fee_benchmarks.json (published fee rows, labeled by payer/geography/date/purpose),
and the REAL plan presets (fixtures/plans/{ml26,ml26h,ml26l,dd24,dd24l,fm26h,fm26s,fd26h,fd26s}.json).

Rules (see sources/RESEARCH_PROTOCOL.md):
- every preset field is pulled from a fact record by fact_id; quotes and pages are never retyped here;
- unknown stays UNKNOWN (value null); ambiguous stays AMBIGUOUS; conflicts are preserved, never resolved by picking;
- fictional demonstration plans (hb26, sm26, nw26, tw26) are generated by tools/build_fictional_plans.py and are NOT touched;
- the output is validated: loader round-trip, class/procedure key integrity, frequency clocks, statuses, duplicate fact ids.

Run:  python3 tools/ingest_sources.py            (writes fixtures and prints the import report)
      python3 tools/ingest_sources.py --check    (validates only; non-zero exit on problems)
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "sources" / "extracted"
FIX = ROOT / "fixtures"
sys.path.insert(0, str(ROOT / "engine"))
from oralcompass_engine import load_plan  # noqa: E402
from oralcompass_engine.rules import coverage_rules  # noqa: E402

RETRIEVED = "2026-10-03"
PROCEDURE_KEYS = [p["key"] for p in json.loads((FIX / "procedures.json").read_text())["items"]]
VALID_STATUS = {"DOC", "USER", "ASSUMED", "AMBIGUOUS", "UNKNOWN", "CONFLICT"}
VALID_CLOCKS = {"calendar_count", "interval_months", "rolling12_count", "per_tooth_months", "per_quadrant_months", "lifetime"}

# document version labels (scope tags for stitches) per source_id
LABELS = {
    "ncflex-2026-plan-details": "ML26", "ncflex-metlife-classic-certificate-2020": "ML20c", "ncflex-metlife-high-certificate-2018": "ML18h",
    "ncflex-metlife-low-certificate-2020": "ML20l", "delta-msu-eoc-2024": "DD24", "msu-dental-benefit-highlights-2021": "MSU20h",
    "opm-fedvip-metlife-2026": "FM26", "opm-fedvip-delta-2026": "FD26", "delta-dental-nc-individual-2026": "DN26",
    "nc-medicaid-dental-fees": "NCMED26", "ada-cdt-license-terms": "ADACDT", "cdt-procedure-mapping": "CDTMAP",
}

SOURCES: dict[str, dict] = {}
FACTS: dict[str, dict] = {}          # fact_id -> fact (+ source_id)
PROBLEMS: list[str] = []


def load_sources():
    for p in sorted(SRC.glob("*.json")):
        j = json.loads(p.read_text())
        sid = j["source_id"]
        SOURCES[sid] = j
        for f in j.get("facts", []):
            fid = f.get("fact_id")
            if not fid:
                PROBLEMS.append(f"{sid}: fact without fact_id: {str(f)[:80]}"); continue
            if fid in FACTS:
                PROBLEMS.append(f"duplicate fact_id {fid} ({sid} and {FACTS[fid]['_source']})"); continue
            FACTS[fid] = {**f, "_source": sid}


def fact(fid: str) -> dict:
    if fid not in FACTS:
        raise KeyError(f"missing fact {fid}")
    return FACTS[fid]


def fact_opt(fid: str):
    return FACTS.get(fid)


def page_int(page) -> int:
    """First integer in a page field ('sch 47' → 47, '24-26' → 24, 'unknown' → 0). 0 means 'page not determinable from the text'."""
    if page is None:
        return 0
    if isinstance(page, int):
        return page
    m = re.search(r"\d+", str(page))
    return int(m.group()) if m else 0


def page_label(f: dict) -> str:
    sec = str(f.get("section") or "")
    p = f.get("page")
    part = ""
    for name in ("Attachment A", "Attachment B"):
        if sec.startswith(name):
            part = name + " "
    if p is None or str(p).lower().startswith("unknown") or str(p).lower() == "none":
        return "page not determinable from the text extraction"
    return f"{part}p.{p}"


def cite(fid: str, doc_label: str | None = None) -> dict:
    f = fact(fid)
    if not f.get("quote"):
        raise ValueError(f"fact {fid} has no quote — cannot cite")
    return {"doc": doc_label or LABELS[f["_source"]], "page": page_int(f.get("page")), "page_note": page_label(f), "quote": f["quote"],
            "section": f.get("section"), "fact_id": fid, "review_status": f.get("review_status")}


def V(fid: str, value=None, status: str | None = None, note: str = "", doc_label: str | None = None, use_fact_value=True) -> dict:
    f = fact(fid)
    st = status or f.get("status", "DOC")
    out = {"value": (f.get("value") if (value is None and use_fact_value) else value), "status": st, "note": note or (f.get("notes") or "")[:400]}
    if f.get("quote"):
        out["cite"] = cite(fid, doc_label)
    if st == "UNKNOWN":
        out["value"] = None
    return out


def unknown(note: str, fid: str | None = None) -> dict:
    out = {"value": None, "status": "UNKNOWN", "note": note}
    if fid:
        out["fact_id"] = fid
    return out


def pct_to_bp_plan_pays(f: dict) -> int:
    """Convert a coinsurance fact to basis points the PLAN pays. Facts record the basis explicitly (unit)."""
    unit = f.get("unit")
    if unit == "percent_plan_pays":
        return int(f["value"]) * 100
    if unit == "percent_you_pay":
        return (100 - int(f["value"])) * 100
    raise ValueError(f"coinsurance fact {f['fact_id']} has unit {unit!r}")


def coins(fid: str, extra_note: str = "") -> dict:
    f = fact(fid)
    bp = pct_to_bp_plan_pays(f)
    note = ("document states what YOU pay; plan share = 100% − that. " if f.get("unit") == "percent_you_pay" else "") + extra_note
    return {"value": bp, "status": f.get("status", "DOC"), "cite": cite(fid), "note": note.strip(), "basis": f.get("basis")}


def source_document(sid: str, extra: dict | None = None) -> dict:
    s = SOURCES[sid]
    out = {"title": s["title"], "publisher": s["publisher"], "url": s["url"], "secondary_urls": s.get("secondary_urls", []),
           "document_type": s.get("document_type"), "document_date": s.get("document_date"), "effective_period": s.get("effective_period"),
           "retrieved_at": s.get("retrieved_at", RETRIEVED), "retrieval_method": s.get("retrieval_method"), "pages": s.get("pages_total"),
           "sha256": "", "sha256_note": "The egress policy of the build environment blocks binary downloads from this host; the document was read "
                                        "through the sanctioned text-extraction fetch. Record the SHA-256 and re-verify each quote on its PDF page "
                                        "when the PDF is downloaded (tools/seed_presets.py).",
           "version_label": LABELS[sid], "reuse_terms": s.get("reuse_terms"), "access_limits": s.get("access_limits", []), "source_id": sid,
           "path": None}
    if extra:
        out.update(extra)
    return out


def secondary(sid: str) -> dict:
    s = SOURCES[sid]
    return {"version_label": LABELS[sid], "title": s["title"], "url": s["url"], "document_date": s.get("document_date"),
            "document_type": s.get("document_type"), "source_id": sid, "access_limits": s.get("access_limits", [])}


def unsupported(fid: str, reason: str) -> dict:
    f = fact(fid)
    return {"quote": f.get("quote"), "page": page_int(f.get("page")), "page_note": page_label(f), "doc": LABELS[f["_source"]], "reason": reason, "fact_id": fid}


def conflicts_of(*sids: str) -> list[dict]:
    out = []
    for sid in sids:
        for c in SOURCES[sid].get("conflicts", []):
            out.append({**c, "source_id": sid})
    return out


# --------------------------------------------------------------------------------------------------------------------------
# ML26 family — NCFlex (State of North Carolina) dental plan insured by MetLife, plan year 2026: Classic / High / Low options
# --------------------------------------------------------------------------------------------------------------------------
def build_ml26(option: str) -> dict:
    g = "ncflex-2026-plan-details"
    cert = {"Classic": "ncflex-metlife-classic-certificate-2020", "High": "ncflex-metlife-high-certificate-2018", "Low": "ncflex-metlife-low-certificate-2020"}[option]
    code = {"Classic": "ML26", "High": "ML26H", "Low": "ML26L"}[option]
    cert_label = LABELS[cert]
    t1, t2, t2b, t3 = (f"{g}:coinsurance_type1:{option}", f"{g}:coinsurance_type2_basic:{option}", f"{g}:coinsurance_type2_perio_surgery:{option}", f"{g}:coinsurance_type3:{option}")
    type1_after_deductible = option == "Low"

    classes = [
        {"name": "Type I", "plan_share_bp_in": coins(t1), "plan_share_bp_out": coins(t1, "same percentage out-of-network, applied to the reasonable and customary (R&C) charge"),
         "procedures_text": ["Oral Examination", "Cleaning", "X-rays", "Topical Fluoride", "Sealants for Permanent First and Second Molars"],
         "cite": cite(f"{g}:class_membership:exam")},
        {"name": "Type II", "plan_share_bp_in": coins(t2), "plan_share_bp_out": coins(t2, "same percentage out-of-network, applied to the R&C charge"),
         "procedures_text": ["Fillings (amalgam, synthetic, or composite)", "Simple Extractions", "Endodontics (root canal treatment)", "Re-Cement Crowns, Inlays, Bridges"],
         "cite": cite(f"{g}:class_membership:composite")},
        {"name": "Type II (50% row)", "plan_share_bp_in": coins(t2b), "plan_share_bp_out": coins(t2b, "same percentage out-of-network, applied to the R&C charge"),
         "procedures_text": ["Periodontal Services (gingivectomy, gingivoplasty, osseous surgery, scaling, and root planing)", "Periodontal Maintenance after Therapy", "Oral Surgery (wisdom teeth extractions)", "General Anesthesia"],
         "cite": cite(f"{g}:class_membership:scaling_root_planing"),
         "note": "The guide prints this row under 'Type II — Basic Services' at 50% for every option, which equals the certificates' Type C percentage rather than Type B. The label is preserved as printed; the class membership of the procedures in this row is AMBIGUOUS (see conflicts)."},
    ]
    excluded = {"night_guard": V(f"{g}:exclusion:night_guard", value=True, note="Exclusions list: 'Appliances or treatment for bruxism (grinding teeth).' The page says the list is partial and the certificate governs.")}
    if fact(t3)["value"] is not None:
        classes.append({"name": "Type III", "plan_share_bp_in": coins(t3), "plan_share_bp_out": coins(t3, "same percentage out-of-network, applied to the R&C charge"),
                        "procedures_text": ["Crowns, including Single Implant Crowns", "Dentures", "Bridges", "Implants"], "cite": cite(f"{g}:class_membership:crown")})
    else:  # Low Option: Type III — Major Services is 'Not Covered'
        for k in ("crown", "cast_crown", "denture_partial", "implant"):
            excluded[k] = V(t3, value=True, status="DOC", note="Type III — Major Services are 'Not Covered' under the Low Option (table cell 'Not Covered').")

    def cls(key: str, name: str, status: str | None = None, note: str = ""):
        return V(f"{g}:class_membership:{key}", value=name, status=status, note=note)

    class_of = {
        "exam": cls("exam", "Type I"), "cleaning": cls("cleaning", "Type I"), "bitewing_xrays": cls("bitewing_xrays", "Type I"),
        "fluoride_child": cls("fluoride_child", "Type I"), "sealant": cls("sealant", "Type I"),
        "composite": cls("composite", "Type II"), "amalgam": cls("amalgam", "Type II"), "extraction_simple": cls("extraction_simple", "Type II"),
        "root_canal_molar": cls("root_canal_molar", "Type II", note="'Endodontics (root canal treatment)' is listed in the Type II first row; no molar/anterior distinction is printed."),
        "scaling_root_planing": cls("scaling_root_planing", "Type II (50% row)", status="AMBIGUOUS",
                                    note="printed under 'Type II' but at the 50% row, which equals the certificate's Type C percentage; computed at 50%"),
        "extraction_surgical": cls("extraction_surgical", "Type II (50% row)", status="AMBIGUOUS",
                                   note="the guide names only 'Oral Surgery (wisdom teeth extractions)' in the 50% row; a surgical extraction of another tooth could fall under 'Simple Extractions' — not stated; computed at 50%"),
    }
    if fact(t3)["value"] is not None:
        class_of.update({"crown": cls("crown", "Type III"), "cast_crown": cls("cast_crown", "Type III", note="the guide's single 'Crowns' line covers all crown materials"),
                         "denture_partial": cls("denture_partial", "Type III", note="'Dentures' — partial vs complete not distinguished"),
                         "implant": cls("implant", "Type III", note="deductible applicability to implants conflicts between the guide and the 2020 certificate (see conflicts)")})

    frequency = [
        {"procedure_key": "exam", "clock": "calendar_count", "n": 2, "cite": cite(f"{g}:frequency:exam"), "period_as_printed": "two per calendar year"},
        {"procedure_key": "cleaning", "clock": "calendar_count", "n": 2, "cite": cite(f"{g}:frequency:cleaning"), "period_as_printed": "two per calendar year"},
        {"procedure_key": "bitewing_xrays", "clock": "calendar_count", "n": 1, "cite": cite(f"{g}:frequency:bitewing_xrays"), "period_as_printed": "one per calendar year"},
        {"procedure_key": "fluoride_child", "clock": "calendar_count", "n": 2, "cite": cite(f"{g}:frequency:fluoride_child"), "period_as_printed": "two per calendar year under age 19"},
    ]
    if fact(t3)["value"] is not None:
        frequency += [
            {"procedure_key": "crown", "clock": "per_tooth_months", "n": 84, "cite": cite(f"{g}:frequency:crown"), "period_as_printed": "replacements limited to every seven years",
             "note": "replacement rule; per-tooth basis not stated in the guide — not enforced in the arithmetic, shown as a rule"},
            {"procedure_key": "denture_partial", "clock": "interval_months", "n": 84, "cite": cite(f"{g}:frequency:denture_partial"), "period_as_printed": "replacements limited to every seven years"},
        ]

    premium = {}
    for tier, fid_part in (("employee_only", "premium_monthly_employee_only"), ("employee_spouse", "premium_monthly_employee_spouse"),
                           ("employee_children", "premium_monthly_employee_children"), ("family", "premium_monthly_family")):
        premium[tier] = V(f"{g}:{fid_part}:{option}", note=f"{option} Option, '{tier.replace('_', ' ')}' tier, Monthly Cost table (columns High | Classic | Low)")

    oon = fact(f"{g}:oon_basis:n/a"); bb = fact(f"{g}:balance_billing:n/a"); cert_oon = fact(f"{cert}:oon_basis:{option}")
    plan = {
        "plan_code": code,
        "title": f"MetLife NCFlex Dental — {option} Option, plan year 2026 (State of North Carolina)",
        "carrier_text": "Metropolitan Life Insurance Company (MetLife)",
        "is_fictional": False,
        "catalog": {
            "carrier": "Metropolitan Life Insurance Company (MetLife)", "plan_name": "NCFlex Dental Plan (State of North Carolina)", "option": f"{option} Option",
            "plan_year": 2026, "benefit_year_type": "calendar", "region": "North Carolina",
            "network": {"text": fact(f"{g}:network:n/a")["value"], "cite": cite(f"{g}:network:n/a")},
            "effective_dates": {"start": "2026-01-01", "end": "2026-12-31",
                                "text": "Plan year 2026 (the dental pages do not print the year; it rests on the guide cover 'Benefits Guide 2026' and the enrollment rule that elections begin January 1 of the following year).",
                                "cite": cite(f"{g}:effective_dates:n/a"), "basis_note": SOURCES[g]["effective_period"].get("quote_note")},
            "where_offered": {"text": "North Carolina — NCFlex (state agencies, universities, participating community colleges and charter schools)", "cite": cite(f"{g}:eligibility:n/a")},
            "eligibility": {"text": fact(f"{g}:eligibility:n/a")["value"] + ". Listed here means the document is public — not that you are eligible to enroll.", "cite": cite(f"{g}:eligibility:n/a")},
            "governing_document": {"text": "The guide states the certificate/contract governs over the guide.", "cite": cite(f"{g}:governing_document:n/a")},
            "verification": {"date": RETRIEVED, "method": SOURCES[g].get("retrieval_method"),
                             "note": "Primary document: 2026 NCFlex Dental Plan Details (3 pages, verified in three passes). Certificates: 2020/2018 editions reachable only to about page 50; "
                                     "covered-service lists, alternate-benefit, waiting-period, missing-tooth and exclusions clauses were NOT reachable and remain UNKNOWN."},
        },
        "source_document": source_document(g, {"primary_pages": "24-26 of 'Benefits Guide 2026' (footer www.ncflex.org 24/25/26)"}),
        "secondary_documents": [secondary(cert)],
        "benefit_year_start_month": V(f"{cert}:benefit_year:{option}", value=1, note="certificate definition of 'Year' (same group policy 165756-1-G); the guide's tables are labeled 'Calendar-Year'"),
        "deductible_individual": V(f"{g}:deductible_individual:{option}"),
        "deductible_family": V(f"{g}:deductible_family:{option}"),
        "deductible_waived_classes": [] if type1_after_deductible else ["Type I"],
        "deductible_waiver_note": ("Under the Low Option the Type I cell reads '100% after deductible', so the deductible applies to Type I." if type1_after_deductible else
                                   "The Type I cell reads '100%' with no 'after deductible' wording; Type II and Type III cells read 'after deductible'."),
        "annual_max": V(f"{g}:annual_max:{option}"),
        "classes": classes,
        "class_of": class_of,
        "allowed_amounts": {},
        "allowed_amounts_note": "No fee schedule or negotiated fee is printed in the guide or the certificates. In-network: 'The MAC for in-network dental providers is the negotiated in-network fee.' The allowed amount must come from your pre-treatment estimate, EOB or dentist (USER).",
        "alternate_benefit": {"status": "UNKNOWN", "conditions": [], "note": "The certificate's Alternate Benefits clause (DENTAL INSURANCE section, p.59–62) was not reachable; the guide does not print one. Absence is not confirmed.",
                              "fact_id": f"{cert}:alternate_benefit:Classic" if option == "Classic" else None},
        "waiting_months": unknown("Not mentioned on guide pages 24–26 or elsewhere in the 56-page guide; the certificate section that would contain a waiting period was not reachable. Absence not confirmed.", f"{g}:waiting_period:n/a"),
        "frequency": frequency,
        "excluded": excluded,
        "missing_tooth": {"present": None, "status": "UNKNOWN", "note": "Not in the guide (its exclusion list is 'a partial listing'); certificate exclusions (p.66–67) not reachable."},
        "oon_rule": {"value": {"in": fact(f"{g}:in_network_basis:n/a")["value"], "out": oon["value"] + ". " + bb["value"]},
                     "status": "DOC", "cite": cite(f"{g}:oon_basis:n/a"), "balance_billing_cite": cite(f"{g}:balance_billing:n/a"), "in_network_cite": cite(f"{g}:in_network_basis:n/a"),
                     "note": f"The guide states no percentile. The {option} certificate ({cert_label}, {SOURCES[cert].get('document_date')}) defines the customary charge as: '{cert_oon['quote']}'. "
                             "That certificate predates the 2026 plan year — recorded as a potential version conflict.", "certificate_cite": cite(f"{cert}:oon_basis:{option}", cert_label)},
        "dos_rule": V(f"{g}:dos_rule_prosthetics:n/a", value="completion", note="stated for single prosthetic procedures (crowns): 'considered completed on the date they are inserted, not the date of impression'; application to other services is not explicit"),
        "premium_monthly": premium,
        "unsupported_rules": [
            unsupported(f"{g}:coinsurance_type4_ortho:Classic", "orthodontia (Type IV) — not modeled"),
            unsupported(f"{g}:frequency:fillings_replacement", "replacement-of-filling rule (once every 24 months) — applies to replacements only; shown as a limitation, not enforced"),
            unsupported(f"{g}:age_limit:crown", "age condition for crowns — age is not collected"),
            unsupported(f"{g}:age_limit:sealant", "sealant age/tooth condition — age is not collected; frequency 'see certificate' (not reached)"),
            unsupported(f"{g}:age_limit:fluoride_child", "fluoride age condition — age is not collected"),
            unsupported(f"{g}:pretreatment_estimate:n/a", "pre-estimate encouraged when a service is expected to cost $300 or more — informational"),
            unsupported(f"{g}:frequency:perio_maintenance", "periodontal maintenance count — not an internal procedure; may interact with cleaning counts (not stated)"),
        ],
        "conflicts": conflicts_of(g, cert),
        "procedure_codes": {},
        "procedure_codes_note": "No CDT codes are printed in the guide or the reachable certificate pages.",
    }
    if option == "Classic":
        plan["unsupported_rules"].append(unsupported(f"{cert}:deductible_waived:implant", "certificate (2020): deductible excludes implants and implant services — conflicts with the guide's Type III row 'after deductible'; implants computed WITH the deductible per the 2026 guide, conflict shown"))
    return plan


# --------------------------------------------------------------------------------------------------------------------------
# DD24 family — Delta Dental PPO, Mississippi State University (Group 01125), EOC effective 2024-01-01: High Plan / Low Plan
# --------------------------------------------------------------------------------------------------------------------------
def build_dd24(option: str) -> dict:
    e = "delta-msu-eoc-2024"; h = "msu-dental-benefit-highlights-2021"
    code = {"High": "DD24", "Low": "DD24L"}[option]
    opt_l = option.lower()
    cls_fid = lambda k: f"{e}:class_membership:n/a:{k}"

    classes = [
        {"name": "Diagnostic and Preventive Services", "plan_share_bp_in": coins(f"{e}:coinsurance:{option}:diagnostic_preventive"),
         "plan_share_bp_out": coins(f"{e}:coinsurance:{option}:diagnostic_preventive", "same percentage for Premier and Non-Delta Dental dentists (columns 2 and 4); paid on the Program Allowance for Non-Delta dentists"),
         "procedures_text": ["Diagnostic (oral examinations)", "Preventive: cleaning, topical application of fluoride solutions, space maintainers"], "cite": cite(cls_fid("cleaning"))},
        {"name": "Basic Services", "plan_share_bp_in": coins(f"{e}:coinsurance:{option}:basic"), "plan_share_bp_out": coins(f"{e}:coinsurance:{option}:basic", "same percentage for Premier and Non-Delta Dental dentists"),
         "procedures_text": ["Oral Surgery: extractions and other surgical procedures", "Restorative: amalgam and resin-based composite restorations (fillings) and prefabricated crowns", "Sealants", "Palliative", "Denture Repairs"], "cite": cite(cls_fid("composite"))},
        {"name": "Major Services", "plan_share_bp_in": coins(f"{e}:coinsurance:{option}:major"), "plan_share_bp_out": coins(f"{e}:coinsurance:{option}:major", "same percentage for Premier and Non-Delta Dental dentists"),
         "procedures_text": ["Crowns and Inlays/Onlays", "Prosthodontics", "Endodontics", "Periodontics"], "cite": cite(cls_fid("crown"))},
    ]
    class_of = {
        "exam": V(cls_fid("exam"), value="Diagnostic and Preventive Services"), "cleaning": V(cls_fid("cleaning"), value="Diagnostic and Preventive Services"),
        "fluoride_child": V(cls_fid("fluoride_child"), value="Diagnostic and Preventive Services"),
        "bitewing_xrays": {"value": "Diagnostic and Preventive Services", "status": "AMBIGUOUS", "cite": cite(f"{e}:frequency:n/a:bitewing_xrays"),
                           "note": "The 'Diagnostic' category description does not name x-rays; the only x-ray text is Limitation 3 (x-ray limitations). Diagnostic is the only plausible home — computed as such and labeled AMBIGUOUS.",
                           "fact_id": cls_fid("bitewing_xrays")},
        "sealant": V(cls_fid("sealant"), value="Basic Services", note="Sealants are a BASIC service in this EOC (not Diagnostic & Preventive)."),
        "extraction_simple": V(cls_fid("extraction"), value="Basic Services"), "extraction_surgical": V(cls_fid("extraction_surgical"), value="Basic Services"),
        "composite": V(cls_fid("composite"), value="Basic Services"), "amalgam": V(cls_fid("amalgam"), value="Basic Services"),
        "root_canal_molar": V(cls_fid("root_canal_molar"), value="Major Services"), "scaling_root_planing": V(cls_fid("scaling_root_planing"), value="Major Services"),
        "crown": V(cls_fid("crown"), value="Major Services"), "cast_crown": V(cls_fid("cast_crown"), value="Major Services"), "denture_partial": V(cls_fid("denture_partial"), value="Major Services"),
    }
    waiting = {"value": {"composite": 12, "amalgam": 12, "root_canal_molar": 12, "scaling_root_planing": 12, "denture_partial": 12, "crown": 12, "cast_crown": 12},
               "status": "AMBIGUOUS", "cite": cite(f"{e}:waiting_period:n/a:restorative_endo_perio_prostho"),
               "note": "The 12-month wait names 'Restorative, Endodontics, Periodontics, and Prosthodontics' — procedure groups, not classes. Applied to fillings (Restorative), root canals (Endodontics), "
                       "scaling and root planing (Periodontics) and partial dentures (Prosthodontics). 'Crowns and Inlays/Onlays' is a separate Major item not named in the sentence — applied here as 12 months and flagged AMBIGUOUS. "
                       "Oral Surgery (extractions), Sealants, Palliative care and Denture Repairs are not named — no wait applied.",
               "ambiguous_fact_id": f"{e}:waiting_period:n/a:crown"}
    frequency = [
        {"procedure_key": "exam", "clock": "calendar_count", "n": 2, "cite": cite(f"{e}:frequency:n/a:exam"), "period_as_printed": "no more than twice in a Calendar Year"},
        {"procedure_key": "cleaning", "clock": "calendar_count", "n": 2, "cite": cite(f"{e}:frequency:n/a:cleaning"), "period_as_printed": "no more than twice in a Calendar Year"},
        {"procedure_key": "bitewing_xrays", "clock": "calendar_count", "n": 1, "cite": cite(f"{e}:frequency:n/a:bitewing_xrays"), "period_as_printed": "one (1) time each Calendar Year for Enrollees age 18 and over (twice under age 18)",
         "note": "computed with the age-18-and-over limit; age is not collected"},
        {"procedure_key": "fluoride_child", "clock": "calendar_count", "n": 2, "cite": cite(f"{e}:age_limit:n/a:fluoride_child"), "period_as_printed": "no more than twice in a Calendar Year; Enrollees to age 19"},
        {"procedure_key": "scaling_root_planing", "clock": "per_quadrant_months", "n": 24, "cite": cite(f"{e}:frequency:n/a:scaling_root_planing"), "period_as_printed": "once in every 24-month period (same quadrant)",
         "note": "per quadrant — not enforced in the arithmetic (quadrant history is not collected); shown as a rule"},
        {"procedure_key": "crown", "clock": "per_tooth_months", "n": 60, "cite": cite(f"{e}:frequency:n/a:crown"), "period_as_printed": "not more often than once in any 60 month period (age 12 and older)",
         "note": "per tooth — not enforced in the arithmetic; shown as a rule"},
        {"procedure_key": "denture_partial", "clock": "interval_months", "n": 60, "cite": cite(f"{e}:frequency:n/a:denture_partial"), "period_as_printed": "replaced only after 60 months have passed"},
    ]
    excluded = {
        "implant": V(f"{e}:exclusion:n/a:implant_limitation", value=True, note="Limitation 33 (Attachment B p.6): 'We will not pay for implants…'; a credit toward a pontic or standard denture is described. Exclusion 34 (p.7) also excludes implant services."),
        "night_guard": V(f"{e}:exclusion:n/a:night_guard", value=True, note="Exclusion 6: '… Night Guards/Occlusal guards …' are listed as examples of excluded treatment."),
    }
    prem_fid = f"{h}:premium_monthly:{option}:enrollee_only"
    premium = {"employee_only": {**V(prem_fid, status="AMBIGUOUS"), "note": "Printed on the Benefit Highlights sheet revised 8/26/2020 (file dated 2021). No plan year is printed on the sheet; the rate may not apply to 2024–2026. Shown with its document date, not as a current premium."},
               "employee_plus_dependents": {**V(f"{h}:premium_monthly:{option}:enrollee_plus_dependents", status="AMBIGUOUS"), "note": "same sheet; 'Enrollee + 1 or more dependents' tier"}}

    plan = {
        "plan_code": code,
        "title": f"Delta Dental PPO — {option} Plan, Mississippi State University (Group 01125), EOC effective 1/1/2024",
        "carrier_text": "Delta Dental Insurance Company",
        "is_fictional": False,
        "catalog": {
            "carrier": "Delta Dental Insurance Company", "plan_name": "Delta Dental PPO (Evidence of Coverage form PPO-ENT-MS-E-R23)", "option": f"{option} Plan", "plan_year": 2024,
            "benefit_year_type": "calendar", "region": "Mississippi", "network": "Delta Dental PPO / Delta Dental Premier / Non-Delta Dental Dentists",
            "effective_dates": {"start": "2024-01-01", "end": None, "text": "Effective Date: January 1, 2024 (no end date printed). The MSU HR dental page (last modified 2026-05-04) still links this EOC; no 2025/2026 EOC was found.",
                                "cite": cite(f"{e}:effective_dates:n/a")},
            "where_offered": {"text": "Group plan for Mississippi State University (Group 01125) — Mississippi", "cite": cite(f"{e}:eligibility:n/a:public_document")},
            "eligibility": {"text": "MSU benefits-eligible employees and their dependents enrolled under the Contract. Listed here means the document is public — not that you are eligible to enroll.", "cite": cite(f"{e}:eligibility:n/a:dependent_age")},
            "currency_note": "Possibly outdated for 2026: the latest public EOC is effective 2024-01-01; premiums come from a 2020-revision highlights sheet.",
            "verification": {"date": RETRIEVED, "method": SOURCES[e].get("retrieval_method"),
                             "note": "Page numbers are the footer page numbers printed in each PART of the EOC (main document / Attachment A / Attachment B); physical PDF indexes could not be read. "
                                     "Three attributions carry ±1 uncertainty (needs_review in the cite)."},
        },
        "source_document": source_document(e, {"parts": ["main document (footer PPO-ENT-MS-E-R23 n 01125)", "Attachment A (footer E-PPO-A-DM2LH2, benefit summary)", "Attachment B (footer ENT-LE-MS-22, services/limitations/exclusions)"]}),
        "secondary_documents": [secondary(h)],
        "benefit_year_start_month": V(f"{e}:benefit_year:n/a", value=1),
        "deductible_individual": V(f"{e}:deductible_individual:{option}"),
        "deductible_family": V(f"{e}:deductible_family:{option}"),
        "deductible_waived_classes": ["Diagnostic and Preventive Services"],
        "deductible_waiver_cite": cite(f"{e}:deductible_waived_classes:{option}"),
        "deductible_waiver_note": ("'Deductibles waived for Diagnostic & Preventive and Orthodontic Services' (orthodontics not modeled)." if option == "High" else
                                   "Low Plan cell most plausibly reads 'Diagnostic & Preventive Services' (cells concatenated in extraction) — AMBIGUOUS whether orthodontics is also named; orthodontics is 'Not Covered' under the Low Plan anyway."),
        "annual_max": V(f"{e}:annual_max:{option}"),
        "classes": classes,
        "class_of": class_of,
        "allowed_amounts": {},
        "allowed_amounts_note": "No fee schedule or dollar allowances anywhere in the EOC ('Maximum Contract Allowance' is defined but not listed). Payment is 'the lesser of the Dentist's Submitted Fee or the Maximum Allowance'.",
        "alternate_benefit": {"status": "DOC", "cite": cite(f"{e}:alternate_benefit:n/a:optional_services"), "rule_cite": cite(f"{e}:alternate_benefit:n/a:rule_sentence"),
                              "conditions": [{"procedure_key": "crown", "condition": "upper_second_third_or_lower_molar", "basis_key": None,
                                              "text": "porcelain, resin or similar materials for crowns placed on a maxillary second or third molar, or on any mandibular molar (an allowance will be made for a porcelain fused to high noble metal crown)"}],
                              "note": "The alternate allowance (porcelain fused to high noble metal crown) is not stated as a dollar amount; plan payment is an UPPER bound when the condition applies. No posterior-composite downgrade clause was found (Limitations 1–35 searched).",
                              "posterior_composite_fact_id": f"{e}:alternate_benefit:n/a:posterior_composite"},
        "waiting_months": waiting,
        "frequency": frequency,
        "excluded": excluded,
        "missing_tooth": {"present": None, "status": "UNKNOWN", "note": "No missing-tooth clause found in Attachment B Limitations 1–35 or Exclusions 1–34 (fetcher reported none); not asserted as absent."},
        "oon_rule": {"value": {"in": fact(f"{e}:oon_basis:n/a:ppo_accepts_allowance")["quote"], "out": fact(f"{e}:oon_basis:n/a:payment_basis")["quote"] + " " + fact(f"{e}:oon_basis:n/a:balance_billing")["quote"]},
                     "status": "DOC", "cite": cite(f"{e}:oon_basis:n/a:balance_billing"), "payment_basis_cite": cite(f"{e}:oon_basis:n/a:payment_basis"), "in_network_cite": cite(f"{e}:oon_basis:n/a:ppo_accepts_allowance"),
                     "footnote_cite": cite(f"{e}:oon_basis:n/a:attachment_a_footnote")},
        "dos_rule": {"value": "completion", "status": "UNKNOWN", "cite": cite(f"{e}:other:n/a:incurred_rule"),
                     "note": "The EOC's 'incurred' rule (crown 'at the time the tooth or teeth are prepared') sits under Continuation of Benefits and governs termination liability; the claim-payment date rule is not stated. Computed with the completion date and labeled as an assumption."},
        "premium_monthly": premium,
        "unsupported_rules": [
            unsupported(f"{e}:orthodontic_max:High", "orthodontic lifetime maximum — not modeled") if option == "High" else unsupported(f"{e}:coinsurance:Low:orthodontic", "orthodontics 'Not Covered' under the Low Plan — not modeled"),
            unsupported(f"{e}:other:n/a:pre_treatment_estimate", "pre-treatment estimates are described (not required; 'does not guarantee payment') — informational"),
            unsupported(f"{e}:frequency:n/a:filling_replacement", "replacement of a filling within 24 months by the same provider is not covered — replacement rule, not enforced"),
            unsupported(f"{e}:frequency:n/a:root_canal_retreatment", "root canal retreatment within 24 months by the same provider is part of the original procedure — not enforced"),
            unsupported(f"{e}:frequency:n/a:oral_surgery", "oral surgery services covered once in a lifetime — shown as printed; 'per tooth' is an inference the document does not make"),
            unsupported(f"{e}:age_limit:n/a:sealant", "sealant age/tooth condition (through age 15, permanent molars) — age is not collected"),
            unsupported(f"{e}:age_limit:n/a:crown", "crowns limited to Enrollees age 12 and older — age is not collected"),
            unsupported(f"{e}:frequency:n/a:full_mouth_xrays", "complete series / panoramic film once every 60 months — not an internal procedure"),
            unsupported(f"{e}:class_membership:n/a:periodontal_maintenance", "periodontal maintenance is a Major Benefit for payment purposes — not an internal procedure"),
            unsupported(f"{e}:deductible_takeover:n/a", "prior-plan deductible credit for the 2024 transition — not modeled"),
        ],
        "conflicts": conflicts_of(e, h),
        "procedure_codes": {},
        "procedure_codes_note": "The EOC prints no CDT codes (it defines 'Procedure Code' by reference to CDT).",
    }
    return plan


# --------------------------------------------------------------------------------------------------------------------------
# FEDVIP 2026 brochures (OPM) — MetLife Federal Dental Plan (FM26*) and Delta Dental Federal Employees Dental Program (FD26*)
# --------------------------------------------------------------------------------------------------------------------------
def _fedvip_classes(src: str, option: str, class_defs: list[tuple[str, str, str, list[str], str]]) -> list[dict]:
    out = []
    for name, fid_in, fid_out, procs, cite_fid in class_defs:
        out.append({"name": name, "plan_share_bp_in": coins(fid_in), "plan_share_bp_out": coins(fid_out, "out-of-network: you also pay any amount above the Plan Allowance billed by the provider"),
                    "procedures_text": procs, "cite": cite(cite_fid)})
    return out


def mapping_codes(src: str) -> dict:
    """procedure_codes block for a preset: only codes printed in THIS document (from its procedure_mappings)."""
    out = {}
    for m in SOURCES[src].get("procedure_mappings", []):
        if not m.get("external_code") or not m.get("quote"):
            continue
        k = m["internal_key"]
        if k in out:
            continue
        out[k] = {"code": m["external_code"], "descriptor_as_printed": m.get("descriptor_as_printed"), "review": bool(m.get("review")),
                  "confidence": m.get("confidence"), "notes": (m.get("notes") or "")[:300],
                  "cite": {"doc": LABELS[src], "page": page_int(m.get("page")), "page_note": f"p.{m.get('page')}", "quote": m["quote"]}}
    return out


def build_fm26(option: str) -> dict:
    s = "opm-fedvip-metlife-2026"
    code = {"High": "FM26H", "Standard": "FM26S"}[option]
    cd = lambda c: (f"{s}:coinsurance:{option}:{c}:in", f"{s}:coinsurance:{option}:{c}:out")
    classes = _fedvip_classes(s, option, [
        ("Class A Basic", *cd("classA"), ["Preventive and Diagnostic Services: oral evaluations, prophylaxis, bitewings, fluoride, sealants"], f"{s}:frequency:exam"),
        ("Class B Intermediate", *cd("classB"), ["Restorative (fillings)", "Extractions", "Periodontal scaling and root planing"], f"{s}:class_membership:extraction"),
        ("Class C Major", *cd("classC"), ["Crowns"], f"{s}:frequency:crown"),
    ])

    def cls_from(fid: str, name: str, note: str = ""):
        return {"value": name, "status": "DOC", "cite": cite(fid), "note": note or f"code line printed in the {name} table"}

    class_of = {
        "exam": cls_from(f"{s}:frequency:exam", "Class A Basic"), "cleaning": cls_from(f"{s}:frequency:cleaning", "Class A Basic"),
        "bitewing_xrays": cls_from(f"{s}:frequency:bitewing_xrays", "Class A Basic"), "fluoride_child": cls_from(f"{s}:frequency:fluoride_child", "Class A Basic"),
        "sealant": cls_from(f"{s}:frequency:sealant", "Class A Basic"),
        "composite": {"value": "Class B Intermediate", "status": "DOC", "cite": {"doc": LABELS[s], "page": 29, "page_note": "p.29 (one fetch placed the row on p.30)", "quote": "D2392 Resin-based composite - two surfaces, posterior"}, "note": "listed in the Class B Intermediate table"},
        "amalgam": {"value": "Class B Intermediate", "status": "DOC", "cite": {"doc": LABELS[s], "page": 29, "page_note": "p.29 (one fetch placed the row on p.30)", "quote": "D2150 Amalgam - two surfaces, primary or permanent"}, "note": "listed in the Class B Intermediate table"},
        "extraction_simple": cls_from(f"{s}:class_membership:extraction", "Class B Intermediate", "D7140 and D7210 both listed in Class B"),
        "extraction_surgical": cls_from(f"{s}:class_membership:extraction", "Class B Intermediate", "D7210 listed in Class B; impacted-tooth codes may differ"),
        "scaling_root_planing": cls_from(f"{s}:frequency:scaling_root_planing", "Class B Intermediate"),
        "crown": cls_from(f"{s}:frequency:crown", "Class C Major"), "cast_crown": cls_from(f"{s}:frequency:cast_crown", "Class C Major"),
        "root_canal_molar": unknown("D3330 (molar root canal) was not present in the readable text (truncated near p.33); class and coinsurance unknown.", f"{s}:frequency:root_canal_molar"),
        "denture_partial": unknown("D5211–D5214 not present in the readable text; class unknown.", f"{s}:frequency:denture_partial"),
        "implant": unknown("D6010 (implant body) not present in the readable text; only implant maintenance codes appeared in the 2026 changes list.", f"{s}:frequency:implant"),
        "night_guard": unknown("Occlusal guard appliance codes (D9944–D9946) not present in the readable text; only the 2026 frequency change (1 in 24 months) is known.", f"{s}:frequency:night_guard"),
    }
    frequency = [
        {"procedure_key": "exam", "clock": "rolling12_count", "n": 2, "cite": cite(f"{s}:frequency:exam"), "period_as_printed": "Limited to 2 every 12 months"},
        {"procedure_key": "cleaning", "clock": "rolling12_count", "n": 2, "cite": cite(f"{s}:frequency:cleaning"), "period_as_printed": "Limited to 2 in 12 months (High Option: a third cleaning with pregnancy or diabetes)"},
        {"procedure_key": "bitewing_xrays", "clock": "calendar_count", "n": 1, "cite": cite(f"{s}:frequency:bitewing_xrays"), "period_as_printed": "Adult - 1 set every calendar year"},
        {"procedure_key": "fluoride_child", "clock": "rolling12_count", "n": 2, "cite": cite(f"{s}:frequency:fluoride_child"), "period_as_printed": "Limited to 2 every 12 months for dependent children based on age limits"},
        {"procedure_key": "sealant", "clock": "per_tooth_months", "n": 36, "cite": cite(f"{s}:frequency:sealant"), "period_as_printed": "1 sealant per tooth every 36 months; unrestored permanent molars; less than age 19", "note": "per tooth — not enforced in the arithmetic"},
        {"procedure_key": "scaling_root_planing", "clock": "per_quadrant_months", "n": 24, "cite": cite(f"{s}:frequency:scaling_root_planing"), "period_as_printed": "Limited to 1 every 24 months (per quadrant)", "note": "per quadrant — not enforced in the arithmetic"},
        {"procedure_key": "crown", "clock": "per_tooth_months", "n": 60, "cite": cite(f"{s}:frequency:crown"), "period_as_printed": "Limited to 1 per tooth every 60 months", "note": "per tooth — not enforced in the arithmetic"},
        {"procedure_key": "cast_crown", "clock": "per_tooth_months", "n": 60, "cite": cite(f"{s}:frequency:cast_crown"), "period_as_printed": "Limited to 1 per tooth every 60 months", "note": "per tooth — not enforced in the arithmetic"},
    ]
    ded_in = f"{s}:deductible_individual:{option}"; ded_out = f"{s}:deductible_individual:{option}:out"
    amax = fact(f"{s}:annual_max:{option}")
    annual_max = V(f"{s}:annual_max:{option}")
    if amax["value"] is None:
        annual_max.update({"value": None, "unlimited": True, "note": "The table cell reads 'Unlimited' (in-network and out-of-network rows) — no dollar maximum."})
    plan = {
        "plan_code": code, "title": f"The MetLife Federal Dental Plan 2026 — {option} Option (FEDVIP, nationwide)", "carrier_text": "Metropolitan Life Insurance Company (MetLife)", "is_fictional": False,
        "catalog": {"carrier": "Metropolitan Life Insurance Company (MetLife)", "plan_name": "The MetLife Federal Dental Plan (FEDVIP brochure 02AP-11)", "option": f"{option} Option", "plan_year": 2026, "benefit_year_type": "calendar",
                    "region": "Nationwide and overseas (includes North Carolina); premiums vary by rating area", "network": "MetLife Dental PPO (In-Network / Out-of-Network, Plan Allowance basis)",
                    "effective_dates": {"start": "2026-01-01", "end": "2026-12-31", "text": "Plan year 2026", "cite": cite(f"{s}:effective_dates:n/a"), "benefit_period_cite": cite(f"{s}:benefit_period:n/a")},
                    "where_offered": {"text": SOURCES[s]["scope"]["geography"], "cite": cite(f"{s}:eligibility:n/a")},
                    "eligibility": {"text": fact(f"{s}:eligibility:n/a")["value"] + ". Listed here means the document is public — not that you are eligible to enroll.", "cite": cite(f"{s}:eligibility:n/a")},
                    "governing_document": {"text": "The brochure is the official statement of benefits.", "cite": cite(f"{s}:official_statement:n/a")},
                    "verification": {"date": RETRIEVED, "method": SOURCES[s].get("retrieval_method"), "note": "Brochure text was reachable to about page 33 (71 pages). Rate pages, Section 7 exclusions, endodontic/prosthodontic/implant/occlusal-guard rows were not reliably returned and remain UNKNOWN."}},
        "source_document": source_document(s),
        "benefit_year_start_month": V(f"{s}:benefit_period:n/a", value=1),
        "deductible_individual": V(ded_in, note="in-network deductible is $0 per person (Class A, B and C rows)"),
        "deductible_individual_out": V(ded_out, note="out-of-network deductible per person per calendar year; tracked separately — enter your remaining out-of-network deductible for out-of-network estimates"),
        "deductible_family": unknown("Family deductible not stated in the returned text (deductible printed per person).", f"{s}:deductible_family:n/a"),
        "deductible_waived_classes": [],
        "deductible_waiver_note": "The deductible table shows the same values for Class A, B and C rows ($0 in-network); orthodontics $0.",
        "annual_max": annual_max,
        "annual_max_out": ({"value": None, "status": "DOC", "unlimited": True, "cite": cite(f"{s}:annual_max:{option}"), "note": "Out-of-network row also 'Unlimited'."} if amax["value"] is None
                           else {"value": amax["value"], "status": "DOC", "cite": cite(f"{s}:annual_max:{option}"), "note": "Out-of-network row prints the same $2,000; whether in- and out-of-network maximums are combined was not stated."}),
        "classes": classes, "class_of": class_of,
        "allowed_amounts": {}, "allowed_amounts_note": "The brochure prints no fee schedule. 'Plan Allowance' is 'the maximum amount we will consider for payment for a specific procedure' (p.59); the amount must come from your pre-treatment estimate or EOB (USER).",
        "alternate_benefit": {"status": "DOC", "cite": cite(f"{s}:alternate_benefit:n/a"), "conditions": [],
                              "note": "Clause present (p.18): benefits are paid on a less costly covered service that 'would produce a professionally acceptable result'. The readable pages do not list which services it applies to, so no condition is modeled; the ledger flags the possibility."},
        "waiting_months": unknown("No sentence containing 'waiting' was found in the readable text; because the text was truncated this is UNKNOWN, not 'no waiting period'.", f"{s}:waiting_period:n/a"),
        "frequency": frequency, "excluded": {},
        "missing_tooth": {"present": None, "status": "UNKNOWN", "note": "Section 7 General Exclusions (p.50) was not reliably extracted."},
        "oon_rule": {"value": {"in": fact(f"{s}:in_network_basis:n/a")["quote"], "out": fact(f"{s}:oon_basis:n/a")["quote"] + ". Out-of-Network providers may charge their normal fees which may be greater than the Plan Allowance."},
                     "status": "DOC", "cite": cite(f"{s}:oon_basis:n/a"), "in_network_cite": cite(f"{s}:in_network_basis:n/a"), "plan_allowance_cite": cite(f"{s}:plan_allowance_definition:n/a")},
        "dos_rule": unknown("Not stated in the readable pages; computed with the completion date and labeled as an assumption."),
        "premium_monthly": {"self_only": unknown("Rate Information (p.71) was not returned by the text extraction; rates depend on the rating area for your ZIP code (North Carolina's area not determined).", f"{s}:premium_monthly:n/a")},
        "unsupported_rules": [
            unsupported(f"{s}:frequency:fillings_replacement", "replacement restorations limited to 1 in 24 months — replacement rule, not enforced"),
            unsupported(f"{s}:prior_service_counts:n/a", "services before the effective date may count toward frequency limits — history entered by the user is counted regardless of plan"),
            unsupported(f"{s}:frequency:night_guard", "occlusal guard frequency changed to 1 in 24 months for 2026 — class/coinsurance for the appliance not readable"),
            unsupported(f"{s}:ortho_lifetime_max:High", "orthodontia lifetime maximum — not modeled; figures from a single fetch"),
            unsupported(f"{s}:coinsurance:both:classD", "Class D Orthodontic 50% — not modeled"),
        ],
        "conflicts": conflicts_of(s),
        "procedure_codes": mapping_codes(s),
        "reuse_terms_cite": cite(f"{s}:reuse_terms:n/a"),
    }
    return plan


def build_fd26(option: str) -> dict:
    s = "opm-fedvip-delta-2026"
    code = {"High": "FD26H", "Standard": "FD26S"}[option]
    cd = lambda c: (f"{s}:coinsurance:{c}:{option}:in", f"{s}:coinsurance:{c}:{option}:out")
    classes = _fedvip_classes(s, option, [
        ("Class A Basic", *cd("ClassA"), ["Diagnostic Services (evaluations, bitewings)", "Preventive Services (prophylaxis, fluoride, sealants)"], f"{s}:class_membership:exam"),
        ("Class B Intermediate", *cd("ClassB"), ["Restorative Services (fillings)", "Periodontic Services (scaling and root planing)", "Oral Surgery (extractions)"], f"{s}:class_membership:composite"),
        ("Class C Major", *cd("ClassC"), ["Major Restorative Services (crowns)", "Endodontic Services (root canals)", "Prosthodontic Services (partial dentures)"], f"{s}:class_membership:crown"),
    ])
    cm = lambda k, name, note="": {"value": name, "status": "DOC", "cite": cite(f"{s}:class_membership:{k}"), "note": note or f"code line printed under {name}"}
    class_of = {
        "exam": cm("exam", "Class A Basic"), "cleaning": cm("cleaning", "Class A Basic"), "bitewing_xrays": cm("bitewing_xrays", "Class A Basic"),
        "fluoride_child": cm("fluoride_child", "Class A Basic"), "sealant": cm("sealant", "Class A Basic"),
        "composite": cm("composite", "Class B Intermediate"), "amalgam": cm("amalgam", "Class B Intermediate"), "extraction_simple": cm("extraction_simple", "Class B Intermediate"),
        "extraction_surgical": cm("extraction_surgical", "Class B Intermediate"), "scaling_root_planing": cm("scaling_root_planing", "Class B Intermediate"),
        "root_canal_molar": cm("root_canal_molar", "Class C Major", "root canals are Class C (Major) in this brochure"), "crown": cm("crown", "Class C Major"),
        "cast_crown": cm("cast_crown", "Class C Major"), "denture_partial": cm("denture_partial", "Class C Major"),
        "implant": unknown("The Implant Services subsection lies after the readable pages (~p.30). Section 4 states a $2,500 per-person per-calendar-year implant limit under the High Option.", f"{s}:class_membership:implant"),
        "night_guard": unknown("Occlusal guard appliance codes (D9944–D9946) do not appear in readable pages 1–29; only 'D9936 Cleaning and inspection of occlusal guard' (2026 change) was found.", f"{s}:class_membership:night_guard"),
    }
    frequency = [
        {"procedure_key": "exam", "clock": "calendar_count", "n": 2, "cite": cite(f"{s}:frequency:exam"), "period_as_printed": "Limited to two in a calendar year"},
        {"procedure_key": "cleaning", "clock": "calendar_count", "n": 2, "cite": cite(f"{s}:frequency:cleaning"), "period_as_printed": "Limited to two in a calendar year (or three for a pregnant individual)"},
        {"procedure_key": "bitewing_xrays", "clock": "calendar_count", "n": 1, "cite": cite(f"{s}:frequency:bitewing_xrays"), "period_as_printed": "Limited to one in a calendar year (each bitewing code line)"},
        {"procedure_key": "fluoride_child", "clock": "calendar_count", "n": 2, "cite": cite(f"{s}:frequency:fluoride_child"), "period_as_printed": "Limited to two in a calendar year"},
        {"procedure_key": "sealant", "clock": "per_tooth_months", "n": 36, "cite": cite(f"{s}:frequency:sealant"), "period_as_printed": "Limited to one in 36 months (per tooth; permanent molars free from caries; patients under 19)", "note": "per tooth — not enforced"},
        {"procedure_key": "scaling_root_planing", "clock": "per_quadrant_months", "n": 24, "cite": cite(f"{s}:frequency:scaling_root_planing"), "period_as_printed": "Payable once per quadrant in 24 months", "note": "per quadrant — not enforced"},
        {"procedure_key": "cast_crown", "clock": "per_tooth_months", "n": 60, "cite": cite(f"{s}:frequency:cast_crown"), "period_as_printed": "Limited to once in five years", "note": "per-tooth wording not printed; not enforced"},
        {"procedure_key": "crown", "clock": "per_tooth_months", "n": 60, "cite": cite(f"{s}:frequency:crown"), "period_as_printed": "replacement covered only if the existing crown was inserted at least five years prior", "note": "replacement rule; not enforced"},
    ]
    amax_in = fact(f"{s}:annual_max:{option}:in"); amax_out = fact(f"{s}:annual_max:{option}:out")
    annual_max = V(f"{s}:annual_max:{option}:in")
    if amax_in["value"] is None:
        annual_max.update({"unlimited": True, "note": "In-network High Option cell reads 'Unlimited'. Implants carry their own $2,500 per-person limit under the High Option."})
    plan = {
        "plan_code": code, "title": f"Delta Dental's Federal Employees Dental Program 2026 — {option} Option (FEDVIP, nationwide)", "carrier_text": "Delta Dental of California", "is_fictional": False,
        "catalog": {"carrier": fact(f"{s}:carrier:n/a")["value"], "plan_name": "Delta Dental's Federal Employees Dental Program (FEDVIP brochure 02AP-05; contract OPM02-FEDVIP-02AP-05)", "option": f"{option} Option", "plan_year": 2026,
                    "benefit_year_type": "calendar", "region": "Nationwide plus international (includes North Carolina); five rating regions by home ZIP code", "network": fact(f"{s}:network_names:n/a")["value"],
                    "effective_dates": {"start": "2026-01-01", "end": "2026-12-31", "text": "Plan year January 1, 2026 to December 31, 2026", "cite": cite(f"{s}:benefit_year:n/a")},
                    "where_offered": {"text": SOURCES[s]["scope"]["geography"], "cite": cite(f"{s}:rating_regions:n/a")},
                    "eligibility": {"text": fact(f"{s}:eligibility:n/a")["value"] + ". Listed here means the document is public — not that you are eligible to enroll.", "cite": cite(f"{s}:eligibility:n/a")},
                    "governing_document": {"text": "The brochure is the official statement of benefits.", "cite": cite(f"{s}:official_statement:n/a")},
                    "verification": {"date": RETRIEVED, "method": SOURCES[s].get("retrieval_method"), "note": "Brochure pages 1–29 of 62 were readable; table cells on pp.15–16 were returned as 'label: value' renderings (needs_review). Pages 30–62 (implants, occlusal guards, exclusions, definitions, rates/regions) remain UNKNOWN."}},
        "source_document": source_document(s),
        "benefit_year_start_month": V(f"{s}:benefit_year:n/a", value=1),
        "deductible_individual": V(f"{s}:deductible_individual:{option}:in", note="in-network deductible $0 for every class row"),
        "deductible_individual_out": V(f"{s}:deductible_individual:{option}:out", note="out-of-network deductible per enrolled covered person (Class B and Class C rows; Class A and D rows $0); whether one combined amount across B and C is not stated"),
        "deductible_family": {"value": None, "status": "DOC", "cite": cite(f"{s}:deductible_family:n/a"), "note": "'There is no family deductible limit.' — each enrolled person satisfies their own deductible"},
        "deductible_waived_classes": ["Class A Basic"],
        "deductible_waiver_note": "Out-of-network deductible applies to Class B and Class C rows only (Class A and D rows show $0). In-network the deductible is $0 for every class.",
        "annual_max": annual_max,
        "annual_max_out": ({"value": amax_out["value"], "status": amax_out.get("status", "DOC"), "cite": cite(f"{s}:annual_max:{option}:out"), "note": "Annual Benefit Maximums within each option are combined between in- and out-of-network services; the out-of-network figure is the lower cap when you use an out-of-network dentist."}),
        "annual_max_rule_cite": cite(f"{s}:annual_max_rule:n/a"),
        "classes": classes, "class_of": class_of,
        "allowed_amounts": {}, "allowed_amounts_note": "The brochure prints no fee schedule. 'The plan allowance is the amount we allow for a specific procedure' (p.13); the amount must come from your pre-treatment estimate or EOB (USER).",
        "alternate_benefit": {"status": "DOC", "cite": cite(f"{s}:alternate_benefit:n/a"), "conditions": [],
                              "note": "Clause present (p.13): Delta Dental 'reserves the right to authorize an alternate, less costly covered service'. The readable pages do not list which services it applies to; the ledger flags the possibility."},
        "waiting_months": unknown("No 'waiting period' text in readable pages 1–29; Summary of Benefits and Sections 7/9 not readable — UNKNOWN, not 'none'.", f"{s}:waiting_period:{option}"),
        "frequency": frequency, "excluded": {},
        "missing_tooth": {"present": None, "status": "UNKNOWN", "note": "Section 7 General Exclusions not readable."},
        "oon_rule": {"value": {"in": "You pay the coinsurance percentage of our network allowance for covered services. You are not responsible for charges above that allowance.", "out": fact(f"{s}:oon_basis:n/a")["quote"]},
                     "status": "DOC", "cite": cite(f"{s}:oon_basis:n/a"), "section4_cite": cite(f"{s}:oon_basis_section4:n/a")},
        "dos_rule": unknown("Not stated in the readable pages; computed with the completion date and labeled as an assumption."),
        "premium_monthly": {"self_only": unknown("Rate pages at the end of the brochure were not readable and North Carolina's rating region could not be determined from an official page (OPM's rating-region spreadsheet is a binary file the sanctioned fetch cannot read).", f"{s}:premium_monthly:{option}")},
        "unsupported_rules": [
            unsupported(f"{s}:implant_max:{option}", "implant annual limit — implants' class is not readable, so no implant line can be computed"),
            unsupported(f"{s}:frequency:composite", "repair/replacement of a restoration by the same dentist within 24 months is integral to the original — replacement rule, not enforced"),
            unsupported(f"{s}:frequency:root_canal_molar", "retreatment within 24 months by the same dentist is part of the original procedure — not enforced"),
            unsupported(f"{s}:age_limit:crown", "single crowns excluded for members 12 or younger unless rationale is provided — age is not collected"),
            unsupported(f"{s}:age_limit:sealant", "sealants: permanent molars free from caries, patients under 19 — age is not collected"),
            unsupported(f"{s}:pretreatment_estimate:n/a", "non-binding pre-treatment estimate available on request — informational"),
            unsupported(f"{s}:coinsurance:ClassD:both:both", "Class D Orthodontic 50% — not modeled"),
        ],
        "conflicts": conflicts_of(s),
        "procedure_codes": mapping_codes(s),
    }
    return plan


# --------------------------------------------------------------------------------------------------------------------------
# Registry, evidence, procedure codes, fee benchmarks
# --------------------------------------------------------------------------------------------------------------------------
def build_registry(presets: dict[str, dict]) -> dict:
    supports = defaultdict(set)
    for code, p in presets.items():
        supports[p["source_document"]["source_id"]].add(code)
        for sd in p.get("secondary_documents", []):
            supports[sd["source_id"]].add(code)
    items = []
    for sid, s in SOURCES.items():
        facts = s.get("facts", [])
        items.append({
            "source_id": sid, "version_label": LABELS.get(sid), "title": s["title"], "publisher": s["publisher"], "url": s["url"], "secondary_urls": s.get("secondary_urls", []),
            "document_type": s.get("document_type"), "document_date": s.get("document_date"), "effective_period": s.get("effective_period"), "scope": s.get("scope"),
            "retrieved_at": s.get("retrieved_at", RETRIEVED), "retrieval_method": s.get("retrieval_method"), "pages_total": s.get("pages_total"),
            "reuse_terms": s.get("reuse_terms"), "access_limits": s.get("access_limits", []),
            "counts": {"facts": len(facts), "by_status": dict(Counter(f.get("status") for f in facts)), "procedure_mappings": len(s.get("procedure_mappings", [])),
                       "conflicts": len(s.get("conflicts", [])), "gaps": len(s.get("gaps", []))},
            "supports_plan_codes": sorted(supports.get(sid, [])),
            "contributes": {"plan_rules": sid in ("ncflex-2026-plan-details", "ncflex-metlife-classic-certificate-2020", "ncflex-metlife-high-certificate-2018", "ncflex-metlife-low-certificate-2020",
                                                   "delta-msu-eoc-2024", "opm-fedvip-metlife-2026", "opm-fedvip-delta-2026", "delta-dental-nc-individual-2026"),
                            "premiums": sid in ("ncflex-2026-plan-details", "msu-dental-benefit-highlights-2021", "delta-dental-nc-individual-2026"),
                            "procedure_codes": len(s.get("procedure_mappings", [])) > 0, "fee_benchmarks": sid == "nc-medicaid-dental-fees", "reuse_terms": sid == "ada-cdt-license-terms"},
            "gaps": s.get("gaps", []),
        })
    return {"label": "OralCompass source inventory — every imported record points back to one of these documents", "generated_from": "sources/extracted/*.json via tools/ingest_sources.py",
            "retrieval_note": "All documents were read through the sanctioned text-extraction fetch; binary downloads from these hosts are blocked by the build environment's egress policy, so SHA-256 values and physical PDF page indexes are pending (see each access_limits).",
            "items": items}


def build_evidence() -> dict[str, list[dict]]:
    out = {}
    for sid, s in SOURCES.items():
        rows = []
        for f in s.get("facts", []):
            rows.append({"evidence_id": f.get("fact_id"), "source_id": sid, "doc": LABELS.get(sid), "field": f.get("field"), "plan_option": f.get("plan_option"), "procedure_key": f.get("procedure_key"),
                         "external_code": f.get("external_code"), "value": f.get("value"), "unit": f.get("unit"), "basis": f.get("basis"), "network": f.get("network"),
                         "quote": f.get("quote"), "page": page_int(f.get("page")), "page_label": page_label(f), "section": f.get("section"), "status": f.get("status"),
                         "confidence": f.get("confidence"), "review_status": f.get("review_status"), "notes": f.get("notes"), "effective_date_as_printed": f.get("effective_date_as_printed"),
                         "end_date_as_printed": f.get("end_date_as_printed")})
        out[sid] = rows
    return out


def build_procedure_codes() -> dict:
    """Explicit mapping internal key → candidate external codes, each tied to the document where the code was printed."""
    by_key: dict[str, list[dict]] = defaultdict(list)
    seen = set()
    for sid in ("cdt-procedure-mapping", "nc-medicaid-dental-fees", "opm-fedvip-metlife-2026", "opm-fedvip-delta-2026"):
        for m in SOURCES.get(sid, {}).get("procedure_mappings", []):
            if not m.get("external_code") or not m.get("quote"):
                continue
            doc = m.get("document_id") or LABELS.get(sid) or sid
            key = (m["internal_key"], m["external_code"], doc)
            if key in seen:
                continue
            seen.add(key)
            by_key[m["internal_key"]].append({"system": m.get("external_system", "CDT"), "code": m["external_code"], "descriptor_as_printed": m.get("descriptor_as_printed"), "quote": m["quote"],
                                              "document": m.get("document") or SOURCES[sid]["title"], "document_id": doc, "document_url": m.get("document_url") or SOURCES[sid]["url"],
                                              "page": m.get("page"), "confidence": m.get("confidence"), "review": bool(m.get("review")), "notes": m.get("notes", ""), "source_id": sid})
    items = []
    for key in PROCEDURE_KEYS:
        cands = by_key.get(key, [])
        codes = Counter(c["code"] for c in cands)
        primary = codes.most_common(1)[0][0] if codes else None
        distinct = sorted(codes)
        review = (len(distinct) > 1) or any(c["review"] for c in cands) or primary is None
        items.append({"procedure_key": key, "primary_code": primary, "primary_code_document_count": codes[primary] if primary else 0, "distinct_codes_seen": distinct,
                      "review_required": review,
                      "review_reason": (None if not review else ("no code printed in any opened document" if primary is None else
                                        "more than one code could apply to this internal key — the user's own estimate/claim decides" if len(distinct) > 1 else "an extraction flagged this mapping for review")),
                      "candidates": cands})
    return {"label": "External procedure-code mappings for the 16 fixed internal procedure keys (identifiers preserved; codes shown only as printed in opened documents)",
            "policy": "Internal keys are never renamed. A mapping is a pointer to where a code was printed, not an assertion that the user's procedure IS that code; a code printed on the user's "
                      "own estimate or claim (USER) takes precedence. Mappings with review_required=true are shown with their alternatives, never silently chosen.",
            "reuse_terms": {"source_id": "ada-cdt-license-terms", "note": "CDT is copyrighted by the American Dental Association; this file does not reproduce the CDT catalog. Code numbers and descriptors appear only as printed in the cited public documents (each carries its own ADA notice)."},
            "items": items}


def build_fee_benchmarks(codes: dict) -> dict:
    s = SOURCES["nc-medicaid-dental-fees"]
    key_by_code = defaultdict(set)
    for it in codes["items"]:
        for c in it["candidates"]:
            key_by_code[c["code"]].add(it["procedure_key"])
    rows = []
    for f in s.get("facts", []):
        if f.get("field") != "fee":
            continue
        rows.append({"code": f.get("external_code"), "payer": "NC Medicaid (North Carolina Department of Health and Human Services)", "geography": "North Carolina", "purpose": "Medicaid reimbursement rate (public program payment to providers)",
                     "rate_cents": f.get("value"), "status": f.get("status"), "quote": f.get("quote"), "effective_date_as_printed": f.get("effective_date_as_printed"), "end_date_as_printed": f.get("end_date_as_printed"),
                     "schedule_revision": s.get("document_date"), "source_id": "nc-medicaid-dental-fees", "doc": LABELS["nc-medicaid-dental-fees"], "url": s["url"], "page": page_label(f),
                     "mapped_internal_keys": sorted(key_by_code.get(f.get("external_code"), [])), "notes": f.get("notes"),
                     "not_a_price": "This is a public-program reimbursement rate. It is not your dentist's fee, not your plan's allowed amount and not a commercial price. It is shown only as a labeled reference and is never used in an estimate unless you enter it yourself as a hypothetical."})
    return {"label": "Published fee references (benchmarks) — labeled by payer, geography, date and purpose; kept separate from dentist fees and allowed amounts",
            "source": {"source_id": "nc-medicaid-dental-fees", "title": s["title"], "publisher": s["publisher"], "url": s["url"], "document_date": s.get("document_date"), "effective_period": s.get("effective_period"),
                       "retrieved_at": s.get("retrieved_at"), "reuse_terms": s.get("reuse_terms"), "access_limits": s.get("access_limits", []), "scope": s.get("scope")},
            "rows": rows}


# --------------------------------------------------------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------------------------------------------------------
def validate_plan(path: Path, j: dict) -> list[str]:
    errs = []
    code = j["plan_code"]
    for k in j.get("class_of", {}):
        if k not in PROCEDURE_KEYS:
            errs.append(f"{code}: class_of key '{k}' is not an internal procedure key")
    class_names = {c["name"] for c in j["classes"]}
    for k, v in j.get("class_of", {}).items():
        if v.get("status") not in VALID_STATUS:
            errs.append(f"{code}: class_of.{k} has invalid status {v.get('status')}")
        if v.get("value") is not None and v["value"] not in class_names:
            errs.append(f"{code}: class_of.{k} = '{v['value']}' has no class rule")
        if v.get("status") == "UNKNOWN" and v.get("value") is not None:
            errs.append(f"{code}: class_of.{k} UNKNOWN must have null value")
    for f in j.get("frequency", []):
        if f["procedure_key"] not in PROCEDURE_KEYS:
            errs.append(f"{code}: frequency key '{f['procedure_key']}' is not an internal procedure key")
        if f["clock"] not in VALID_CLOCKS:
            errs.append(f"{code}: frequency clock '{f['clock']}' invalid")
        if not isinstance(f.get("n"), int) or f["n"] <= 0:
            errs.append(f"{code}: frequency n must be a positive integer")
        if not f.get("cite"):
            errs.append(f"{code}: frequency rule for {f['procedure_key']} has no cite")
    for k in j.get("excluded", {}):
        if k not in PROCEDURE_KEYS:
            errs.append(f"{code}: excluded key '{k}' is not an internal procedure key")
    for name in ("deductible_individual", "annual_max", "benefit_year_start_month"):
        v = j.get(name)
        if not v or v.get("status") not in VALID_STATUS:
            errs.append(f"{code}: {name} missing or invalid status")
        elif v["status"] == "DOC" and not v.get("cite"):
            errs.append(f"{code}: {name} is DOC without a cite")
        elif v["status"] == "DOC" and v.get("value") is None and not v.get("unlimited"):
            errs.append(f"{code}: {name} is DOC with null value")
    for c in j["classes"]:
        for side in ("plan_share_bp_in", "plan_share_bp_out"):
            bp = c[side]["value"]
            if not (isinstance(bp, int) and 0 <= bp <= 10000):
                errs.append(f"{code}: class {c['name']} {side} out of range: {bp}")
            if not c[side].get("cite"):
                errs.append(f"{code}: class {c['name']} {side} has no cite")
    for k, v in j.get("premium_monthly", {}).items():
        if v.get("status") not in VALID_STATUS:
            errs.append(f"{code}: premium {k} invalid status")
        if v.get("value") is not None and (not isinstance(v["value"], int) or v["value"] <= 0):
            errs.append(f"{code}: premium {k} must be positive integer cents")
    # every cite must point to an existing fact with the same quote
    def walk(o):
        if isinstance(o, dict):
            if "fact_id" in o and "quote" in o and o.get("fact_id") in FACTS and FACTS[o["fact_id"]].get("quote") != o["quote"]:
                errs.append(f"{code}: cite quote differs from fact {o['fact_id']}")
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)
    walk(j)
    # loader round trip
    try:
        pm = load_plan(path)
        coverage_rules(pm)
    except Exception as ex:  # noqa: BLE001
        errs.append(f"{code}: loader/rules failed: {ex!r}")
    return errs


def main(check_only: bool = False) -> int:
    load_sources()
    presets = {
        "ml26": build_ml26("Classic"), "ml26h": build_ml26("High"), "ml26l": build_ml26("Low"),
        "dd24": build_dd24("High"), "dd24l": build_dd24("Low"),
        "fm26h": build_fm26("High"), "fm26s": build_fm26("Standard"),
        "fd26h": build_fd26("High"), "fd26s": build_fd26("Standard"),
    }
    codes = build_procedure_codes()
    benchmarks = build_fee_benchmarks(codes)
    registry = build_registry({p["plan_code"]: p for p in presets.values()})
    evidence = build_evidence()

    out_dir = FIX / "plans"
    written = []
    errors = list(PROBLEMS)
    if not check_only:
        (FIX / "evidence").mkdir(exist_ok=True)
        for stem, plan in presets.items():
            path = out_dir / f"{stem}.json"
            path.write_text(json.dumps(plan, indent=2, ensure_ascii=False) + "\n")
            written.append(str(path.relative_to(ROOT)))
        (FIX / "sources.json").write_text(json.dumps(registry, indent=2, ensure_ascii=False) + "\n")
        (FIX / "procedure_codes.json").write_text(json.dumps(codes, indent=2, ensure_ascii=False) + "\n")
        (FIX / "fee_benchmarks.json").write_text(json.dumps(benchmarks, indent=2, ensure_ascii=False) + "\n")
        for sid, rows in evidence.items():
            (FIX / "evidence" / f"{sid}.json").write_text(json.dumps({"source_id": sid, "doc": LABELS.get(sid), "rows": rows}, indent=2, ensure_ascii=False) + "\n")
    for stem, plan in presets.items():
        errors += validate_plan(out_dir / f"{stem}.json", plan)

    # ---- report ----
    mapped = [it["procedure_key"] for it in codes["items"] if it["primary_code"]]
    unmapped = [it["procedure_key"] for it in codes["items"] if not it["primary_code"]]
    review = [it["procedure_key"] for it in codes["items"] if it["review_required"]]
    fee_present = [r["code"] for r in benchmarks["rows"] if r["status"] == "DOC"]
    fee_absent = [r["code"] for r in benchmarks["rows"] if r["status"] != "DOC"]
    per_plan = {}
    for stem, plan in presets.items():
        co = plan["class_of"]
        per_plan[plan["plan_code"]] = {
            "class_known": sorted(k for k, v in co.items() if v.get("value") is not None and v["status"] != "UNKNOWN"),
            "class_ambiguous": sorted(k for k, v in co.items() if v["status"] == "AMBIGUOUS"),
            "class_unknown": sorted(k for k, v in co.items() if v["status"] == "UNKNOWN"),
            "excluded": sorted(plan["excluded"]), "not_in_class_of": sorted(set(PROCEDURE_KEYS) - set(co) - set(plan["excluded"])),
            "frequency_rules": len(plan["frequency"]), "codes_printed": len(plan.get("procedure_codes", {})),
            "waiting": plan["waiting_months"]["status"], "alternate_benefit": plan["alternate_benefit"]["status"],
            "premium": {k: v["status"] for k, v in plan["premium_monthly"].items()}, "conflicts": len(plan["conflicts"]),
        }
    report = {
        "generated_at": RETRIEVED, "sources": len(SOURCES), "facts": len(FACTS), "facts_by_status": dict(Counter(f.get("status") for f in FACTS.values())),
        "presets_written": written, "procedure_keys": len(PROCEDURE_KEYS), "procedure_keys_with_code": mapped, "procedure_keys_without_code": unmapped, "procedure_keys_review_required": review,
        "fee_benchmark_rows_present": fee_present, "fee_benchmark_rows_absent": fee_absent, "per_plan": per_plan,
        "conflicts_total": sum(len(s.get("conflicts", [])) for s in SOURCES.values()), "validation_errors": errors,
    }
    if not check_only:
        (FIX / "ingest_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(report, indent=1, ensure_ascii=False))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(check_only="--check" in sys.argv))
